using MddBooster.Core.Ast;
using MddBooster.Core.Semantic;
using MddBooster.Generators.Sql;

namespace MddBooster.Tests.Generators.Sql;

public class TableRendererTests
{
    private static string FixturePath(string name) =>
        Path.Combine(AppContext.BaseDirectory, "fixtures", name);

    [Fact]
    public void Render_BankAccount_ProducesExpectedDdl()
    {
        var ast = new M3lLoader().LoadFile(FixturePath("bank-account.m3l.md"));
        var resolved = new InterfaceResolver(ast).ResolveAll().Single(m => m.Name == "BankAccount");

        var sql = TableRenderer.Render(resolved, schema: "dbo");

        var expected = """
-- # Code generated by "mdd-booster"; DO NOT EDIT.
CREATE TABLE [dbo].[BankAccount]
(
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    [BankName] NVARCHAR(30) NOT NULL,
    [AccountNumber] NVARCHAR(40) NOT NULL,
    [HolderName] NVARCHAR(30) NOT NULL,
    [Note] NVARCHAR(200) NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    [CreatedAt] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    [UpdatedAt] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CONSTRAINT [UK_BankAccount_AccountNumber] UNIQUE NONCLUSTERED ([AccountNumber])
)
GO
""";

        Assert.Equal(Normalize(expected), Normalize(sql));
    }

    private static string Normalize(string s) =>
        s.Replace("\r\n", "\n").TrimEnd() + "\n";
}
