using System.Text;
using M3L.Native;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Sql.Postgres;

/// <summary>
/// PG 방언 <c>{table}_full_view</c> 렌더러 — T-SQL <see cref="FullViewRenderer"/>의 등가물.
/// Lookup(LEFT JOIN)·Rollup(상관 서브쿼리) 파생 필드만 지원한다. 식별자는 ADR-0001을 따라
/// 전부 비인용 snake_case이고, JOIN/서브쿼리 대상 컬럼은 m3l 필드명을 그대로 쓴다(대소문자
/// 변환 없음 — PascalCase 변환은 <see cref="FullViewRenderer.IsDerivedColumn"/> 게이트를
/// 재사용할 때만 국소적으로 계산한다).
/// <para>
/// <b>Computed 필드는 이 렌더러의 범위 밖이다.</b> T-SQL 쪽의 <c>NormalizeComputedExpression</c>은
/// 저자가 쓴 표현식 문자열을 정규식으로 재작성하는데, PG는 문자열 연결(<c>||</c> vs T-SQL
/// <c>+</c>) 등 표현식 문법 자체가 달라 같은 방식의 안전한 재작성을 보장할 수 없다 — 검증 없는
/// 변환기가 조용히 틀린 SQL을 만드는 위험이, 지금처럼 명시적으로 거절하는 것보다 나쁘다. Computed
/// 필드가 있는 모델은 호출자(<see cref="PostgresSqlGenerator"/>)가 이 렌더러를 아예 부르지 않고
/// 기존 stderr 경고로 표면화한다.
/// </para>
/// <para>
/// <b>인덱싱된 Rollup(<c>@indexed</c>)도 범위 밖이다.</b> T-SQL의 <c>WITH SCHEMABINDING</c> +
/// 인덱스 뷰에 대응하는 PG 개념은 구체화 뷰(<c>MATERIALIZED VIEW</c>)인데, 이는 갱신 시점·트리거
/// 설계가 필요한 별개의 아키텍처 결정이라 이 렌더러가 임의로 선택하지 않는다 — 마찬가지로
/// 호출자가 걸러 경고로 표면화한다.
/// </para>
/// </summary>
public static class PgFullViewRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    /// <param name="plan">모델의 뷰 플랜.</param>
    /// <param name="schema">PG 스키마명(비인용).</param>
    /// <param name="tableNameMap">모델명 → PG 테이블명(snake_case) 맵.</param>
    /// <param name="viewNameMap">FullView가 필요한 모델명 → 그 PG 뷰명(<c>{table}_full_view</c>) 맵.</param>
    /// <param name="modelLookup">모델명 → <see cref="ResolvedModel"/> 맵(참조 대상 PK 조회용).</param>
    /// <param name="derivedFieldsByModel">
    /// 모델명 → 그 모델 자신의 파생(Lookup/Rollup/Computed) 필드의 PascalCase 이름 집합.
    /// <see cref="FullViewRenderer.IsDerivedColumn"/> 게이트 재사용 전용 — SQL 텍스트에는
    /// 나타나지 않는다(T-SQL 쪽과 동일한 딕셔너리를 그대로 공유해도 무방).
    /// </param>
    public static string Render(
        ViewPlan plan,
        string schema,
        IReadOnlyDictionary<string, string> tableNameMap,
        IReadOnlyDictionary<string, string> viewNameMap,
        IReadOnlyDictionary<string, ResolvedModel> modelLookup,
        IReadOnlyDictionary<string, IReadOnlySet<string>> derivedFieldsByModel)
    {
        ArgumentNullException.ThrowIfNull(plan);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);
        if (!plan.NeedsFullView)
            throw new InvalidOperationException($"모델 '{plan.Model.Name}'은 FullView가 필요 없습니다.");

        var model = plan.Model;
        var tableName = tableNameMap[model.Name];
        var viewName = viewNameMap[model.Name];
        var sourceRelation = plan.NeedsUdView ? UdViewNameOf(tableName) : tableName;
        const string baseAlias = "b";

        var basePk = ModelPrimaryKey.Find(model)
            ?? throw new InvalidOperationException($"모델 '{model.Name}'에 PK가 없어 Rollup 상관 서브쿼리를 렌더할 수 없습니다.");

        var baseColumns = BaseColumns.StoredFields(model, excludeFieldInternal: true).Select(f => f.Name);
        var baseProjection = string.Join(", ", baseColumns.Select(c => baseAlias + "." + c));

        var lookups = plan.Lookups.Where(f => !EntitySurface.IsFieldInternal(f)).ToList();
        var rollups = plan.Rollups.Where(f => !EntitySurface.IsFieldInternal(f)).ToList();

        // --- JOIN (FK 하나당 하나, 같은 FK를 공유하는 여러 Lookup은 같은 JOIN을 공유) ---
        var lookupsByFk = lookups
            .Select(lookup =>
            {
                var path = lookup.Lookup?.Path
                    ?? throw new InvalidOperationException(
                        $"Lookup 필드 '{model.Name}.{lookup.Name}'에 파싱된 LookupDef가 없습니다.");
                var (fkField, targetColumn) = FullViewRenderer.ParsePath(path);
                return (lookup, fkField, targetColumn);
            })
            .GroupBy(x => x.fkField, StringComparer.Ordinal);

        var joinsByFk = new Dictionary<string, (string TargetRelation, string Alias)>(StringComparer.Ordinal);
        var lookupColumns = new List<(string expr, string alias)>();
        foreach (var group in lookupsByFk)
        {
            var fkField = group.Key;
            var targetModelName = FullViewRenderer.ResolveReferenceTarget(model, fkField);
            var targetModel = modelLookup.TryGetValue(targetModelName, out var tm)
                ? tm
                : throw new InvalidOperationException($"참조 대상 모델 '{targetModelName}'을(를) 찾을 수 없습니다.");
            var targetPk = ModelPrimaryKey.Find(targetModel)
                ?? throw new InvalidOperationException($"참조 대상 모델 '{targetModelName}'에 PK가 없어 JOIN을 렌더할 수 없습니다.");

            var needsFullView = group.Any(x =>
                FullViewRenderer.IsDerivedColumn(derivedFieldsByModel, targetModelName, NameCasing.ToPascalCase(x.targetColumn)));
            var targetTable = tableNameMap[targetModelName];
            var targetRelation = needsFullView ? viewNameMap[targetModelName] : targetTable;

            var alias = "j_" + fkField;
            joinsByFk[fkField] = (targetRelation, alias);

            foreach (var (lu, _, targetColumn) in group)
                lookupColumns.Add(($"{alias}.{targetColumn}", lu.Name));
        }

        // --- Rollup 상관 서브쿼리 ---
        var rollupColumns = new List<(string expr, string alias)>();
        foreach (var rollup in rollups)
        {
            var def = rollup.Rollup
                ?? throw new InvalidOperationException(
                    $"Rollup 필드 '{model.Name}.{rollup.Name}'에 파싱된 RollupDef가 없습니다.");
            rollupColumns.Add((RenderRollupSubquery(def, schema, baseAlias, basePk.Name, tableNameMap, viewNameMap, derivedFieldsByModel), rollup.Name));
        }

        var allProjected = lookupColumns.Concat(rollupColumns).ToList();

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE VIEW ").Append(schema).Append('.').Append(viewName).AppendLine(" AS");
        sb.Append("SELECT ").Append(baseProjection);
        foreach (var (expr, alias) in allProjected)
        {
            sb.AppendLine(",");
            sb.Append("    ").Append(expr).Append(" AS ").Append(alias);
        }
        sb.AppendLine();
        sb.Append("FROM ").Append(schema).Append('.').Append(sourceRelation).AppendLine(" AS b");
        foreach (var (fkField, join) in joinsByFk.OrderBy(kv => kv.Value.Alias, StringComparer.Ordinal))
        {
            var targetPkName = ResolveTargetPkName(model, fkField, modelLookup);
            sb.Append("LEFT JOIN ").Append(schema).Append('.').Append(join.TargetRelation)
              .Append(" AS ").Append(join.Alias)
              .Append(" ON b.").Append(fkField).Append(" = ").Append(join.Alias).Append('.').AppendLine(targetPkName);
        }
        // FROM/JOIN 라인들은 전부 AppendLine으로 끝났다 — 마지막 개행을 지우고 문장을 종결한다.
        sb.Length -= Environment.NewLine.Length;
        sb.AppendLine(";");
        return sb.ToString();
    }

    private static string ResolveTargetPkName(
        ResolvedModel model, string fkField, IReadOnlyDictionary<string, ResolvedModel> modelLookup)
    {
        var targetModelName = FullViewRenderer.ResolveReferenceTarget(model, fkField);
        var targetModel = modelLookup[targetModelName];
        var targetPk = ModelPrimaryKey.Find(targetModel)
            ?? throw new InvalidOperationException($"참조 대상 모델 '{targetModelName}'에 PK가 없습니다.");
        return targetPk.Name;
    }

    internal static string RenderRollupSubquery(
        RollupDef def,
        string schema,
        string baseAlias,
        string basePkName,
        IReadOnlyDictionary<string, string> tableNameMap,
        IReadOnlyDictionary<string, string> viewNameMap,
        IReadOnlyDictionary<string, IReadOnlySet<string>> derivedFieldsByModel)
    {
        var target = def.Target;
        var fkColumn = def.Fk;
        var aggregate = (def.Aggregate ?? "count").Trim().ToLowerInvariant();
        var field = def.Field;

        var targetTable = tableNameMap[target];
        var fromRelation = !string.IsNullOrEmpty(field)
            && FullViewRenderer.IsDerivedColumn(derivedFieldsByModel, target, NameCasing.ToPascalCase(field))
                ? viewNameMap[target]
                : targetTable;

        var innerExpr = aggregate switch
        {
            "count" => "COUNT(*)",
            "sum" when !string.IsNullOrEmpty(field) => $"COALESCE(SUM({field}), 0)",
            "avg" when !string.IsNullOrEmpty(field) => $"AVG({field})",
            "min" when !string.IsNullOrEmpty(field) => $"MIN({field})",
            "max" when !string.IsNullOrEmpty(field) => $"MAX({field})",
            _ => throw new NotSupportedException(
                $"지원하지 않는 rollup: aggregate='{aggregate}' field='{field}'."),
        };

        var whereClause = $"{fkColumn} = {baseAlias}.{basePkName}";
        if (!string.IsNullOrWhiteSpace(def.Where))
            whereClause += $" AND ({def.Where})";

        return $"(SELECT {innerExpr} FROM {schema}.{fromRelation} WHERE {whereClause})";
    }

    /// <summary>모델의 PG UdView 이름 — <see cref="PostgresSqlGenerator"/>가 같은 규칙으로 계산한다.</summary>
    internal static string UdViewNameOf(string tableName) => tableName + "_ud_view";

    /// <summary>모델의 PG FullView 이름 — <see cref="PostgresSqlGenerator"/>가 같은 규칙으로 계산한다.</summary>
    internal static string FullViewNameOf(string tableName) => tableName + "_full_view";
}
