using System.Text;
using System.Text.Json;
using M3L.Native;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Sql.Postgres;

/// <summary>PG 테이블 렌더 결과 — DDL 본문과, 방출할 수 없어 경고로 표면화한 항목들.</summary>
public sealed record PgTableArtifact(
    string TableName,
    string Sql,
    IReadOnlyList<string> Warnings);

/// <summary>
/// M3L 모델 → PostgreSQL CREATE TABLE 렌더러. 범위는 Schemorph PG P1 능력과 정렬 —
/// 테이블·컬럼·제약(PK/FK/UNIQUE/CHECK)까지만 방출하고, 인덱스는 방출하지 않는다
/// (Schemorph P1이 인덱스를 명시 거부 — 무음 탈락 대신 <see cref="PgTableArtifact.Warnings"/>로
/// 표면화). 식별자는 전부 비인용 snake_case이며(ADR-0001), 컬럼명·제약명도
/// <see cref="PostgresIdentifiers.Check"/> 게이트를 통과해야 한다.
/// 참조 PK는 대상 모델의 <b>PK 물리명</b>으로 렌더한다 — T-SQL 경로의
/// <c>[dbo]</c>·<c>[Id]</c> 하드코딩이 막던 공유 PK 확장 테이블 재참조가 여기선 성립한다.
/// </summary>
public static class PgTableRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static PgTableArtifact Render(
        ResolvedModel model,
        string schema,
        IReadOnlyDictionary<string, string> tableNameMap,
        IReadOnlyDictionary<string, ResolvedModel> modelLookup,
        IReadOnlyDictionary<string, EnumNode>? enumLookup = null,
        bool emitEnumCheckConstraints = false)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);
        ArgumentNullException.ThrowIfNull(tableNameMap);
        ArgumentNullException.ThrowIfNull(modelLookup);

        if (!tableNameMap.TryGetValue(model.Name, out var tableName))
        {
            throw new InvalidOperationException(
                $"모델 '{model.Name}'의 테이블명 매핑이 없습니다 — PostgresIdentifiers.BuildTableNameMap 결과를 전달해야 합니다.");
        }

        var storedFields = BaseColumns.StoredFields(model).ToList();
        var violations = new List<string>();

        // 컬럼명 게이트 — 필드명은 이미 snake_case 관용이지만 패턴·길이·예약어는 통과해야 한다
        foreach (var field in storedFields)
        {
            var violation = PostgresIdentifiers.Check(field.Name);
            if (violation is not null)
            {
                violations.Add($"모델 '{model.Name}' 필드 '{field.Name}': {violation}");
            }
        }

        var warnings = new List<string>();
        var constraints = new List<(string Name, string Body)>();

        // PK — 물리명은 필드명 그대로 (공유 PK 확장 테이블이면 `{parent}_id`)
        var pkField = ModelPrimaryKey.Find(model);
        if (pkField is not null)
        {
            constraints.Add(($"pk_{tableName}", $"PRIMARY KEY ({pkField.Name})"));
        }

        // FK — 대상 테이블명은 변환 맵, 대상 컬럼은 대상 모델의 PK 물리명
        foreach (var field in storedFields)
        {
            var target = GetAttributeFirstParam(field, "reference");
            if (string.IsNullOrEmpty(target)) continue;

            if (!tableNameMap.TryGetValue(target!, out var targetTable))
            {
                throw new InvalidOperationException(
                    $"모델 '{model.Name}' 필드 '{field.Name}'의 참조 대상 '{target}'이(가) 테이블명 매핑에 없습니다.");
            }
            if (!modelLookup.TryGetValue(target!, out var targetModel))
            {
                throw new InvalidOperationException(
                    $"모델 '{model.Name}' 필드 '{field.Name}'의 참조 대상 모델 '{target}'을(를) 찾을 수 없습니다.");
            }
            var targetPk = ModelPrimaryKey.Find(targetModel)
                ?? throw new InvalidOperationException(
                    $"참조 대상 모델 '{target}'에 PK가 없어 FK를 렌더할 수 없습니다.");

            constraints.Add((
                $"fk_{tableName}_{field.Name}",
                $"FOREIGN KEY ({field.Name}) REFERENCES {schema}.{targetTable} ({targetPk.Name})"));
        }

        // field-level @unique — PG UNIQUE는 NULL을 distinct로 취급하므로
        // nullable이어도 filtered index 우회 없이 제약 하나로 정확하다
        foreach (var field in storedFields)
        {
            if (!Has(field, "unique") || Has(field, "pk")) continue;
            constraints.Add(($"uq_{tableName}_{field.Name}", $"UNIQUE ({field.Name})"));
        }

        // field-level @index — Schemorph PG P1이 인덱스를 거부하므로 방출 금지, 경고로 표면화
        foreach (var field in storedFields)
        {
            if (!Has(field, "index") || Has(field, "pk") || Has(field, "unique")) continue;
            warnings.Add(
                $"@index({field.Name})는 방출하지 않음 — Schemorph PG P1은 인덱스를 거부한다 (P2 지원 시 재개)");
        }

        AppendSectionIndexes(model, tableName, constraints, warnings);

        // enum CHECK opt-in — 리터럴은 ANSI 표기('value'), T-SQL의 N'..'와 저장값은 동일
        if (emitEnumCheckConstraints && enumLookup is not null)
        {
            foreach (var field in storedFields)
            {
                if (field.Type is null || !enumLookup.TryGetValue(field.Type, out var enumNode)) continue;
                if (enumNode.Values.Count == 0) continue;

                constraints.Add((
                    $"ck_{tableName}_{field.Name}",
                    $"CHECK ({field.Name} IN ({AnsiCheckValues(enumNode)}))"));
            }
        }

        // 제약명 게이트 — 테이블명·컬럼명이 각각 통과해도 조합(fk_{t}_{c})은 63바이트를
        // 넘을 수 있고, PG는 NOTICE만 내고 조용히 절단한다. 절단 대신 오류.
        foreach (var (name, _) in constraints)
        {
            var violation = PostgresIdentifiers.Check(name);
            if (violation is not null)
            {
                violations.Add($"모델 '{model.Name}' 제약명: {violation}");
            }
        }

        if (violations.Count > 0)
        {
            throw new PostgresNamingException(violations);
        }

        // 렌더
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE TABLE ").Append(schema).Append('.').AppendLine(tableName);
        sb.AppendLine("(");

        var bodyLines = new List<string>();
        bodyLines.AddRange(storedFields.Select(f => RenderColumn(f, enumLookup)));
        bodyLines.AddRange(constraints.Select(c => $"CONSTRAINT {c.Name} {c.Body}"));

        for (var i = 0; i < bodyLines.Count; i++)
        {
            sb.Append("    ").Append(bodyLines[i]);
            if (i < bodyLines.Count - 1)
            {
                sb.Append(',');
            }
            sb.AppendLine();
        }

        sb.AppendLine(");");
        return new PgTableArtifact(tableName, sb.ToString(), warnings);
    }

    private static string RenderColumn(FieldNode field, IReadOnlyDictionary<string, EnumNode>? enumLookup)
    {
        var m3lType = field.Type ?? throw new InvalidOperationException(
            $"필드 '{field.Name}'에 타입이 없습니다.");
        var pgType = PgTypeMapper.MapFieldType(m3lType, ExtractStringParams(field.Params), enumLookup);

        var sb = new StringBuilder();
        sb.Append(field.Name).Append(' ').Append(pgType);
        if (!field.Nullable)
        {
            sb.Append(" NOT NULL");
        }

        // @pk @generated identifier → 서버 생성 UUID (PG 13+ 내장)
        if (Has(field, "pk") && Has(field, "generated") && m3lType == "identifier")
        {
            sb.Append(" DEFAULT gen_random_uuid()");
            return sb.ToString();
        }

        var defaultValue = MddBooster.Core.Ast.FieldAttributes.EffectiveDefault(field);
        if (!string.IsNullOrEmpty(defaultValue))
        {
            var mapped = MapDefaultValue(defaultValue!, m3lType, enumLookup);
            if (mapped is not null)
            {
                sb.Append(" DEFAULT ").Append(mapped);
            }
        }
        return sb.ToString();
    }

    private static string? MapDefaultValue(
        string raw, string m3lType, IReadOnlyDictionary<string, EnumNode>? enumLookup)
    {
        var trimmed = raw.Trim();

        if (m3lType == "boolean")
        {
            return trimmed switch
            {
                "true" => "true",
                "false" => "false",
                _ => null,
            };
        }

        if (string.Equals(trimmed, "now()", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(trimmed, "current_timestamp", StringComparison.OrdinalIgnoreCase))
        {
            return "now()";
        }

        if (double.TryParse(trimmed, out _))
        {
            return trimmed;
        }

        if (trimmed.Length >= 2 && trimmed.StartsWith('"') && trimmed.EndsWith('"'))
        {
            return AnsiLiteral(trimmed.Substring(1, trimmed.Length - 2));
        }

        // enum·string 계열의 quote 없는 raw default — T-SQL 경로와 같은 정책, 리터럴만 ANSI
        if (enumLookup is not null && enumLookup.ContainsKey(m3lType))
        {
            return AnsiLiteral(trimmed);
        }
        if (m3lType == "string" || m3lType == "text"
            || m3lType.StartsWith("string(", StringComparison.OrdinalIgnoreCase))
        {
            return AnsiLiteral(trimmed);
        }

        return null;
    }

    /// <summary>
    /// `### Indexes` 섹션 — `@unique(...)`는 UNIQUE 제약으로 방출(PG NULL-distinct 의미가
    /// 그대로 정확), `@index(...)`는 방출하지 않고 경고 (Schemorph PG P1 인덱스 거부).
    /// </summary>
    private static void AppendSectionIndexes(
        ResolvedModel model, string tableName,
        List<(string Name, string Body)> constraints, List<string> warnings)
    {
        var indexes = model.Source.Sections?.Indexes;
        if (indexes is null || indexes.Count == 0) return;

        foreach (var idxEl in indexes)
        {
            if (idxEl.ValueKind != JsonValueKind.Object) continue;
            if (!idxEl.TryGetProperty("type", out var typeProp)) continue;
            var typeStr = typeProp.GetString();
            if (typeStr != "directive" && typeStr != "indexed") continue;
            if (!idxEl.TryGetProperty("args", out var argsEl)) continue;

            var cols = new List<string>();
            if (argsEl.ValueKind == JsonValueKind.String)
            {
                var s = argsEl.GetString();
                if (!string.IsNullOrWhiteSpace(s)) cols.Add(s!);
            }
            else if (argsEl.ValueKind == JsonValueKind.Array)
            {
                foreach (var a in argsEl.EnumerateArray())
                {
                    var s = a.ValueKind == JsonValueKind.String ? a.GetString() : a.GetRawText();
                    if (!string.IsNullOrWhiteSpace(s)) cols.Add(s!);
                }
            }
            if (cols.Count == 0) continue;

            var isUnique = idxEl.TryGetProperty("unique", out var uniqueProp)
                           && uniqueProp.ValueKind == JsonValueKind.True;
            if (isUnique)
            {
                constraints.Add((
                    $"uq_{tableName}_{string.Join("_", cols)}",
                    $"UNIQUE ({string.Join(", ", cols)})"));
            }
            else
            {
                warnings.Add(
                    $"@index({string.Join(", ", cols)})는 방출하지 않음 — Schemorph PG P1은 인덱스를 거부한다 (P2 지원 시 재개)");
            }
        }
    }

    private static string AnsiCheckValues(EnumNode enumNode) =>
        string.Join(", ", enumNode.Values.Select(v => AnsiLiteral(v.Name ?? string.Empty)));

    private static string AnsiLiteral(string value) =>
        "'" + value.Replace("'", "''") + "'";

    private static bool Has(FieldNode field, string name) =>
        MddBooster.Core.Ast.FieldAttributes.Has(field, name);

    private static string? GetAttributeFirstParam(FieldNode field, string name) =>
        MddBooster.Core.Ast.FieldAttributes.FirstArg(field, name);

    private static IReadOnlyList<string>? ExtractStringParams(List<JsonElement>? paramsList) =>
        MddBooster.Core.Ast.FieldAttributes.StringArgs(paramsList);
}
