using System.Text;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Sql.Postgres;

/// <summary>
/// PG 방언 <c>{table}_ud_view</c>(UndeletedView) 렌더러 — T-SQL <see cref="UdViewRenderer"/>의
/// 등가물. 소프트 삭제(<c>deleted_at</c>)가 활성인 모델의 뷰 파생 체인(<c>Entity → UdView →
/// FullView → ExtView</c>) 첫 층. 식별자는 ADR-0001을 따라 전부 비인용 snake_case이고,
/// T-SQL의 <c>GO</c> 배치 구분자는 없다.
/// <para>
/// <see cref="BaseColumns"/>와 마찬가지로 <c>b.*</c> 대신 명시 컬럼 나열을 쓴다 — 이유는
/// <see cref="UdViewRenderer"/>의 같은 주석 참조(선언형 스키마 도구가 <c>SELECT *</c> 뷰의
/// 컬럼 추가를 놓치는 문제).
/// </para>
/// </summary>
public static class PgUdViewRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(ResolvedModel model, string schema, string tableName, string viewName)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);
        ArgumentException.ThrowIfNullOrWhiteSpace(tableName);
        ArgumentException.ThrowIfNullOrWhiteSpace(viewName);

        var columns = BaseColumns.StoredFields(model, excludeFieldInternal: true)
            .Select(f => f.Name);
        var projection = string.Join(", ", columns.Select(c => "b." + c));

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE VIEW ").Append(schema).Append('.').Append(viewName).AppendLine(" AS");
        sb.Append("SELECT ").AppendLine(projection);
        sb.Append("FROM ").Append(schema).Append('.').Append(tableName).AppendLine(" AS b");
        sb.AppendLine("WHERE b.deleted_at IS NULL;");
        return sb.ToString();
    }
}
