using System.Text;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders the OData entity set name list into <c>entity_names_gen.ts</c>.
/// </summary>
/// <remarks>
/// The generated <c>ENTITY_NAMES</c> const array mirrors the OData entity set
/// names (PascalCase plural) registered by the API generator. Consumers use
/// <c>EntitySetName</c> as a type-safe key for building OData URLs.
/// </remarks>
public static class TsEntityNamesRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>
    /// Renders all entity set names into a single <c>entity_names_gen.ts</c> file.
    /// </summary>
    public static string RenderAll(IReadOnlyList<ResolvedModel> models)
    {
        ArgumentNullException.ThrowIfNull(models);

        var names = models
            .Select(m => Pluralizer.Pluralize(TypeScriptTypeMapper.PascalCase(m.Name)))
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();
        sb.AppendLine("export const ENTITY_NAMES = [");
        foreach (var name in names)
        {
            sb.Append("  '").Append(name).AppendLine("',");
        }
        sb.AppendLine("] as const");
        sb.AppendLine();
        sb.AppendLine("export type EntitySetName = typeof ENTITY_NAMES[number]");
        sb.AppendLine();
        return sb.ToString();
    }
}
