using System.Text;
using M3L.Native;
using MddBooster.Core.Naming;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders M3L top-level enum declarations (<c>## Name ::enum</c>) into a
/// TypeScript file containing Union literal types.
/// </summary>
/// <remarks>
/// Each M3L enum becomes a TypeScript <c>export type</c> Union literal so that
/// consumers get full type safety and autocompletion without importing a
/// runtime enum object.
/// <example>
/// M3L:  <c>## OrderStatus ::enum  - draft: "초안"  - confirmed: "확정"</c>
/// TS:   <c>export type OrderStatus = 'draft' | 'confirmed'</c>
/// </example>
/// <para>
/// The literal values are the M3L member names as declared (e.g. <c>draft</c>,
/// <c>in_production</c>) — the same wire form the C# generator carries via
/// <c>[EnumMember(Value = "...")]</c> (see <c>EnumRenderer</c>), not the
/// PascalCase CLR member name. A server whose EDM/JSON layers honor
/// <c>[EnumMember]</c> serializes and deserializes enums using that form, so
/// this type must agree with it by construction rather than by coincidence.
/// </para>
/// </remarks>
public static class TsEnumRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>
    /// Renders all enums into a single <c>enums_gen.ts</c> file content.
    /// </summary>
    public static string RenderAll(IReadOnlyList<EnumNode> enums)
    {
        ArgumentNullException.ThrowIfNull(enums);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();

        foreach (var enumNode in enums)
        {
            var typeName = NameCasing.ToPascalCase(enumNode.Name);

            if (!string.IsNullOrWhiteSpace(enumNode.Description))
            {
                sb.Append("/** ").Append(enumNode.Description.Replace("*/", "* /")).AppendLine(" */");
            }

            sb.Append("export type ").Append(typeName).Append(" =");

            if (enumNode.Values.Count == 0)
            {
                sb.AppendLine(" never");
            }
            else
            {
                for (var i = 0; i < enumNode.Values.Count; i++)
                {
                    var v = enumNode.Values[i];
                    sb.AppendLine();
                    sb.Append("  ");
                    if (i > 0) sb.Append("| ");
                    else sb.Append("  ");
                    // Wire form, matching [EnumMember(Value = "...")] on the C# side (EnumRenderer):
                    // m3l "supplier" → C# [EnumMember(Value = "supplier")] EnumType.Supplier → JSON "supplier"
                    sb.Append("'").Append(EscapeString(v.Name ?? string.Empty)).Append("'");
                }
                sb.AppendLine();
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("'", "\\'");
}
