using System.Text;
using M3L.Native;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders M3L enum declarations into an <c>enum_labels_gen.ts</c> file that maps
/// each enum value (PascalCase) to its Korean label (the M3L description string).
/// </summary>
/// <remarks>
/// <example>
/// M3L:  <c>## OrderStatus ::enum  - draft: "작성중"</c>
/// TS:   <c>export const OrderStatusLabels: Record&lt;OrderStatus, string&gt; = { Draft: '작성중' } as const</c>
/// </example>
/// </remarks>
public static class TsEnumLabelsRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>
    /// Renders all enums into a single <c>enum_labels_gen.ts</c> file content.
    /// Every enum value gets a label entry — the M3L description if present, otherwise the PascalCase key.
    /// </summary>
    public static string RenderAll(IReadOnlyList<EnumNode> enums)
    {
        ArgumentNullException.ThrowIfNull(enums);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();

        // Import all enum types from enums_gen
        var enumTypeNames = enums
            .Select(e => TypeScriptTypeMapper.PascalCase(e.Name))
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        if (enumTypeNames.Count > 0)
        {
            sb.Append("import type { ")
              .Append(string.Join(", ", enumTypeNames))
              .AppendLine(" } from './enums_gen'");
            sb.AppendLine();
        }

        foreach (var enumNode in enums)
        {
            var typeName = TypeScriptTypeMapper.PascalCase(enumNode.Name);

            if (!string.IsNullOrWhiteSpace(enumNode.Description))
            {
                sb.Append("/** ").Append(enumNode.Description.Replace("*/", "* /")).AppendLine(" */");
            }

            sb.Append("export const ").Append(typeName).Append("Labels: Record<")
              .Append(typeName).AppendLine(", string> = {");

            foreach (var v in enumNode.Values)
            {
                var key = TypeScriptTypeMapper.PascalCase(v.Name ?? string.Empty);
                var label = !string.IsNullOrWhiteSpace(v.Description)
                    ? v.Description
                    : key;
                // Escape single quotes inside label
                var escaped = label.Replace("\\", "\\\\").Replace("'", "\\'");
                sb.Append("  ").Append(key).Append(": '").Append(escaped).AppendLine("',");
            }

            sb.AppendLine("} as const");
            sb.AppendLine();

            AppendSelectableLabels(sb, enumNode, typeName);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits the input-choice map for enums carrying <c>@system</c> values.
    /// </summary>
    /// <remarks>
    /// Display labels and input choices are different concerns that used to share
    /// one source, which is why generated forms offered values only the system may
    /// write. The label map above stays complete (existing rows must still render);
    /// this narrower map is what a form offers.
    /// <para>
    /// Typed as <c>Record&lt;Exclude&lt;T, 'Excluded'&gt;, string&gt;</c> so the exclusion is
    /// checked by the compiler and the map still satisfies a <c>Record&lt;string, string&gt;</c>
    /// parameter — no change is required of the consumer's <c>enumToOptions</c> helper.
    /// </para>
    /// </remarks>
    private static void AppendSelectableLabels(StringBuilder sb, EnumNode enumNode, string typeName)
    {
        if (!EnumValueVisibility.HasSystemValues(enumNode)) return;

        var excluded = enumNode.Values
            .Where(EnumValueVisibility.IsSystemValue)
            .Select(v => "'" + TypeScriptTypeMapper.PascalCase(v.Name ?? string.Empty) + "'")
            .ToList();

        sb.AppendLine("/** Input choices — excludes values marked @system in the model. */");
        sb.Append("export const ").Append(EnumValueVisibility.SelectableLabelsName(typeName))
          .Append(": Record<Exclude<").Append(typeName).Append(", ")
          .Append(string.Join(" | ", excluded)).AppendLine(">, string> = {");

        foreach (var v in enumNode.Values.Where(v => !EnumValueVisibility.IsSystemValue(v)))
        {
            var key = TypeScriptTypeMapper.PascalCase(v.Name ?? string.Empty);
            var label = !string.IsNullOrWhiteSpace(v.Description) ? v.Description : key;
            var escaped = label.Replace("\\", "\\\\").Replace("'", "\\'");
            sb.Append("  ").Append(key).Append(": '").Append(escaped).AppendLine("',");
        }

        sb.AppendLine("} as const");
        sb.AppendLine();
    }
}
