using System.Text;
using M3L.Native;
using MddBooster.Core.Naming;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders M3L enum declarations into an <c>enum_labels_gen.ts</c> file that maps
/// each enum value (PascalCase) to its Korean label (the M3L description string).
/// </summary>
/// <remarks>
/// <example>
/// M3L:  <c>## OrderStatus ::enum  - draft: "작성중"</c>
/// TS:   <c>export const OrderStatusLabels: Record&lt;OrderStatus, string&gt; = { draft: '작성중' } as const</c>
/// </example>
/// <para>
/// Keys are the M3L member names as declared (the same wire form
/// <c>TsEnumRenderer</c> uses for the <c>OrderStatus</c> union members), not
/// PascalCase — the map must index by the same values the type it is
/// <c>Record&lt;&gt;</c>-keyed on actually holds.
/// </para>
/// </remarks>
public static class TsEnumLabelsRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>
    /// Renders all enums into a single <c>enum_labels_gen.ts</c> file content.
    /// Every enum value gets a label entry — the M3L description if present, otherwise the PascalCase key.
    /// </summary>
    public static string RenderAll(IReadOnlyList<EnumNode> enums)
    {
        ArgumentNullException.ThrowIfNull(enums);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();

        // Import all enum types from enums_gen
        var enumTypeNames = enums
            .Select(e => NameCasing.ToPascalCase(e.Name))
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        if (enumTypeNames.Count > 0)
        {
            sb.Append("import type { ")
              .Append(string.Join(", ", enumTypeNames))
              .AppendLine(" } from './enums_gen'");
            sb.AppendLine();
        }

        foreach (var enumNode in enums)
        {
            var typeName = NameCasing.ToPascalCase(enumNode.Name);

            if (!string.IsNullOrWhiteSpace(enumNode.Description))
            {
                sb.Append("/** ").Append(enumNode.Description.Replace("*/", "* /")).AppendLine(" */");
            }

            sb.Append("export const ").Append(typeName).Append("Labels: Record<")
              .Append(typeName).AppendLine(", string> = {");

            foreach (var v in enumNode.Values)
            {
                var key = v.Name ?? string.Empty;
                var label = !string.IsNullOrWhiteSpace(v.Description)
                    ? v.Description
                    : NameCasing.ToPascalCase(key);
                // Escape single quotes inside label
                var escaped = label.Replace("\\", "\\\\").Replace("'", "\\'");
                sb.Append("  ").Append(key).Append(": '").Append(escaped).AppendLine("',");
            }

            sb.AppendLine("} as const");
            sb.AppendLine();

            AppendSelectableLabels(sb, enumNode, typeName);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits the input-choice map for enums carrying values excluded from authoring.
    /// </summary>
    /// <remarks>
    /// Display labels and input choices are different concerns that used to share
    /// one source, which is why generated forms offered values only the system may
    /// write. The label map above stays complete (existing rows must still render);
    /// this narrower map is what a form offers.
    /// <para>
    /// Typed as <c>Record&lt;Exclude&lt;T, 'Excluded'&gt;, string&gt;</c> so the exclusion is
    /// checked by the compiler and the map still satisfies a <c>Record&lt;string, string&gt;</c>
    /// parameter — no change is required of the consumer's <c>enumToOptions</c> helper.
    /// </para>
    /// </remarks>
    private static void AppendSelectableLabels(StringBuilder sb, EnumNode enumNode, string typeName)
    {
        if (!EnumValueVisibility.HasExcludedValues(enumNode)) return;

        var excluded = enumNode.Values
            .Where(EnumValueVisibility.IsExcludedFromChoices)
            .Select(v => "'" + (v.Name ?? string.Empty) + "'")
            .ToList();

        sb.AppendLine("/** Input choices — excludes values marked @system or @deprecated in the model. */");
        sb.Append("export const ").Append(EnumValueVisibility.SelectableLabelsName(typeName))
          .Append(": Record<Exclude<").Append(typeName).Append(", ")
          .Append(string.Join(" | ", excluded)).AppendLine(">, string> = {");

        foreach (var v in enumNode.Values.Where(v => !EnumValueVisibility.IsExcludedFromChoices(v)))
        {
            var key = v.Name ?? string.Empty;
            var label = !string.IsNullOrWhiteSpace(v.Description) ? v.Description : NameCasing.ToPascalCase(key);
            var escaped = label.Replace("\\", "\\\\").Replace("'", "\\'");
            sb.Append("  ").Append(key).Append(": '").Append(escaped).AppendLine("',");
        }

        sb.AppendLine("} as const");
        sb.AppendLine();

        AppendChoicesFunction(sb, typeName);
    }

    /// <summary>
    /// Emits the function a generated form calls for its choices.
    /// </summary>
    /// <remarks>
    /// The narrowed map above answers "what may be authored". A form also has to
    /// answer "what is this row showing", and for a row holding an excluded value
    /// those two differ — the map has no entry for it, so the control receives a
    /// value absent from its own options. This restores that single value while it
    /// is the current one, leaving every other row with the narrowed choices.
    /// <para>
    /// The parameter is <c>string</c>, not the enum type, on purpose:
    /// <c>@display_labels(X)</c> keys the map by <em>X</em> while the form's value is
    /// still typed as the field's own enum, so typing the parameter as either one
    /// makes the other combination stop compiling. The compile-time guarantee is
    /// unaffected — it lives on the map's <c>Exclude&lt;&gt;</c> declaration, which
    /// this only reads.
    /// </para>
    /// </remarks>
    private static void AppendChoicesFunction(StringBuilder sb, string typeName)
    {
        var selectable = EnumValueVisibility.SelectableLabelsName(typeName);
        var labels = typeName + "Labels";

        sb.AppendLine("/** Input choices, plus the current value when the model excludes it (so editing an existing row keeps it). */");
        sb.Append("export function ").Append(EnumValueVisibility.ChoicesFunctionName(typeName))
          .AppendLine("(current?: string | null): Record<string, string> {");
        sb.Append("  if (!current || current in ").Append(selectable)
          .Append(") return ").Append(selectable).AppendLine();
        sb.Append("  const label = (").Append(labels)
          .AppendLine(" as Record<string, string>)[current]");
        sb.Append("  return label === undefined ? ").Append(selectable)
          .Append(" : { ...").Append(selectable).AppendLine(", [current]: label }");
        sb.AppendLine("}");
        sb.AppendLine();
    }
}
