using System.Text;
using M3L.Native;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders M3L top-level enum declarations (<c>## Name ::enum</c>) into a
/// TypeScript file containing Union literal types.
/// </summary>
/// <remarks>
/// Each M3L enum becomes a TypeScript <c>export type</c> Union literal so that
/// consumers get full type safety and autocompletion without importing a
/// runtime enum object.
/// <example>
/// M3L:  <c>## OrderStatus ::enum  - draft: "초안"  - confirmed: "확정"</c>
/// TS:   <c>export type OrderStatus = 'draft' | 'confirmed'</c>
/// </example>
/// </remarks>
public static class TsEnumRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>
    /// Renders all enums into a single <c>enums_gen.ts</c> file content.
    /// </summary>
    public static string RenderAll(IReadOnlyList<EnumNode> enums)
    {
        ArgumentNullException.ThrowIfNull(enums);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();

        foreach (var enumNode in enums)
        {
            var typeName = TypeScriptTypeMapper.PascalCase(enumNode.Name);

            if (!string.IsNullOrWhiteSpace(enumNode.Description))
            {
                sb.Append("/** ").Append(enumNode.Description.Replace("*/", "* /")).AppendLine(" */");
            }

            sb.Append("export type ").Append(typeName).Append(" =");

            if (enumNode.Values.Count == 0)
            {
                sb.AppendLine(" never");
            }
            else
            {
                for (var i = 0; i < enumNode.Values.Count; i++)
                {
                    var v = enumNode.Values[i];
                    sb.AppendLine();
                    sb.Append("  ");
                    if (i > 0) sb.Append("| ");
                    else sb.Append("  ");
                    // API serializes enum members as PascalCase C# member names (not snake_case DB values).
                    // m3l "supplier" → C# EnumType.Supplier → JSON "Supplier"
                    sb.Append("'").Append(TypeScriptTypeMapper.PascalCase(v.Name ?? string.Empty)).Append("'");
                }
                sb.AppendLine();
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }
}
