using System.Text;
using System.Text.Json;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders stored-field constraints from M3L models into a <c>field_schema_gen.ts</c> file.
/// Constraints are derived from M3L attributes: non-nullable (required), string length params (maxLength),
/// <c>@min</c>/<c>@max</c> (min/max).
/// </summary>
/// <remarks>
/// Only stored fields with at least one constraint emit an entry.
/// Fields with no constraints are omitted to keep the schema lean.
/// </remarks>
public static class TsFieldSchemaRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string RenderAll(IReadOnlyList<ResolvedModel> models)
    {
        ArgumentNullException.ThrowIfNull(models);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();
        sb.AppendLine("export type FieldConstraints = {");
        sb.AppendLine("  required?: true");
        sb.AppendLine("  maxLength?: number");
        sb.AppendLine("  min?: number");
        sb.AppendLine("  max?: number");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("export const FieldSchema = {");

        foreach (var model in models)
        {
            var entityName = TypeScriptTypeMapper.PascalCase(model.Name);
            var storedFields = model.Fields
                .Where(f => f.Kind == FieldKind.Stored)
                .Where(f => !HasAttribute(f, "pk"))
                .Where(f => !IsInheritedTimestamp(f.Name))
                .ToList();

            var constrainedFields = storedFields
                .Select(f => (Field: f, Constraints: ExtractConstraints(f)))
                .Where(pair => pair.Constraints.HasAny)
                .ToList();

            if (constrainedFields.Count == 0) continue;

            sb.Append("  ").Append(entityName).AppendLine(": {");

            foreach (var (field, constraints) in constrainedFields)
            {
                var prop = TypeScriptTypeMapper.PascalCase(field.Name);
                sb.Append("    ").Append(prop).Append(": {");

                var parts = new List<string>();
                if (constraints.Required)           parts.Add("required: true");
                if (constraints.MaxLength.HasValue) parts.Add($"maxLength: {constraints.MaxLength.Value}");
                if (constraints.Min.HasValue)       parts.Add($"min: {constraints.Min.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)}");
                if (constraints.Max.HasValue)       parts.Add($"max: {constraints.Max.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)}");

                sb.Append(' ').Append(string.Join(", ", parts)).AppendLine(" },");
            }

            sb.AppendLine("  },");
        }

        sb.AppendLine("} as const satisfies Record<string, Record<string, FieldConstraints>>");
        sb.AppendLine();

        return sb.ToString();
    }

    private static FieldConstraints ExtractConstraints(FieldNode field)
    {
        var required = !field.Nullable;

        // maxLength: from string(N) params
        // NOTE: M3L.Native serializes integer params as doubles (e.g. "30" → 30.0)
        int? maxLength = null;
        if (field.Type is not null && field.Type.StartsWith("string", StringComparison.OrdinalIgnoreCase)
            && field.Params is { Count: > 0 })
        {
            if (field.Params[0].ValueKind == JsonValueKind.Number
                && field.Params[0].TryGetDouble(out var lenD)
                && lenD == Math.Floor(lenD))
            {
                maxLength = (int)lenD;
            }
        }

        // min / max: from @min(N) @max(N) attributes
        double? min = GetAttributeNumber(field, "min");
        double? max = GetAttributeNumber(field, "max");

        return new FieldConstraints(required, maxLength, min, max);
    }

    private static double? GetAttributeNumber(FieldNode field, string attrName)
    {
        var attr = field.Attributes.FirstOrDefault(a =>
            string.Equals(a.Name, attrName, StringComparison.OrdinalIgnoreCase));
        if (attr?.Args is { Count: > 0 }
            && attr.Args[0].ValueKind == JsonValueKind.Number
            && attr.Args[0].TryGetDouble(out var value))
        {
            return value;
        }
        return null;
    }

    private static bool HasAttribute(FieldNode field, string name) =>
        field.Attributes.Any(a => string.Equals(a.Name, name, StringComparison.OrdinalIgnoreCase));

    private static bool IsInheritedTimestamp(string fieldName) =>
        string.Equals(fieldName, "created_at", StringComparison.OrdinalIgnoreCase)
        || string.Equals(fieldName, "updated_at", StringComparison.OrdinalIgnoreCase);

    private record FieldConstraints(bool Required, int? MaxLength, double? Min, double? Max)
    {
        public bool HasAny => Required || MaxLength.HasValue || Min.HasValue || Max.HasValue;
    }
}
