using System.Text;
using System.Text.Json;
using M3L.Native;
using MddBooster.Core.Semantic;
using MddBooster.Core.Naming;

namespace MddBooster.Generators.TypeScript;

public static class TsFieldSchemaRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string RenderAll(IReadOnlyList<ResolvedModel> models)
    {
        ArgumentNullException.ThrowIfNull(models);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();
        sb.AppendLine("export type FieldConstraints = {");
        sb.AppendLine("  required?: true");
        sb.AppendLine("  maxLength?: number");
        sb.AppendLine("  min?: number");
        sb.AppendLine("  max?: number");
        sb.AppendLine("  label?: string");
        sb.AppendLine("  group?: string");
        sb.AppendLine("  derived?: 'lookup' | 'rollup' | 'computed'");
        sb.AppendLine("  readOnly?: true");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("export const FieldSchema = {");

        foreach (var model in models)
        {
            var entityName = NameCasing.ToPascalCase(model.Name);
            // Stored and derived fields are both in scope, but they earn their place on
            // different terms. A stored field is here for its *constraints*, so one with none
            // says nothing and is dropped (HasAny). A derived field is here for its *kind* —
            // `derived`/`readOnly` is itself what the consumer needs to know — so it is never
            // dropped for lacking a label. Declaration order is preserved by filtering the
            // model's own field list once rather than concatenating two passes.
            var schemaFields = model.Fields
                .Where(f => f.Kind is FieldKind.Stored or FieldKind.Lookup or FieldKind.Rollup or FieldKind.Computed)
                .Where(f => !HasAttribute(f, "pk"))
                .Where(f => !IsInheritedTimestamp(f.Name))
                .ToList();

            var constrainedFields = schemaFields
                .Select(f => (Field: f, Constraints: ExtractConstraints(f, model, models)))
                .Where(pair => pair.Constraints.IsDerived || pair.Constraints.HasAny)
                .ToList();

            if (constrainedFields.Count == 0) continue;

            sb.Append("  ").Append(entityName).AppendLine(": {");

            foreach (var (field, constraints) in constrainedFields)
            {
                var prop = NameCasing.ToPascalCase(field.Name);
                sb.Append("    ").Append(prop).Append(": {");

                var parts = new List<string>();
                if (constraints.Required)            parts.Add("required: true");
                if (constraints.MaxLength.HasValue)  parts.Add($"maxLength: {constraints.MaxLength.Value}");
                if (constraints.Min.HasValue)        parts.Add($"min: {constraints.Min.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)}");
                if (constraints.Max.HasValue)        parts.Add($"max: {constraints.Max.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)}");
                if (constraints.Label != null)
                {
                    var escapedLabel = constraints.Label.Replace("\\", "\\\\").Replace("'", "\\'");
                    parts.Add($"label: '{escapedLabel}'");
                }
                if (constraints.Group != null)
                {
                    var escapedGroup = constraints.Group.Replace("\\", "\\\\").Replace("'", "\\'");
                    parts.Add($"group: '{escapedGroup}'");
                }
                if (constraints.Derived != null)
                {
                    parts.Add($"derived: '{constraints.Derived}'");
                    parts.Add("readOnly: true");
                }

                sb.Append(' ').Append(string.Join(", ", parts)).AppendLine(" },");
            }

            sb.AppendLine("  },");
        }

        sb.AppendLine("} as const satisfies Record<string, Record<string, FieldConstraints>>");
        sb.AppendLine();

        return sb.ToString();
    }

    private static FieldConstraints ExtractConstraints(
        FieldNode field,
        ResolvedModel owner,
        IReadOnlyList<ResolvedModel> allModels)
    {
        var derived = field.Kind switch
        {
            FieldKind.Lookup => "lookup",
            FieldKind.Rollup => "rollup",
            FieldKind.Computed => "computed",
            _ => null,
        };

        // `required` is a write-axis statement — "the user must supply this". A derived field is
        // never supplied, so carrying its resolved nullability across would assert something
        // false: `customer_name @lookup(customer_id.name)` reads a NOT NULL column and therefore
        // resolves non-nullable, but nothing about that obliges a *form* to collect it.
        var required = derived is null && !field.Nullable;

        // Shared with the generated form's `maxlength` — see FieldAttributes.EffectiveMaxLength.
        // Extracting it separately here is how the two would drift into disagreeing about the
        // same column's limit. The effective bound, not the declared one: a field can be
        // bounded by its type without the declaration saying so.
        int? maxLength = MddBooster.Core.Ast.FieldAttributes.EffectiveMaxLength(field);

        double? min = GetAttributeNumber(field, "min");
        double? max = GetAttributeNumber(field, "max");
        // @label(text) overrides the description; unlike FieldAttributes.EffectiveLabel this
        // does NOT fall back to the PascalCase field name — presence of a label here signals
        // authored, meaningful text, and every field mechanically has a PascalCase name.
        string? label = MddBooster.Core.Ast.FieldAttributes.FirstArg(field, "label") ?? field.Description;

        // A lookup with no label of its own borrows the one on the field it reads: the target
        // already names this value, and making the author repeat that string is how the two drift.
        // Only lookups can do this — a rollup is an aggregate (`count`, `sum(x)`) and a computed is
        // an expression, so neither has a single target *field* whose name would apply.
        // An explicit label always wins; if the target has none either, nothing is invented — the
        // PascalCase fallback is deliberately not used here (see the comment above).
        if (label is null && derived == "lookup")
        {
            var target = LookupTarget.Resolve(owner, field, allModels);
            if (target is not null)
                label = MddBooster.Core.Ast.FieldAttributes.FirstArg(target, "label") ?? target.Description;
        }
        string? group = GetAttributeString(field, "group");

        return new FieldConstraints(required, maxLength, min, max, label, group, derived);
    }

    private static double? GetAttributeNumber(FieldNode field, string attrName)
    {
        var attr = MddBooster.Core.Ast.FieldAttributes.Find(field, attrName);
        if (attr?.Args is { Count: > 0 }
            && attr.Args[0].ValueKind == JsonValueKind.Number
            && attr.Args[0].TryGetDouble(out var value))
        {
            return value;
        }
        return null;
    }

    private static string? GetAttributeString(FieldNode field, string attrName)
    {
        var attr = MddBooster.Core.Ast.FieldAttributes.Find(field, attrName);
        if (attr?.Args is { Count: > 0 }
            && attr.Args[0].ValueKind == JsonValueKind.String)
        {
            return attr.Args[0].GetString();
        }
        return null;
    }

    private static bool HasAttribute(FieldNode field, string name) =>
        MddBooster.Core.Ast.FieldAttributes.Has(field, name);

    private static bool IsInheritedTimestamp(string fieldName) =>
        string.Equals(fieldName, "created_at", StringComparison.OrdinalIgnoreCase)
        || string.Equals(fieldName, "updated_at", StringComparison.OrdinalIgnoreCase);

    private record FieldConstraints(
        bool Required, int? MaxLength, double? Min, double? Max,
        string? Label, string? Group, string? Derived)
    {
        /// <summary>
        /// True when the field has at least one constraint or metadata (required, maxLength, min, max, label, group).
        /// A nullable field with only label or group still qualifies for schema inclusion.
        /// </summary>
        public bool HasAny => Required || MaxLength.HasValue || Min.HasValue || Max.HasValue || Label != null || Group != null;

        /// <summary>
        /// Derived fields (lookup/rollup/computed) are included on their kind alone — see the
        /// selection comment in <see cref="RenderAll"/>. <see cref="HasAny"/> deliberately does
        /// not fold this in: it answers "does this field carry constraints?", which stays the
        /// right question for stored fields and would silently change meaning if widened.
        /// </summary>
        public bool IsDerived => Derived != null;
    }
}
