using System.Text;
using System.Text.Json;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders per-entity React form base components ({Entity}Form_gen.tsx).
/// Generated forms use FormSection/FormRow from @iyulab/enterprise.
/// FK fields (@reference) become slot placeholders.
/// </summary>
public static class TsFormRenderer
{
    // Match the convention used by all other TS renderers in this project.
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>Returns a dictionary of entityName → tsx content.</summary>
    public static IReadOnlyDictionary<string, string> RenderAll(
        IReadOnlyList<ResolvedModel> models,
        IReadOnlySet<string> enumNames)
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentNullException.ThrowIfNull(enumNames);

        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var model in models)
        {
            var content = RenderOne(model, enumNames);
            if (content != null)
                result[TypeScriptTypeMapper.PascalCase(model.Name)] = content;
        }
        return result;
    }

    private static string? RenderOne(ResolvedModel model, IReadOnlySet<string> enumNames)
    {
        var storedFields = model.Fields
            .Where(f => f.Kind == FieldKind.Stored)
            .Where(f => !HasAttribute(f, "pk"))
            .Where(f => !IsInheritedTimestamp(f.Name))
            .ToList();

        if (storedFields.Count == 0) return null;

        var entityName = TypeScriptTypeMapper.PascalCase(model.Name);

        // Group fields by @group attribute (preserve insertion order).
        // "기타" is the default fallback — note explicit @group("기타") merges into the same bucket.
        var sections = new Dictionary<string, List<FieldNode>>(StringComparer.Ordinal);
        foreach (var field in storedFields)
        {
            var group = GetAttributeString(field, "group") ?? "기타";
            if (!sections.ContainsKey(group))
                sections[group] = [];
            sections[group].Add(field);
        }

        // Collect FK fields (for slots type).
        var fkFields = storedFields
            .Where(f => HasAttribute(f, "reference"))
            .Select(f => TypeScriptTypeMapper.PascalCase(f.Name))
            .ToList();

        // Collect enum imports needed.
        var enumImports = storedFields
            .Where(f => f.Type != null && enumNames.Contains(f.Type))
            .Select(f => f.Type!)
            .Distinct()
            .Select(TypeScriptTypeMapper.PascalCase)
            .OrderBy(e => e)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("import type { ReactNode } from 'react'");
        sb.AppendLine("import { FormSection, FormRow } from '@iyulab/enterprise'");

        var hasBooleans = storedFields.Any(f =>
            string.Equals(f.Type, "boolean", StringComparison.OrdinalIgnoreCase));
        var uiImports = new List<string> { "UInput", "USelect" };
        if (hasBooleans) uiImports.Add("UCheckbox");
        sb.Append("import { ").Append(string.Join(", ", uiImports)).AppendLine(" } from '../components/ui'");
        sb.Append("import type { ").Append(entityName).AppendLine(" } from '../types/entities_gen'");

        if (enumImports.Count > 0)
        {
            var labelImports = string.Join(", ", enumImports.Select(e => $"{e}Labels"));
            sb.Append("import { ").Append(labelImports).AppendLine(" } from '../lib/enum_labels_gen'");
            sb.AppendLine("import { enumToOptions } from '../lib/select-options'");
        }

        sb.AppendLine();

        // Slots type (only when FK fields exist).
        if (fkFields.Count > 0)
        {
            sb.Append("export type ").Append(entityName).AppendLine("FormSlots = {");
            foreach (var fk in fkFields)
                sb.Append("  ").Append(fk).AppendLine("?: ReactNode");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // FormBase function.
        sb.Append("export function ").Append(entityName).AppendLine("FormBase({");
        sb.AppendLine("  form,");
        sb.AppendLine("  onChange,");
        if (fkFields.Count > 0) sb.AppendLine("  slots,");
        sb.AppendLine("}: {");
        sb.Append("  form: Partial<").Append(entityName).AppendLine(">");
        sb.Append("  onChange: (updates: Partial<").Append(entityName).AppendLine(">) => void");
        if (fkFields.Count > 0) sb.Append("  slots?: ").Append(entityName).AppendLine("FormSlots");
        sb.AppendLine("}) {");
        sb.AppendLine("  return (");
        sb.AppendLine("    <>");

        foreach (var (sectionTitle, fields) in sections)
        {
            sb.Append("      <FormSection title=\"").Append(sectionTitle).AppendLine("\">");
            RenderSectionRows(sb, fields, enumNames);
            sb.AppendLine("      </FormSection>");
        }

        sb.AppendLine("    </>");
        sb.AppendLine("  )");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void RenderSectionRows(
        StringBuilder sb,
        List<FieldNode> fields,
        IReadOnlySet<string> enumNames)
    {
        var i = 0;
        while (i < fields.Count)
        {
            var field = fields[i];
            var isFullWidth = IsFullWidth(field);

            if (isFullWidth)
            {
                sb.AppendLine("        <FormRow full>");
                sb.Append("          ").AppendLine(RenderField(field, enumNames));
                sb.AppendLine("        </FormRow>");
                i++;
            }
            else if (i + 1 < fields.Count && !IsFullWidth(fields[i + 1]))
            {
                sb.AppendLine("        <FormRow>");
                sb.Append("          ").AppendLine(RenderField(field, enumNames));
                sb.Append("          ").AppendLine(RenderField(fields[i + 1], enumNames));
                sb.AppendLine("        </FormRow>");
                i += 2;
            }
            else
            {
                // unpaired half-width field
                sb.AppendLine("        <FormRow full>");
                sb.Append("          ").AppendLine(RenderField(field, enumNames));
                sb.AppendLine("        </FormRow>");
                i++;
            }
        }
    }

    private static bool IsFullWidth(FieldNode field)
    {
        if (HasAttribute(field, "reference")) return true;
        if (string.Equals(field.Type, "text", StringComparison.OrdinalIgnoreCase)) return true;
        return false;
    }

    private static string RenderField(FieldNode field, IReadOnlySet<string> enumNames)
    {
        var prop = TypeScriptTypeMapper.PascalCase(field.Name);
        var label = field.Description ?? prop;
        var required = !field.Nullable;
        var requiredAttr = required ? " required" : "";

        // FK → slot
        if (HasAttribute(field, "reference"))
            return $"{{slots?.{prop} ?? <span className=\"text-gray-400 text-xs\">{label} slot</span>}}";

        // boolean → UCheckbox
        if (string.Equals(field.Type, "boolean", StringComparison.OrdinalIgnoreCase))
            return $"<UCheckbox label=\"{label}\" checked={{form.{prop} ?? false}} onChange={{v => onChange({{ {prop}: v }})}} />";

        // enum → USelect
        if (field.Type != null && enumNames.Contains(field.Type))
        {
            var enumTypeName = TypeScriptTypeMapper.PascalCase(field.Type);
            var defaultVal = field.Nullable ? "null" : "''";
            var placeholder = field.Nullable ? $" placeholder=\"{label} 선택\"" : "";
            return $"<USelect label=\"{label}\"{requiredAttr}{placeholder} value={{form.{prop} ?? {defaultVal}}} options={{enumToOptions({enumTypeName}Labels)}} onChange={{v => onChange({{ {prop}: v as {enumTypeName}{(field.Nullable ? " | null" : "")} }})}} />";
        }

        // date → UInput type="date"
        if (string.Equals(field.Type, "date", StringComparison.OrdinalIgnoreCase))
            return $"<UInput label=\"{label}\"{requiredAttr} type=\"date\" value={{form.{prop} ?? ''}} onChange={{v => onChange({{ {prop}: v || null }})}} />";

        // text → UInput (full-width handled by IsFullWidth)
        if (string.Equals(field.Type, "text", StringComparison.OrdinalIgnoreCase))
            return $"<UInput label=\"{label}\" value={{form.{prop} ?? ''}} onChange={{v => onChange({{ {prop}: v || null }})}} />";

        // number types
        if (field.Type != null && (field.Type.StartsWith("integer", StringComparison.OrdinalIgnoreCase)
            || field.Type.StartsWith("decimal", StringComparison.OrdinalIgnoreCase)))
            return $"<UInput label=\"{label}\"{requiredAttr} type=\"number\" value={{form.{prop} != null ? String(form.{prop}) : ''}} onChange={{v => onChange({{ {prop}: v ? Number(v) : null }})}} />";

        // string (default)
        return $"<UInput label=\"{label}\"{requiredAttr} value={{form.{prop} ?? ''}} onChange={{v => onChange({{ {prop}: v }})}} />";
    }

    private static string? GetAttributeString(FieldNode field, string attrName)
    {
        var attr = field.Attributes.FirstOrDefault(a =>
            string.Equals(a.Name, attrName, StringComparison.OrdinalIgnoreCase));
        if (attr?.Args is { Count: > 0 }
            && attr.Args[0].ValueKind == JsonValueKind.String)
        {
            return attr.Args[0].GetString();
        }
        return null;
    }

    private static bool HasAttribute(FieldNode field, string name) =>
        field.Attributes.Any(a => string.Equals(a.Name, name, StringComparison.OrdinalIgnoreCase));

    private static bool IsInheritedTimestamp(string fieldName) =>
        string.Equals(fieldName, "created_at", StringComparison.OrdinalIgnoreCase)
        || string.Equals(fieldName, "updated_at", StringComparison.OrdinalIgnoreCase);
}
