using System.Text;
using System.Text.Json;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders per-entity React form base components ({Entity}Form_gen.tsx).
/// Generated forms use FormSection/FormRow from @iyulab/enterprise.
/// FK fields (@reference) become slot placeholders.
/// </summary>
public static class TsFormRenderer
{
    // Match the convention used by all other TS renderers in this project.
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>Returns a dictionary of entityName → tsx content.</summary>
    public static IReadOnlyDictionary<string, string> RenderAll(
        IReadOnlyList<ResolvedModel> models,
        IReadOnlySet<string> enumNames)
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentNullException.ThrowIfNull(enumNames);

        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var model in models)
        {
            var content = RenderOne(model, enumNames);
            if (content != null)
                result[TypeScriptTypeMapper.PascalCase(model.Name)] = content;
        }
        return result;
    }

    private static string? RenderOne(ResolvedModel model, IReadOnlySet<string> enumNames)
    {
        var storedFields = model.Fields
            .Where(f => f.Kind == FieldKind.Stored)
            .Where(f => !HasAttribute(f, "pk"))
            .Where(f => !IsInheritedTimestamp(f.Name))
            .ToList();

        if (storedFields.Count == 0) return null;

        var entityName = TypeScriptTypeMapper.PascalCase(model.Name);

        // Group fields by @group attribute (preserve insertion order).
        // "기타" is the default fallback — note explicit @group("기타") merges into the same bucket.
        var sections = new Dictionary<string, List<FieldNode>>(StringComparer.Ordinal);
        foreach (var field in storedFields)
        {
            var group = GetAttributeString(field, "group") ?? "기타";
            if (!sections.ContainsKey(group))
                sections[group] = [];
            sections[group].Add(field);
        }

        // Collect slot fields: @reference FK fields AND @slot-annotated non-FK fields.
        // @slot allows non-FK fields (e.g. a field with a custom auto-generate button) to be
        // rendered as slot placeholders rather than as inline form controls.
        var slotFields = storedFields
            .Where(f => HasAttribute(f, "reference") || HasAttribute(f, "slot"))
            .Select(f => TypeScriptTypeMapper.PascalCase(f.Name))
            .ToList();
        // Keep fkFields as alias for backwards-compat with downstream code.
        var fkFields = slotFields;

        // Collect enum imports needed — only from renderable (non-slot, non-reference) fields,
        // since slot fields render their enum types via the caller's slot content, not here.
        var enumImports = storedFields
            .Where(f => f.Type != null && enumNames.Contains(f.Type))
            .Where(f => !HasAttribute(f, "reference") && !HasAttribute(f, "slot"))
            .Select(f => f.Type!)
            .Distinct()
            .Select(TypeScriptTypeMapper.PascalCase)
            .OrderBy(e => e)
            .ToList();

        // Non-slot renderable fields — these determine which UI component imports are needed.
        var renderableFields = storedFields
            .Where(f => !HasAttribute(f, "reference") && !HasAttribute(f, "slot"))
            .ToList();
        var allFieldsAreSlots = renderableFields.Count == 0;

        var sb = new StringBuilder();
        sb.AppendLine(Header);

        // ReactNode is only used for FK slot types — only import when needed.
        if (fkFields.Count > 0)
            sb.AppendLine("import type { ReactNode } from 'react'");

        sb.AppendLine("import { FormSection, FormRow } from '@iyulab/enterprise'");

        var hasBooleans = renderableFields.Any(f =>
            string.Equals(f.Type, "boolean", StringComparison.OrdinalIgnoreCase));
        var hasEnums = enumImports.Count > 0;
        // UInput is only needed when there are renderable non-enum, non-boolean, non-FK fields.
        var hasUInput = renderableFields.Any(f =>
            !string.Equals(f.Type, "boolean", StringComparison.OrdinalIgnoreCase)
            && (f.Type == null || !enumImports.Any(e =>
                string.Equals(TypeScriptTypeMapper.PascalCase(f.Type!), e, StringComparison.Ordinal))));
        var uiImports = new List<string>();
        if (hasUInput) uiImports.Add("UInput");
        if (hasEnums) uiImports.Add("USelect");
        if (hasBooleans) uiImports.Add("UCheckbox");
        if (uiImports.Count > 0)
            sb.Append("import { ").Append(string.Join(", ", uiImports)).AppendLine(" } from '../components/ui'");
        sb.Append("import type { ").Append(entityName).AppendLine(" } from '../types/entities_gen'");

        if (enumImports.Count > 0)
        {
            var typeImports = string.Join(", ", enumImports);
            sb.Append("import type { ").Append(typeImports).AppendLine(" } from '../types/enums_gen'");
            var labelImports = string.Join(", ", enumImports.Select(e => $"{e}Labels"));
            sb.Append("import { ").Append(labelImports).AppendLine(" } from '../types/enum_labels_gen'");
            sb.AppendLine("import { enumToOptions } from '../lib/select-options'");
        }

        sb.AppendLine();

        // Slots type (only when FK fields exist).
        if (fkFields.Count > 0)
        {
            sb.Append("export type ").Append(entityName).AppendLine("FormSlots = {");
            foreach (var fk in fkFields)
                sb.Append("  ").Append(fk).AppendLine("?: ReactNode");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // FormBase function.
        // When all fields are FK slots, form/onChange are not used in JSX.
        // Use destructuring rename { form: _form } to satisfy noUnusedParameters.
        var formDestructure = allFieldsAreSlots ? "form: _form" : "form";
        var onChangeDestructure = allFieldsAreSlots ? "onChange: _onChange" : "onChange";
        sb.Append("export function ").Append(entityName).AppendLine("FormBase({");
        sb.Append("  ").AppendLine(formDestructure + ",");
        sb.Append("  ").AppendLine(onChangeDestructure + ",");
        if (fkFields.Count > 0) sb.AppendLine("  slots,");
        sb.AppendLine("}: {");
        sb.Append("  form: Partial<").Append(entityName).AppendLine(">");
        sb.Append("  onChange: (updates: Partial<").Append(entityName).AppendLine(">) => void");
        if (fkFields.Count > 0) sb.Append("  slots?: ").Append(entityName).AppendLine("FormSlots");
        sb.AppendLine("}) {");
        sb.AppendLine("  return (");
        sb.AppendLine("    <>");

        foreach (var (sectionTitle, fields) in sections)
        {
            sb.Append("      <FormSection title=\"").Append(sectionTitle).AppendLine("\">");
            RenderSectionRows(sb, fields, enumNames);
            sb.AppendLine("      </FormSection>");
        }

        sb.AppendLine("    </>");
        sb.AppendLine("  )");
        sb.AppendLine("}");

        // Form-state helpers — empty defaults + entity→form mapper.
        // Closes the drift class where page EMPTY/handleEdit hand-enumerate fields and
        // silently omit newly-added m3l columns. Generated from stored (writable) fields only,
        // so Lookup/Rollup/Computed never leak into PATCH bodies.
        var camel = CamelCase(entityName);
        sb.AppendLine();
        sb.Append("export const empty").Append(entityName).Append(": Partial<").Append(entityName).Append("> = { ");
        sb.Append(string.Join(", ", storedFields.Select(f =>
            $"{TypeScriptTypeMapper.PascalCase(f.Name)}: {EmptyValue(f, enumNames)}")));
        sb.AppendLine(" }");
        sb.AppendLine();
        sb.Append("export function ").Append(camel).Append("FromEntity(row: ").Append(entityName).Append("): Partial<").Append(entityName).AppendLine("> {");
        sb.Append("  return { ");
        sb.Append(string.Join(", ", storedFields.Select(f =>
            $"{TypeScriptTypeMapper.PascalCase(f.Name)}: {FromEntityValue(f, enumNames)}")));
        sb.AppendLine(" }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string CamelCase(string pascal) =>
        string.IsNullOrEmpty(pascal) ? pascal : char.ToLowerInvariant(pascal[0]) + pascal[1..];

    private static bool IsNumberType(string? t) =>
        t != null && (t.StartsWith("integer", StringComparison.OrdinalIgnoreCase)
            || t.StartsWith("decimal", StringComparison.OrdinalIgnoreCase));

    /// <summary>Literal for the empty/new form state of a field (matches RenderField's coercion).</summary>
    private static string EmptyValue(FieldNode field, IReadOnlySet<string> enumNames)
    {
        var t = field.Type;
        var def = field.DefaultValue;
        var isEnum = t != null && enumNames.Contains(t);
        var isBool = string.Equals(t, "boolean", StringComparison.OrdinalIgnoreCase);
        if (!string.IsNullOrEmpty(def))
        {
            if (isEnum) return $"'{TypeScriptTypeMapper.PascalCase(def!)}'";
            if (isBool) return def!;            // "true" / "false"
            if (IsNumberType(t)) return def!;   // numeric literal
            return $"'{def}'";                  // string default
        }
        if (isBool) return "false";
        if (IsNumberType(t)) return field.Nullable ? "null" : "0";
        // enum not_null without a default has no valid empty literal ('' breaks the EnumType union);
        // emit undefined (valid in Partial<T>) so the user must pick. nullable → null.
        if (isEnum) return field.Nullable ? "null" : "undefined";
        if (string.Equals(t, "date", StringComparison.OrdinalIgnoreCase)) return field.Nullable ? "null" : "''";
        return "''";                             // string / text / identifier(FK) / json / phone
    }

    /// <summary>Expression mapping an entity row field into form state (write fields only).</summary>
    private static string FromEntityValue(FieldNode field, IReadOnlySet<string> enumNames)
    {
        var prop = TypeScriptTypeMapper.PascalCase(field.Name);
        var t = field.Type;
        var isEnum = t != null && enumNames.Contains(t);
        var isBool = string.Equals(t, "boolean", StringComparison.OrdinalIgnoreCase);
        if (isBool)
        {
            var def = !string.IsNullOrEmpty(field.DefaultValue) ? field.DefaultValue! : "false";
            return $"row.{prop} ?? {def}";
        }
        if (IsNumberType(t)) return $"row.{prop}";
        if (isEnum) return $"row.{prop}";
        if (string.Equals(t, "date", StringComparison.OrdinalIgnoreCase)) return $"row.{prop}";
        return field.Nullable ? $"row.{prop} ?? ''" : $"row.{prop}";
    }

    private static void RenderSectionRows(
        StringBuilder sb,
        List<FieldNode> fields,
        IReadOnlySet<string> enumNames)
    {
        var i = 0;
        while (i < fields.Count)
        {
            var field = fields[i];
            var isFullWidth = IsFullWidth(field);

            if (isFullWidth)
            {
                sb.AppendLine("        <FormRow full>");
                sb.Append("          ").AppendLine(RenderField(field, enumNames));
                sb.AppendLine("        </FormRow>");
                i++;
            }
            else if (i + 1 < fields.Count && !IsFullWidth(fields[i + 1]))
            {
                sb.AppendLine("        <FormRow>");
                sb.Append("          ").AppendLine(RenderField(field, enumNames));
                sb.Append("          ").AppendLine(RenderField(fields[i + 1], enumNames));
                sb.AppendLine("        </FormRow>");
                i += 2;
            }
            else
            {
                // unpaired half-width field
                sb.AppendLine("        <FormRow full>");
                sb.Append("          ").AppendLine(RenderField(field, enumNames));
                sb.AppendLine("        </FormRow>");
                i++;
            }
        }
    }

    private static bool IsFullWidth(FieldNode field)
    {
        if (HasAttribute(field, "reference")) return true;
        if (HasAttribute(field, "slot")) return true;
        if (string.Equals(field.Type, "text", StringComparison.OrdinalIgnoreCase)) return true;
        return false;
    }

    private static string RenderField(FieldNode field, IReadOnlySet<string> enumNames)
    {
        var prop = TypeScriptTypeMapper.PascalCase(field.Name);
        var label = field.Description ?? prop;
        var required = !field.Nullable;
        var requiredAttr = required ? " required" : "";

        // FK or @slot → slot placeholder.
        // Uses `!== undefined` check (not ??) so callers can pass null to suppress the field entirely.
        if (HasAttribute(field, "reference") || HasAttribute(field, "slot"))
            return $"{{slots?.{prop} !== undefined ? slots.{prop} : <span className=\"text-gray-400 text-xs\">{label} slot</span>}}";

        // boolean → UCheckbox
        if (string.Equals(field.Type, "boolean", StringComparison.OrdinalIgnoreCase))
            return $"<UCheckbox label=\"{label}\" checked={{form.{prop} ?? false}} onChange={{v => onChange({{ {prop}: v }})}} />";

        // enum → USelect
        if (field.Type != null && enumNames.Contains(field.Type))
        {
            var enumTypeName = TypeScriptTypeMapper.PascalCase(field.Type);
            // USelect.value is T extends string, it cannot accept null.
            // Use '' as the empty-state sentinel; onChange receives '' for no-selection.
            var placeholder = field.Nullable ? $" placeholder=\"{label} 선택\"" : "";
            var onChangeCast = field.Nullable
                ? $"v => onChange({{ {prop}: (v || null) as {enumTypeName} | null }})"
                : $"v => onChange({{ {prop}: v as {enumTypeName} }})";
            return $"<USelect label=\"{label}\"{requiredAttr}{placeholder} value={{form.{prop} ?? ''}} options={{enumToOptions({enumTypeName}Labels)}} onChange={{{onChangeCast}}} />";
        }

        // date → UInput type="date"
        // Required date fields use || undefined (Partial<T> expects T | undefined, not null).
        // Nullable date fields use || null (entity type is string | null, null is the correct empty value).
        if (string.Equals(field.Type, "date", StringComparison.OrdinalIgnoreCase))
        {
            var dateEmpty = field.Nullable ? "null" : "undefined";
            return $"<UInput label=\"{label}\"{requiredAttr} type=\"date\" value={{form.{prop} ?? ''}} onChange={{v => onChange({{ {prop}: v || {dateEmpty} }})}} />";
        }

        // text → UInput (full-width handled by IsFullWidth)
        if (string.Equals(field.Type, "text", StringComparison.OrdinalIgnoreCase))
            return $"<UInput label=\"{label}\" value={{form.{prop} ?? ''}} onChange={{v => onChange({{ {prop}: v || null }})}} />";

        // number types — onChange uses undefined (not null) because Partial<T> marks fields as T | undefined.
        if (field.Type != null && (field.Type.StartsWith("integer", StringComparison.OrdinalIgnoreCase)
            || field.Type.StartsWith("decimal", StringComparison.OrdinalIgnoreCase)))
            return $"<UInput label=\"{label}\"{requiredAttr} type=\"number\" value={{form.{prop} != null ? String(form.{prop}) : ''}} onChange={{v => onChange({{ {prop}: v ? Number(v) : undefined }})}} />";

        // string (default)
        return $"<UInput label=\"{label}\"{requiredAttr} value={{form.{prop} ?? ''}} onChange={{v => onChange({{ {prop}: v }})}} />";
    }

    private static string? GetAttributeString(FieldNode field, string attrName)
    {
        var attr = field.Attributes.FirstOrDefault(a =>
            string.Equals(a.Name, attrName, StringComparison.OrdinalIgnoreCase));
        if (attr?.Args is { Count: > 0 }
            && attr.Args[0].ValueKind == JsonValueKind.String)
        {
            return attr.Args[0].GetString();
        }
        return null;
    }

    private static bool HasAttribute(FieldNode field, string name) =>
        field.Attributes.Any(a => string.Equals(a.Name, name, StringComparison.OrdinalIgnoreCase));

    private static bool IsInheritedTimestamp(string fieldName) =>
        string.Equals(fieldName, "created_at", StringComparison.OrdinalIgnoreCase)
        || string.Equals(fieldName, "updated_at", StringComparison.OrdinalIgnoreCase);
}
