using System.Text;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.TypeScript;

/// <summary>
/// Renders all M3L entities into a single <c>entities_gen.ts</c> file.
/// Each entity becomes one TypeScript interface that extends <c>IyuEntity</c>.
/// </summary>
/// <remarks>
/// <para>
/// Unlike the C# generator which emits separate Write and Read classes, the
/// TypeScript interface merges base and Ext fields in one declaration — base
/// fields are required, Ext (Lookup/Rollup/Computed) fields are optional (<c>?</c>).
/// This mirrors the OData response shape: a GET may include expanded fields
/// while a PATCH body only carries stored columns.
/// </para>
/// <para>
/// The <c>id</c> / <c>created_at</c> / <c>updated_at</c> fields are elided
/// because <c>IyuEntity</c> already declares them.
/// </para>
/// </remarks>
public static class TsInterfaceRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>
    /// Renders all models into a single <c>entities_gen.ts</c> file content.
    /// Enums used by the models are imported from <c>./enums_gen</c>.
    /// </summary>
    public static string RenderAll(
        IReadOnlyList<ResolvedModel> models,
        IReadOnlySet<string>? knownEnumNames = null)
    {
        ArgumentNullException.ThrowIfNull(models);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();

        // Collect enums actually referenced by the models
        var usedEnums = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var model in models)
        {
            foreach (var f in model.Fields)
            {
                if (knownEnumNames is not null
                    && !string.IsNullOrWhiteSpace(f.Type)
                    && knownEnumNames.Contains(f.Type))
                {
                    usedEnums.Add(TypeScriptTypeMapper.PascalCase(f.Type));
                }
            }
        }

        if (usedEnums.Count > 0)
        {
            sb.Append("import type { ")
              .Append(string.Join(", ", usedEnums))
              .AppendLine(" } from './enums_gen'");
            sb.AppendLine();
        }

        // IyuEntity base
        sb.AppendLine("export interface IyuEntity {");
        sb.AppendLine("  Id: string");
        sb.AppendLine("  CreatedAt: string");
        sb.AppendLine("  UpdatedAt: string");
        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var model in models)
        {
            RenderInterface(sb, model, knownEnumNames);
        }

        return sb.ToString();
    }

    private static void RenderInterface(
        StringBuilder sb,
        ResolvedModel model,
        IReadOnlySet<string>? knownEnumNames)
    {
        var entityName = TypeScriptTypeMapper.PascalCase(model.Name);

        var storedFields = model.Fields
            .Where(f => f.Kind == FieldKind.Stored)
            .Where(f => !HasAttribute(f, "pk"))
            .Where(f => !IsInheritedTimestamp(f.Name))
            .ToList();

        var extFields = model.Fields
            .Where(f => f.Kind is FieldKind.Lookup or FieldKind.Rollup or FieldKind.Computed)
            .ToList();

        if (!string.IsNullOrWhiteSpace(model.Description))
        {
            sb.Append("/** ").Append(model.Description.Replace("*/", "* /").Replace('\n', ' ')).AppendLine(" */");
        }

        sb.Append("export interface ").Append(entityName).AppendLine(" extends IyuEntity {");

        // Stored (required) fields
        foreach (var f in storedFields)
        {
            var tsType = TypeScriptTypeMapper.MapFieldType(f.Type!, knownEnumNames);
            var nullable = f.Nullable ? " | null" : string.Empty;
            var prop = TypeScriptTypeMapper.PascalCase(f.Name);
            sb.Append("  ").Append(prop).Append(": ").Append(tsType).AppendLine(nullable);
        }

        // Ext (optional) fields — always present but may be undefined in write payloads
        if (extFields.Count > 0)
        {
            sb.AppendLine("  // Ext");
            // Build stored field nullability map for Lookup inheritance
            var storedNullability = storedFields.ToDictionary(f => f.Name, f => f.Nullable, StringComparer.Ordinal);

            foreach (var f in extFields)
            {
                var tsType = TypeScriptTypeMapper.MapFieldType(f.Type!, knownEnumNames);
                var effectiveNullable = ResolveExtNullable(f, storedNullability);
                var nullSuffix = effectiveNullable ? " | null" : string.Empty;
                var prop = TypeScriptTypeMapper.PascalCase(f.Name);
                // Ext fields are always optional (may not be returned in write contexts)
                sb.Append("  ").Append(prop).Append("?: ").Append(tsType).AppendLine(nullSuffix);
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static bool ResolveExtNullable(FieldNode f, Dictionary<string, bool> storedNullability)
    {
        if (f.Nullable) return true;
        if (f.Kind == FieldKind.Lookup)
        {
            var path = f.Lookup?.Path;
            if (!string.IsNullOrEmpty(path))
            {
                var dot = path.IndexOf('.');
                var fkName = dot > 0 ? path[..dot] : path;
                if (storedNullability.TryGetValue(fkName, out var fkNullable) && fkNullable)
                    return true;
            }
        }
        return false;
    }

    private static bool HasAttribute(FieldNode field, string name) =>
        MddBooster.Core.Ast.FieldAttributes.Has(field, name);

    private static bool IsInheritedTimestamp(string fieldName) =>
        string.Equals(fieldName, "created_at", StringComparison.OrdinalIgnoreCase)
        || string.Equals(fieldName, "updated_at", StringComparison.OrdinalIgnoreCase);
}
