using M3L.Native;
using MddBooster.Core.Ast;
using MddBooster.Generators.TypeScript;

namespace MddBooster.Tests.Generators.TypeScript;

public class TsEnumRendererTests
{
    private static M3lAst LoadFixture(string name) =>
        new M3lLoader().LoadFile(Path.Combine(AppContext.BaseDirectory, "fixtures", name));

    [Fact]
    public void Renders_union_literal_members_as_the_wire_name_not_the_CLR_member_name()
    {
        // Root defect (docket item 4d751cb9): the C# generator (EnumRenderer) already
        // emits [EnumMember(Value = "in_production")] as the wire name for member
        // `InProduction` — a server that honors [EnumMember] serializes/deserializes
        // using that lowercase form, not the CLR member name. The TS union type must
        // agree with the same wire form by construction.
        var ast = LoadFixture("order-with-enum.m3l.md");
        var orderStatus = ast.Enums.Single(e => e.Name == "OrderStatus");

        var result = TsEnumRenderer.RenderAll([orderStatus]);

        Assert.Contains("export type OrderStatus =", result);
        Assert.Contains("'draft'", result);
        Assert.Contains("'in_production'", result);
        Assert.DoesNotContain("'Draft'", result);
        Assert.DoesNotContain("'InProduction'", result);
    }

    [Fact]
    public void Emits_never_for_an_enum_with_no_values()
    {
        var ast = new M3lAst
        {
            Enums = [new EnumNode { Name = "Empty", Values = [] }]
        };

        var result = TsEnumRenderer.RenderAll(ast.Enums);

        Assert.Contains("export type Empty = never", result);
    }

    [Fact]
    public void Escapes_single_quotes_in_the_member_name()
    {
        var ast = new M3lAst
        {
            Enums =
            [
                new EnumNode
                {
                    Name = "Weird",
                    Values = [new EnumValue { Name = "o'clock" }]
                }
            ]
        };

        var result = TsEnumRenderer.RenderAll(ast.Enums);

        Assert.Contains("'o\\'clock'", result);
    }

    [Fact]
    public void Contains_auto_generated_header()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumRenderer.RenderAll(ast.Enums);

        Assert.StartsWith("// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>", result);
    }
}
