using M3L.Native;
using MddBooster.Core.Ast;
using MddBooster.Generators.TypeScript;

namespace MddBooster.Tests.Generators.TypeScript;

public class TsEnumLabelsRendererTests
{
    private static M3lAst LoadFixture(string name) =>
        new M3lLoader().LoadFile(Path.Combine(AppContext.BaseDirectory, "fixtures", name));

    [Fact]
    public void Renders_korean_labels_for_values_with_descriptions()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("export const OrderStatusLabels: Record<OrderStatus, string> = {", result);
        Assert.Contains("  Draft: '작성중',", result);
        Assert.Contains("  Confirmed: '확정',", result);
        Assert.Contains("  InProduction: '생산중',", result);
        Assert.Contains("  Shipped: '배송됨',", result);
        Assert.Contains("  Cancelled: '취소됨',", result);
    }

    [Fact]
    public void Renders_pascalcase_key_as_fallback_when_value_has_no_description()
    {
        var ast = new M3lAst
        {
            Enums =
            [
                new EnumNode
                {
                    Name = "Direction",
                    Values =
                    [
                        new EnumValue { Name = "up", Description = null },
                        new EnumValue { Name = "down", Description = null }
                    ]
                }
            ]
        };

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("  Up: 'Up',", result);
        Assert.Contains("  Down: 'Down',", result);
    }

    [Fact]
    public void Imports_all_enum_types_from_enums_gen()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("import type {", result);
        Assert.Contains("from './enums_gen'", result);
        Assert.Contains("OrderStatus", result);
        Assert.Contains("Priority", result);
    }

    [Fact]
    public void Renders_enum_description_as_jsdoc_comment()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("/** 주문 우선순위 */", result);
    }

    [Fact]
    public void Uses_as_const_for_type_narrowing()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("} as const", result);
    }

    [Fact]
    public void Contains_auto_generated_header()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.StartsWith("// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>", result);
    }

    [Fact]
    public void Escapes_single_quotes_in_label()
    {
        var ast = new M3lAst
        {
            Enums =
            [
                new EnumNode
                {
                    Name = "Status",
                    Values =
                    [
                        new EnumValue { Name = "special", Description = "고객's 주문" }
                    ]
                }
            ]
        };

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("  Special: '고객\\'s 주문',", result);
    }

    [Fact]
    public void Escapes_jsdoc_close_sequence_in_enum_description()
    {
        var ast = new M3lAst
        {
            Enums =
            [
                new EnumNode
                {
                    Name = "Status",
                    Description = "*/로 끝나는 설명",
                    Values = []
                }
            ]
        };

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("/** * /로 끝나는 설명 */", result);
    }

    // --- @system values: display labels vs input choices -----------------------
    // The root defect this addresses: a generated form rendered *every* enum value
    // as a choice, including ones only the system may write. Splitting the two
    // concerns into two maps is the fix — the label map stays complete so existing
    // rows still display, and a separate map carries what a person may pick.

    [Fact]
    public void Keeps_system_value_in_the_label_map()
    {
        var ast = LoadFixture("enum-system-value.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        // Existing rows holding this value must still render their label.
        Assert.Contains("export const PaymentMethodLabels: Record<PaymentMethod, string> = {", result);
        Assert.Contains("  LegacyCarryover: '레거시 이관 정리',", result);
    }

    [Fact]
    public void Emits_selectable_map_excluding_system_values()
    {
        var ast = LoadFixture("enum-system-value.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains(
            "export const PaymentMethodSelectableLabels: Record<Exclude<PaymentMethod, 'LegacyCarryover'>, string> = {",
            result);
        Assert.Contains("  Cash: '현금',", result);
        // The system value is absent from the entries — it appears only inside the
        // Exclude<> type expression, which is what performs the exclusion.
        var body = result.Replace("\r\n", "\n");
        var selectableBody = body[body.IndexOf(">, string> = {", body.IndexOf("PaymentMethodSelectableLabels", StringComparison.Ordinal), StringComparison.Ordinal)..];
        selectableBody = selectableBody[..selectableBody.IndexOf("} as const", StringComparison.Ordinal)];
        Assert.DoesNotContain("LegacyCarryover", selectableBody);
        Assert.Contains("Card:", selectableBody);
    }

    [Fact]
    public void Does_not_emit_selectable_map_when_no_value_is_system()
    {
        var ast = LoadFixture("enum-system-value.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        // Priority has no @system value — a second map would be dead weight.
        Assert.DoesNotContain("PrioritySelectableLabels", result);
    }
}
