using M3L.Native;
using MddBooster.Core.Ast;
using MddBooster.Generators.TypeScript;

namespace MddBooster.Tests.Generators.TypeScript;

public class TsEnumLabelsRendererTests
{
    private static M3lAst LoadFixture(string name) =>
        new M3lLoader().LoadFile(Path.Combine(AppContext.BaseDirectory, "fixtures", name));

    [Fact]
    public void Renders_korean_labels_for_values_with_descriptions()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("export const OrderStatusLabels: Record<OrderStatus, string> = {", result);
        Assert.Contains("  draft: '작성중',", result);
        Assert.Contains("  confirmed: '확정',", result);
        Assert.Contains("  in_production: '생산중',", result);
        Assert.Contains("  shipped: '배송됨',", result);
        Assert.Contains("  cancelled: '취소됨',", result);
    }

    [Fact]
    public void Keys_the_map_by_the_wire_name_not_the_CLR_member_name()
    {
        // The wire name is what a server that honors [EnumMember(Value=...)] actually
        // serializes/deserializes — the map must index by that, not by the PascalCase
        // C# member name (`EnumRenderer` renders the latter separately in Enum_gen).
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.DoesNotContain("Draft:", result);
        Assert.DoesNotContain("InProduction:", result);
    }

    [Fact]
    public void Renders_pascalcase_label_as_fallback_when_value_has_no_description()
    {
        var ast = new M3lAst
        {
            Enums =
            [
                new EnumNode
                {
                    Name = "Direction",
                    Values =
                    [
                        new EnumValue { Name = "up", Description = null },
                        new EnumValue { Name = "down", Description = null }
                    ]
                }
            ]
        };

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        // Key is the wire name (matches the OrderStatus-style union member); only the
        // display label falls back to a PascalCase rendering when no description exists.
        Assert.Contains("  up: 'Up',", result);
        Assert.Contains("  down: 'Down',", result);
    }

    [Fact]
    public void Imports_all_enum_types_from_enums_gen()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("import type {", result);
        Assert.Contains("from './enums_gen'", result);
        Assert.Contains("OrderStatus", result);
        Assert.Contains("Priority", result);
    }

    [Fact]
    public void Renders_enum_description_as_jsdoc_comment()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("/** 주문 우선순위 */", result);
    }

    [Fact]
    public void Uses_as_const_for_type_narrowing()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("} as const", result);
    }

    [Fact]
    public void Contains_auto_generated_header()
    {
        var ast = LoadFixture("order-with-enum.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.StartsWith("// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>", result);
    }

    [Fact]
    public void Escapes_single_quotes_in_label()
    {
        var ast = new M3lAst
        {
            Enums =
            [
                new EnumNode
                {
                    Name = "Status",
                    Values =
                    [
                        new EnumValue { Name = "special", Description = "고객's 주문" }
                    ]
                }
            ]
        };

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("  special: '고객\\'s 주문',", result);
    }

    [Fact]
    public void Escapes_jsdoc_close_sequence_in_enum_description()
    {
        var ast = new M3lAst
        {
            Enums =
            [
                new EnumNode
                {
                    Name = "Status",
                    Description = "*/로 끝나는 설명",
                    Values = []
                }
            ]
        };

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains("/** * /로 끝나는 설명 */", result);
    }

    // --- @system values: display labels vs input choices -----------------------
    // The root defect this addresses: a generated form rendered *every* enum value
    // as a choice, including ones only the system may write. Splitting the two
    // concerns into two maps is the fix — the label map stays complete so existing
    // rows still display, and a separate map carries what a person may pick.

    [Fact]
    public void Keeps_system_value_in_the_label_map()
    {
        var ast = LoadFixture("enum-system-value.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        // Existing rows holding this value must still render their label.
        Assert.Contains("export const PaymentMethodLabels: Record<PaymentMethod, string> = {", result);
        Assert.Contains("  legacy_carryover: '레거시 이관 정리',", result);
    }

    [Fact]
    public void Emits_selectable_map_excluding_system_values()
    {
        var ast = LoadFixture("enum-system-value.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        Assert.Contains(
            "export const PaymentMethodSelectableLabels: Record<Exclude<PaymentMethod, 'legacy_carryover'>, string> = {",
            result);
        Assert.Contains("  cash: '현금',", result);
        // The system value is absent from the entries — it appears only inside the
        // Exclude<> type expression, which is what performs the exclusion.
        var body = result.Replace("\r\n", "\n");
        var selectableBody = body[body.IndexOf(">, string> = {", body.IndexOf("PaymentMethodSelectableLabels", StringComparison.Ordinal), StringComparison.Ordinal)..];
        selectableBody = selectableBody[..selectableBody.IndexOf("} as const", StringComparison.Ordinal)];
        Assert.DoesNotContain("legacy_carryover", selectableBody);
        Assert.Contains("card:", selectableBody);
    }

    [Fact]
    public void Does_not_emit_selectable_map_when_no_value_is_system()
    {
        var ast = LoadFixture("enum-system-value.m3l.md");

        var result = TsEnumLabelsRenderer.RenderAll(ast.Enums);

        // Priority has no @system value — a second map would be dead weight.
        Assert.DoesNotContain("PrioritySelectableLabels", result);
    }

    [Fact]
    public void System_value_still_reaches_the_sql_check_constraint()
    {
        // @system constrains authoring, never storage. The value must remain a
        // legal stored value — the server and migrations write it. Asserted on
        // the same fixture that drives the form exclusion, so the two can never
        // drift into "excluded from the form AND rejected by the database".
        var ast = LoadFixture("enum-system-value.m3l.md");
        var paymentMethod = ast.Enums.Single(e => e.Name == "PaymentMethod");

        var check = MddBooster.Generators.Sql.EnumSqlConvention.CheckValues(paymentMethod);

        Assert.Contains("N'legacy_carryover'", check);
        Assert.Contains("N'cash'", check);
    }
}
