using MddBooster.Core.Ast;
using MddBooster.Core.Semantic;
using MddBooster.Generators.TypeScript;

namespace MddBooster.Tests.Generators.TypeScript;

public class TsFieldSchemaRendererTests
{
    private static IReadOnlyList<ResolvedModel> LoadFixture(string name)
    {
        var ast = new M3lLoader().LoadFile(Path.Combine(AppContext.BaseDirectory, "fixtures", name));
        return new InterfaceResolver(ast).ResolveAll();
    }

    [Fact]
    public void Emits_required_true_and_maxLength_for_non_nullable_string_field()
    {
        var models = LoadFixture("order-with-enum.m3l.md");

        var result = TsFieldSchemaRenderer.RenderAll(models);

        // order_number: string(30) — non-nullable → required: true, maxLength: 30
        Assert.Contains("OrderNumber: { required: true, maxLength: 30 },", result);
    }

    [Fact]
    public void Omits_nullable_field_with_no_other_constraints()
    {
        var models = LoadFixture("order-with-enum.m3l.md");

        var result = TsFieldSchemaRenderer.RenderAll(models);

        // notes: text? — nullable, no constraints → must not appear
        Assert.DoesNotContain("Notes:", result);
    }

    [Fact]
    public void Emits_min_from_attribute()
    {
        var models = LoadFixture("item-with-constraints.m3l.md");

        var result = TsFieldSchemaRenderer.RenderAll(models);

        // qty: integer @min(1) — non-nullable → required: true, min: 1
        Assert.Contains("Qty: { required: true, min: 1 },", result);
    }

    [Fact]
    public void Emits_min_and_max_from_attributes()
    {
        var models = LoadFixture("item-with-constraints.m3l.md");

        var result = TsFieldSchemaRenderer.RenderAll(models);

        // rate: decimal(5,2) = 0 @min(0) @max(100) — non-nullable → required: true, min: 0, max: 100
        Assert.Contains("Rate: { required: true, min: 0, max: 100 },", result);
    }

    [Fact]
    public void Wraps_result_in_as_const_satisfies()
    {
        var models = LoadFixture("order-with-enum.m3l.md");

        var result = TsFieldSchemaRenderer.RenderAll(models);

        Assert.Contains("} as const satisfies Record<string, Record<string, FieldConstraints>>", result);
    }

    [Fact]
    public void Contains_auto_generated_header()
    {
        var models = LoadFixture("order-with-enum.m3l.md");

        var result = TsFieldSchemaRenderer.RenderAll(models);

        Assert.StartsWith("// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>", result);
    }
}
