using M3L.Native;
using MddBooster.Core.Ast;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;
using MddBooster.Generators.Sql.Postgres;

namespace MddBooster.Tests.Generators.Sql.Postgres;

public class PgTableRendererTests
{
    private static string FixturePath(string name) =>
        Path.Combine(AppContext.BaseDirectory, "fixtures", name);

    private static (IReadOnlyList<ResolvedModel> Models,
                    IReadOnlyDictionary<string, ResolvedModel> Lookup,
                    IReadOnlyDictionary<string, string> TableNames,
                    IReadOnlyDictionary<string, EnumNode> Enums)
        Load(string fixture)
    {
        var ast = new M3lLoader().LoadFile(FixturePath(fixture));
        var models = new InterfaceResolver(ast).ResolveAll().ToList();
        var lookup = models.ToDictionary(m => m.Name, StringComparer.Ordinal);
        var tableNames = PostgresIdentifiers.BuildTableNameMap(models.Select(m => m.Name));
        var enums = ast.Enums.ToDictionary(e => e.Name, StringComparer.Ordinal);
        return (models, lookup, tableNames, enums);
    }

    private static string Normalize(string s) =>
        s.Replace("\r\n", "\n").TrimEnd() + "\n";

    [Fact]
    public void Render_BankAccount_ProducesExpectedPgDdl()
    {
        var (_, lookup, tableNames, enums) = Load("bank-account.m3l.md");
        var model = lookup["BankAccount"];

        var artifact = PgTableRenderer.Render(model, "public", tableNames, lookup, enums);

        var expected = """
-- # Code generated by "mdd-booster"; DO NOT EDIT.
CREATE TABLE public.bank_account
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    bank_name varchar(30) NOT NULL,
    account_number varchar(40) NOT NULL,
    holder_name varchar(30) NOT NULL,
    note varchar(200),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_bank_account PRIMARY KEY (id),
    CONSTRAINT uq_bank_account_account_number UNIQUE (account_number)
);
""";
        Assert.Equal(Normalize(expected), Normalize(artifact.Sql));
        Assert.Equal("bank_account", artifact.TableName);
        Assert.Empty(artifact.Warnings);
    }

    [Fact]
    public void Render_SharedPkExtension_EmitsPkAndFkOnSameColumn()
    {
        var (_, lookup, tableNames, enums) = Load("shared-pk-extension.m3l.md");
        var model = lookup["AssetMaintenanceProfile"];

        var artifact = PgTableRenderer.Render(model, "public", tableNames, lookup, enums);

        var expected = """
-- # Code generated by "mdd-booster"; DO NOT EDIT.
CREATE TABLE public.asset_maintenance_profile
(
    asset_id uuid NOT NULL,
    criticality_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_asset_maintenance_profile PRIMARY KEY (asset_id),
    CONSTRAINT fk_asset_maintenance_profile_asset_id FOREIGN KEY (asset_id) REFERENCES public.asset (id),
    CONSTRAINT fk_asset_maintenance_profile_criticality_id FOREIGN KEY (criticality_id) REFERENCES public.asset_criticality (id)
);
""";
        Assert.Equal(Normalize(expected), Normalize(artifact.Sql));
    }

    [Fact]
    public void Render_FkTargetWithNonIdPk_ReferencesTargetPkPhysicalName()
    {
        // FacilityProfile의 PK 물리명은 facility_id — [Id] 하드코딩이 제거됐다는 증명
        var (_, lookup, tableNames, enums) = Load("pg-reference-chain.m3l.md");
        var model = lookup["FacilityInspection"];

        var artifact = PgTableRenderer.Render(model, "public", tableNames, lookup, enums);

        Assert.Contains(
            "CONSTRAINT fk_facility_inspection_facility_profile_id FOREIGN KEY (facility_profile_id) " +
            "REFERENCES public.facility_profile (facility_id)",
            artifact.Sql);
    }

    [Fact]
    public void Render_IndexAttributes_AreSkippedWithWarnings()
    {
        // Schemorph PG P1은 인덱스를 명시 거부 — CREATE INDEX 방출 금지, 무음 탈락도 금지
        var (_, lookup, tableNames, enums) = Load("pg-reference-chain.m3l.md");
        var model = lookup["FacilityInspection"];

        var artifact = PgTableRenderer.Render(model, "public", tableNames, lookup, enums);

        Assert.DoesNotContain("CREATE INDEX", artifact.Sql);
        Assert.Equal(2, artifact.Warnings.Count); // field-level @index(status) + section @index(facility_profile_id)
        Assert.Contains(artifact.Warnings, w => w.Contains("status"));
        Assert.Contains(artifact.Warnings, w => w.Contains("facility_profile_id"));
    }

    [Fact]
    public void Render_NullableUnique_EmitsPlainUniqueConstraint()
    {
        // PG UNIQUE는 NULL을 distinct로 취급 — T-SQL filtered index 우회가 필요 없다
        var (_, lookup, tableNames, enums) = Load("pg-reference-chain.m3l.md");
        var model = lookup["FacilityInspection"];

        var artifact = PgTableRenderer.Render(model, "public", tableNames, lookup, enums);

        Assert.Contains("CONSTRAINT uq_facility_inspection_serial_no UNIQUE (serial_no)", artifact.Sql);
        Assert.DoesNotContain("WHERE", artifact.Sql);
    }

    [Fact]
    public void Render_SectionUnique_EmitsCompositeUniqueConstraint()
    {
        // Load 헬퍼는 픽스처 전 모델을 매핑하는데 이 픽스처의 Order는 PG 예약어라
        // 게이트에 걸린다(정상 동작) — Membership만 직접 매핑한다.
        var ast = new M3lLoader().LoadFile(FixturePath("table-with-indexes.m3l.md"));
        var models = new InterfaceResolver(ast).ResolveAll().ToList();
        var lookup = models.ToDictionary(m => m.Name, StringComparer.Ordinal);
        var model = lookup["Membership"];
        var tableNamesSafe = PostgresIdentifiers.BuildTableNameMap(["Membership"]);

        var artifact = PgTableRenderer.Render(model, "public", tableNamesSafe, lookup,
            ast.Enums.ToDictionary(e => e.Name, StringComparer.Ordinal));

        Assert.Contains(
            "CONSTRAINT uq_membership_user_id_group_id UNIQUE (user_id, group_id)",
            artifact.Sql);
    }

    [Fact]
    public void Render_EnumCheckOptIn_EmitsAnsiCheckConstraint()
    {
        var (_, lookup, tableNames, enums) = Load("enum-default.m3l.md");
        var model = lookup["Item"];

        var artifact = PgTableRenderer.Render(
            model, "public", tableNames, lookup, enums, emitEnumCheckConstraints: true);

        // N'..' 접두사 없는 ANSI 리터럴 + enum default
        Assert.Contains("CONSTRAINT ck_item_status CHECK (status IN ('draft', 'published'))", artifact.Sql);
        Assert.Contains("status varchar(20) NOT NULL DEFAULT 'draft'", artifact.Sql);
        Assert.Contains("code varchar(20) NOT NULL DEFAULT 'TBD'", artifact.Sql);
        Assert.DoesNotContain("N'", artifact.Sql);
    }

    [Fact]
    public void Render_ReservedColumnName_ThrowsWithoutQuoting()
    {
        var (_, lookup, tableNames, enums) = Load("pg-bad-column.m3l.md");
        var model = lookup["AuditRow"];

        var ex = Assert.Throws<PostgresNamingException>(
            () => PgTableRenderer.Render(model, "public", tableNames, lookup, enums));

        Assert.Contains("order", ex.Message);
        Assert.Contains("AuditRow", ex.Message);
    }
}
