using System.Text;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Api;

/// <summary>
/// Renders a single <c>ApiRegistration_gen.cs</c> file that wires every
/// generated entity pair into OData (EDM model) and GraphQL (HotChocolate
/// schema). The consumer project calls the generated static method once in
/// its composition root — <c>Yesung.MainServer</c> already expects a helper
/// of this shape via the iyu-framework-v5 API surface.
/// </summary>
/// <remarks>
/// The generated method signature is:
/// <code>
/// public static void RegisterGeneratedEntities(global::Iyu.MainServer.IyuMainServerOptions options)
/// </code>
/// For every model <c>Order</c>, the method body emits two lines:
/// <code>
/// options.ODataModel.AddEntityPair&lt;OrderExt, Order&gt;("Orders");
/// options.GraphQL.AddEntityPair&lt;OrderExt, Order&gt;("orders", "order");
/// </code>
/// Entity set names use <see cref="Pluralizer"/> to match the DbContext
/// convention; GraphQL query names are camelCase plural; mutation prefix is
/// camelCase singular (HotChocolate mutation field naming convention).
/// </remarks>
public static class ApiRegistrationRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string Render(
        IReadOnlyList<ResolvedModel> models,
        string ns,
        string? entitiesNamespace = null,
        string methodName = "RegisterGeneratedEntities")
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);
        ArgumentException.ThrowIfNullOrWhiteSpace(methodName);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(entitiesNamespace) && entitiesNamespace != ns)
        {
            sb.Append("using ").Append(entitiesNamespace).AppendLine(";");
            sb.AppendLine();
        }
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("public static partial class ApiRegistration");
        sb.AppendLine("{");
        sb.Append("    public static void ").Append(methodName)
          .AppendLine("(global::Iyu.MainServer.IyuMainServerOptions options)");
        sb.AppendLine("    {");

        foreach (var model in models.OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            var entity = PascalCase(model.Name);
            var setName = MddBooster.Core.Naming.Pluralizer.Pluralize(entity);
            var queryName = CamelCase(setName);       // e.g. "orders"
            var mutationPrefix = CamelCase(entity);    // e.g. "order"

            sb.Append("        options.ODataModel.AddEntityPair<")
              .Append(entity).Append("Ext, ").Append(entity).Append(">(\"")
              .Append(setName).AppendLine("\");");
            sb.Append("        options.GraphQL.AddEntityPair<")
              .Append(entity).Append("Ext, ").Append(entity).Append(">(\"")
              .Append(queryName).Append("\", \"").Append(mutationPrefix).AppendLine("\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }

    private static string CamelCase(string pascal)
    {
        if (string.IsNullOrEmpty(pascal)) return pascal;
        return char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }
}
