using System.Text;
using MddBooster.Core.Generation;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Api;

/// <summary>
/// Emits one thin concrete subclass of <c>IyuODataController&lt;TRead, TWrite&gt;</c>
/// per model into a single <c>Controllers_gen.cs</c> file. These classes exist
/// purely to satisfy ASP.NET Core MVC's <c>ControllerFeatureProvider</c> — MVC
/// filters out generic and abstract types from the default controller discovery,
/// so a named non-generic subclass is required for each OData entity set.
/// </summary>
/// <remarks>
/// The naming convention uses the plural form (<see cref="Pluralizer"/>) so the
/// OData convention router binds <c>{EntitySetName}Controller</c> to the matching
/// EDM set name produced by <see cref="ApiRegistrationRenderer"/>.
/// </remarks>
public static class ODataControllerRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string Render(
        IReadOnlyList<ResolvedModel> models,
        string ns,
        string? entitiesNamespace = null)
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // 엔티티는 using 임포트가 아니라 한정 이름으로 가리킨다 — 이유는 EntityTypeRef 참조.
        // 파일의 네임스페이스는 `{ns}.Controllers` 이지만 판별 기준은 `ns` 다: entitiesNamespace 가
        // `ns` 와 같으면 엔티티는 «둘러싼» 네임스페이스에 있어 임포트 없이 찾아지고, 둘러싼
        // 네임스페이스는 임포트보다 먼저 해석되므로 그 경우에도 충돌이 성립하지 않는다.
        var entityPrefix = EntityTypeRef.PrefixFor(ns, entitiesNamespace);
        sb.Append("namespace ").Append(ns).AppendLine(".Controllers;");
        sb.AppendLine();

        foreach (var model in models.OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            // @internal 엔티티는 OData 컨트롤러를 생성하지 않는다(ApiRegistration 등록 제외와 짝).
            if (EntitySurface.IsInternal(model)) continue;

            var entity = NameCasing.ToPascalCase(model.Name);
            var setName = Pluralizer.Pluralize(entity);

            sb.Append("public sealed partial class ").Append(setName).AppendLine("Controller");
            sb.Append("    : IyuODataController<")
              .Append(entityPrefix).Append(entity).Append("Ext, ")
              .Append(entityPrefix).Append(entity).AppendLine(">");
            sb.AppendLine("{");
            sb.Append("    public ").Append(setName).AppendLine("Controller(IyuDbContext context)");
            sb.AppendLine("        : base(context) { }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

}
