using System.Text;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Api;

/// <summary>
/// Emits one thin concrete subclass of <c>IyuODataController&lt;TRead, TWrite&gt;</c>
/// per model into a single <c>Controllers_gen.cs</c> file. These classes exist
/// purely to satisfy ASP.NET Core MVC's <c>ControllerFeatureProvider</c> — MVC
/// filters out generic and abstract types from the default controller discovery,
/// so a named non-generic subclass is required for each OData entity set.
/// </summary>
/// <remarks>
/// The naming convention uses the plural form (<see cref="Pluralizer"/>) so the
/// OData convention router binds <c>{EntitySetName}Controller</c> to the matching
/// EDM set name produced by <see cref="ApiRegistrationRenderer"/>.
/// </remarks>
public static class ODataControllerRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string Render(
        IReadOnlyList<ResolvedModel> models,
        string ns,
        string? entitiesNamespace = null)
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(entitiesNamespace) && entitiesNamespace != ns)
        {
            sb.Append("using ").Append(entitiesNamespace).AppendLine(";");
            sb.AppendLine();
        }
        sb.Append("namespace ").Append(ns).AppendLine(".Controllers;");
        sb.AppendLine();

        foreach (var model in models.OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            // @internal 엔티티는 OData 컨트롤러를 생성하지 않는다(ApiRegistration 등록 제외와 짝).
            if ((model.Source.Attributes ?? [])
                .Any(a => string.Equals(a.Name, "internal", StringComparison.OrdinalIgnoreCase)))
                continue;

            var entity = PascalCase(model.Name);
            var setName = Pluralizer.Pluralize(entity);

            sb.Append("public sealed partial class ").Append(setName).AppendLine("Controller");
            sb.Append("    : global::Iyu.Server.OData.IyuODataController<")
              .Append(entity).Append("Ext, ").Append(entity).AppendLine(">");
            sb.AppendLine("{");
            sb.Append("    public ").Append(setName).AppendLine("Controller(global::Iyu.Data.IyuDbContext context)");
            sb.AppendLine("        : base(context) { }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
