using System.Text;
using MddBooster.Core.Generation;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Api;

/// <summary>
/// Renders <c>Api_gen/Permissions_gen.cs</c> — one constant per (entity set, verb) plus the
/// entity-set → (read, write) default map.
/// </summary>
/// <remarks>
/// The registration file already emits the entity-set list; without the permission dimension a
/// consumer keeps a second, hand-written list of the same sets, and a set missing from that copy
/// falls through to whatever the fallback policy is — with nothing in the build, the types, the
/// tests, or the response to say so. Deriving the default from the same source that emits the
/// sets is what removes the copy.
/// <para>
/// Read and write only, matching the runtime's own pair
/// (<c>RestrictPolicy(setName, readPolicy, writePolicy)</c>). Delete is part of the write half
/// there, so emitting a third verb would invent a distinction the thing consuming these keys does
/// not make.
/// </para>
/// </remarks>
public static class PermissionsRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    /// <summary>Verbs a key is emitted for, matching the runtime's read/write policy pair.</summary>
    public static readonly IReadOnlyList<string> Verbs = ["read", "write"];

    public static string Render(IReadOnlyList<ResolvedModel> models, string ns, string template)
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);
        ArgumentException.ThrowIfNullOrWhiteSpace(template);

        // Same exclusion the registration file applies: an @internal entity has no data-API
        // surface, so a permission key for it would name an endpoint that does not exist.
        var sets = models
            .Where(m => !EntitySurface.IsInternal(m))
            .Select(m => Pluralizer.Pluralize(NameCasing.ToPascalCase(m.Name)))
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Permission keys derived from the generated entity sets, using the");
        sb.AppendLine("/// <c>permissionKeyTemplate</c> configured for this target.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// Keys that are not entity-derived (a field-level permission, an");
        sb.AppendLine("/// administrative one) are the application's to declare — this type covers");
        sb.AppendLine("/// the mechanical part so a new entity cannot be silently missing from it.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine("public static class GeneratedPermissions");
        sb.AppendLine("{");

        foreach (var set in sets)
        {
            foreach (var verb in Verbs)
            {
                var member = set + char.ToUpperInvariant(verb[0]) + verb[1..];
                sb.Append("    public const string ").Append(member).Append(" = \"")
                  .Append(PermissionKeyTemplate.Expand(template, set, verb)).AppendLine("\";");
            }
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Entity set name → (read, write) keys. A consumer maps its sets from");
        sb.AppendLine("    /// this and layers only its exceptions on top, so adding an entity to the");
        sb.AppendLine("    /// model cannot leave a hole in the map.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, (string Read, string Write)> Default =");
        sb.AppendLine("        new Dictionary<string, (string Read, string Write)>");
        sb.AppendLine("        {");
        foreach (var set in sets)
        {
            sb.Append("            [\"").Append(set).Append("\"] = (")
              .Append(set).Append("Read, ").Append(set).AppendLine("Write),");
        }
        sb.AppendLine("        };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
