using System.Text;
using M3L.Native;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Model;

/// <summary>
/// Renders a partial <c>{Name}DbContext</c> class that inherits from
/// <c>IyuDbContext</c> and exposes a <c>DbSet&lt;T&gt;</c> and
/// <c>DbSet&lt;TExt&gt;</c> for every entity in the input model collection.
/// </summary>
/// <remarks>
/// The Ext read model is mapped to the highest available view layer by priority:
/// <c>ExtView</c> (user-maintained) &gt; <c>FullView</c> &gt; <c>UdView</c> &gt; base table.
/// The caller passes <paramref name="customExtViewModels"/> for the ExtView tier;
/// UdView and FullView tiers are detected from model fields.
/// </remarks>
public static class DbContextRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string Render(
        IReadOnlyList<ResolvedModel> models,
        string contextName,
        string ns,
        IReadOnlySet<string>? customExtViewModels = null)
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentException.ThrowIfNullOrWhiteSpace(contextName);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("public partial class ").Append(contextName)
          .AppendLine(" : global::Iyu.Data.IyuDbContext");
        sb.AppendLine("{");
        sb.Append("    public ").Append(contextName)
          .Append("(DbContextOptions<").Append(contextName).AppendLine("> options)");
        sb.AppendLine("        : base(options) { }");

        var ordered = models.OrderBy(m => m.Name, StringComparer.Ordinal).ToList();

        foreach (var model in ordered)
        {
            var name = PascalCase(model.Name);
            var plural = Pluralizer.Pluralize(name);

            sb.AppendLine();
            sb.Append("    public DbSet<").Append(name).Append("> ")
              .Append(plural).Append(" => Set<").Append(name).AppendLine(">();");
            sb.Append("    public DbSet<").Append(name).Append("Ext> ")
              .Append(plural).Append("Ext => Set<").Append(name).AppendLine("Ext>();");
        }

        // OnModelCreating: map all Ext read models to their view layer.
        // Priority: ExtView (user file) > FullView > UdView > base table.
        var extMappings = ordered
            .Select(m => new
            {
                Name = PascalCase(m.Name),
                Backing = ClassifyBacking(m, customExtViewModels)
            })
            .ToList();

        sb.AppendLine();
        sb.AppendLine("    protected override void OnModelCreating(ModelBuilder modelBuilder)");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnModelCreating(modelBuilder);");
        foreach (var m in extMappings)
        {
            var viewName = m.Backing switch
            {
                "ext" => m.Name + "ExtView",
                "full" => m.Name + "FullView",
                "ud" => m.Name + "UdView",
                _ => m.Name,   // base table
            };
            sb.Append("        modelBuilder.Entity<").Append(m.Name).Append("Ext>().ToTable((string?)null).ToView(\"")
              .Append(viewName).AppendLine("\");");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ClassifyBacking(ResolvedModel model, IReadOnlySet<string>? customExtViewModels)
    {
        var name = PascalCase(model.Name);
        if (customExtViewModels != null && customExtViewModels.Contains(name)) return "ext";
        if (model.Fields.Any(f => f.Kind is FieldKind.Lookup or FieldKind.Rollup or FieldKind.Computed)) return "full";
        if (model.Fields.Any(f => f.Kind == FieldKind.Stored &&
            string.Equals(f.Name, "deleted_at", StringComparison.Ordinal))) return "ud";
        return "none";
    }

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
