using System.Text;
using M3L.Native;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Model;

/// <summary>
/// Renders a partial <c>{Name}DbContext</c> class that inherits from
/// <c>IyuDbContext</c> and exposes a <c>DbSet&lt;T&gt;</c> and
/// <c>DbSet&lt;TExt&gt;</c> for every entity in the input model collection.
/// </summary>
/// <remarks>
/// The Ext read model is mapped to the highest available view layer by priority:
/// <c>ExtView</c> (user-maintained) &gt; <c>FullView</c> &gt; <c>UdView</c> &gt; base table.
/// The caller passes <paramref name="customExtViewModels"/> for the ExtView tier;
/// UdView and FullView tiers are detected from model fields.
/// </remarks>
public static class DbContextRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string Render(
        IReadOnlyList<ResolvedModel> models,
        string contextName,
        string ns,
        IReadOnlySet<string>? customExtViewModels = null,
        bool postgresNaming = false)
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentException.ThrowIfNullOrWhiteSpace(contextName);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("public partial class ").Append(contextName)
          .AppendLine(" : global::Iyu.Data.IyuDbContext");
        sb.AppendLine("{");
        sb.Append("    public ").Append(contextName)
          .Append("(DbContextOptions<").Append(contextName).AppendLine("> options)");
        sb.AppendLine("        : base(options) { }");

        var ordered = models.OrderBy(m => m.Name, StringComparer.Ordinal).ToList();

        foreach (var model in ordered)
        {
            var name = PascalCase(model.Name);
            var plural = Pluralizer.Pluralize(name);

            sb.AppendLine();
            sb.Append("    public DbSet<").Append(name).Append("> ")
              .Append(plural).Append(" => Set<").Append(name).AppendLine(">();");
            sb.Append("    public DbSet<").Append(name).Append("Ext> ")
              .Append(plural).Append("Ext => Set<").Append(name).AppendLine("Ext>();");
        }

        // OnModelCreating: map all Ext read models to their view layer.
        // Priority: ExtView (user file) > FullView > UdView > base table.
        var extMappings = ordered
            .Select(m => new
            {
                Name = PascalCase(m.Name),
                Backing = ClassifyBacking(m, customExtViewModels)
            })
            .ToList();

        sb.AppendLine();
        sb.AppendLine("    protected override void OnModelCreating(ModelBuilder modelBuilder)");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnModelCreating(modelBuilder);");

        if (postgresNaming)
        {
            // ADR-0001 §2.3: 모델 PascalCase ↔ DB snake_case 간극은 생성 코드에 구운
            // 명시 매핑이 흡수한다 — 런타임 컨벤션 추론 없음. 테이블명은 PG 방언과
            // 같은 변환(PostgresIdentifiers), 컬럼명은 M3L 필드명 그대로.
            RenderPostgresMappings(sb, ordered, customExtViewModels);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        foreach (var m in extMappings)
        {
            var viewName = m.Backing switch
            {
                "ext" => m.Name + "ExtView",
                "full" => m.Name + "FullView",
                "ud" => m.Name + "UdView",
                _ => m.Name,   // base table
            };
            sb.Append("        modelBuilder.Entity<").Append(m.Name).Append("Ext>().ToTable((string?)null).ToView(\"")
              .Append(viewName).AppendLine("\");");
        }

        // 공유/명명 PK(필드명 != id): 상속된 IyuEntity.Id를 실제 PK 컬럼으로 재매핑.
        // 예: asset_id @pk @reference(Asset) → SQL 컬럼 [AssetId], 엔티티는 Id로 접근.
        foreach (var model in ordered)
        {
            var pk = ModelPrimaryKey.Find(model);
            if (pk is null || !ModelPrimaryKey.IsNonIdPk(pk)) continue;

            var name = PascalCase(model.Name);
            var column = PascalCase(pk.Name);
            sb.Append("        modelBuilder.Entity<").Append(name)
              .Append(">().Property(e => e.Id).HasColumnName(\"").Append(column).AppendLine("\");");
            sb.Append("        modelBuilder.Entity<").Append(name)
              .Append("Ext>().Property(e => e.Id).HasColumnName(\"").Append(column).AppendLine("\");");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// PG 방언의 엔티티별 명시 매핑 블록. 쓰기 엔티티는 snake 테이블로, Ext 읽기 모델은
    /// 뷰 backing이 없으면 같은 snake 테이블을 뷰로 읽는다(뷰 backing이 있으면 기존
    /// 뷰 이름을 유지 — PG 방언은 뷰를 방출하지 않으므로 ModelGenerator가 경고한다).
    /// 컬럼 매핑은 저장 필드 전체: 속성 PascalCase → 컬럼 = M3L 필드명 그대로.
    /// 공유 PK(필드명 != id)는 상속된 <c>Id</c> 속성이 그 필드의 물리명으로 간다.
    /// <c>json</c> 필드는 DDL이 jsonb이므로 <c>HasColumnType("jsonb")</c>를 함께 굽는다(D24).
    /// </summary>
    private static void RenderPostgresMappings(
        StringBuilder sb,
        IReadOnlyList<ResolvedModel> ordered,
        IReadOnlySet<string>? customExtViewModels)
    {
        var tableNames = PostgresIdentifiers.BuildTableNameMap(ordered.Select(m => m.Name));

        foreach (var model in ordered)
        {
            var name = PascalCase(model.Name);
            var table = tableNames[model.Name];
            var pk = ModelPrimaryKey.Find(model);
            var backing = ClassifyBacking(model, customExtViewModels);
            var extView = backing switch
            {
                "ext" => name + "ExtView",
                "full" => name + "FullView",
                "ud" => name + "UdView",
                _ => table,   // 뷰 backing 없음 — 같은 snake 테이블을 읽는다
            };

            sb.AppendLine();
            sb.Append("        modelBuilder.Entity<").Append(name).AppendLine(">(e =>");
            sb.AppendLine("        {");
            sb.Append("            e.ToTable(\"").Append(table).AppendLine("\");");
            AppendPostgresColumns(sb, model, pk);
            sb.AppendLine("        });");

            sb.Append("        modelBuilder.Entity<").Append(name).AppendLine("Ext>(e =>");
            sb.AppendLine("        {");
            sb.AppendLine("            e.ToTable((string?)null);");
            sb.Append("            e.ToView(\"").Append(extView).AppendLine("\");");
            AppendPostgresColumns(sb, model, pk);
            sb.AppendLine("        });");
        }
    }

    private static void AppendPostgresColumns(StringBuilder sb, ResolvedModel model, FieldNode? pk)
    {
        foreach (var field in BaseColumnsOf(model))
        {
            // 공유/명명 PK 필드는 엔티티에 별도 속성이 없다 — 상속된 Id가 그 컬럼이다.
            var property = ReferenceEquals(field, pk) ? "Id" : PascalCase(field.Name);
            sb.Append("            e.Property(x => x.").Append(property)
              .Append(").HasColumnName(\"").Append(field.Name).Append("\")");
            if (string.Equals(field.Type, "json", StringComparison.Ordinal))
            {
                sb.Append(".HasColumnType(\"jsonb\")");
            }
            sb.AppendLine(";");
        }
    }

    private static IEnumerable<FieldNode> BaseColumnsOf(ResolvedModel model)
        => model.Fields.Where(f => f.Kind == FieldKind.Stored);

    private static string ClassifyBacking(ResolvedModel model, IReadOnlySet<string>? customExtViewModels)
    {
        var name = PascalCase(model.Name);
        if (customExtViewModels != null && customExtViewModels.Contains(name)) return "ext";
        if (model.Fields.Any(f => f.Kind is FieldKind.Lookup or FieldKind.Rollup or FieldKind.Computed)) return "full";
        if (model.Fields.Any(f => f.Kind == FieldKind.Stored &&
            string.Equals(f.Name, "deleted_at", StringComparison.Ordinal))) return "ud";
        return "none";
    }

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
