using System.Text;
using M3L.Native;
using MddBooster.Core.Naming;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Model;

/// <summary>
/// Renders a partial <c>{Name}DbContext</c> class that inherits from
/// <c>IyuDbContext</c> and exposes a <c>DbSet&lt;T&gt;</c> and
/// <c>DbSet&lt;TExt&gt;</c> for every entity in the input model collection.
/// </summary>
/// <remarks>
/// <para>
/// The generated file lives in <c>DbContext_gen/</c> and is marked
/// <c>partial</c> so that consumers can add bespoke <c>OnModelCreating</c>
/// configuration in a sibling <c>DbContext/</c> file without touching
/// generated code.
/// </para>
/// <para>
/// Plural naming convention: the DbSet name is <c>PluralOf(EntityName)</c>
/// using naïve "+s" pluralization. Yesung entities don't have irregular
/// plurals; the spec defers custom override support to a future
/// configuration option.
/// </para>
/// </remarks>
public static class DbContextRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string Render(
        IReadOnlyList<ResolvedModel> models,
        string contextName,
        string ns)
    {
        ArgumentNullException.ThrowIfNull(models);
        ArgumentException.ThrowIfNullOrWhiteSpace(contextName);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("public partial class ").Append(contextName)
          .AppendLine(" : global::Iyu.Data.IyuDbContext");
        sb.AppendLine("{");
        sb.Append("    public ").Append(contextName)
          .Append("(DbContextOptions<").Append(contextName).AppendLine("> options)");
        sb.AppendLine("        : base(options) { }");

        var ordered = models.OrderBy(m => m.Name, StringComparer.Ordinal).ToList();

        foreach (var model in ordered)
        {
            var name = PascalCase(model.Name);
            var plural = Pluralizer.Pluralize(name);

            sb.AppendLine();
            sb.Append("    public DbSet<").Append(name).Append("> ")
              .Append(plural).Append(" => Set<").Append(name).AppendLine(">();");
            sb.Append("    public DbSet<").Append(name).Append("Ext> ")
              .Append(plural).Append("Ext => Set<").Append(name).AppendLine("Ext>();");
        }

        // OnModelCreating override — map ALL Ext read models so EF Core treats
        // them separately from the write entities. Models with derived fields
        // map to their SQL view (_full or _ext); table-only models map to the
        // base table via ToView() so EF Core sees them as a distinct read-only
        // mapping (avoids the "shared table" validation error on SQL Server).
        var extMappings = ordered
            .Select(m => new { Name = PascalCase(m.Name), Backing = ClassifyBacking(m) })
            .ToList();

        sb.AppendLine();
        sb.AppendLine("    protected override void OnModelCreating(ModelBuilder modelBuilder)");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnModelCreating(modelBuilder);");
        foreach (var m in extMappings)
        {
            var viewName = m.Backing switch
            {
                "ext" => m.Name + "_ext",
                "full" => m.Name + "_full",
                _ => m.Name,   // table-only: map to base table as a "view"
            };
            sb.Append("        modelBuilder.Entity<").Append(m.Name).Append("Ext>().ToTable((string?)null).ToView(\"")
              .Append(viewName).AppendLine("\");");
        }
        sb.AppendLine("    }");


        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ClassifyBacking(ResolvedModel model)
    {
        if (model.Fields.Any(f => f.Kind is FieldKind.Rollup or FieldKind.Computed)) return "ext";
        if (model.Fields.Any(f => f.Kind is FieldKind.Lookup)) return "full";
        return "none";
    }

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
