using System.Text;
using System.Text.Json;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Model;

/// <summary>
/// Renders a single M3L entity into the C# read/write entity pair described
/// in the design spec section 3.2: a marker interface <c>IXxx</c>, a write
/// class <c>Xxx : IyuEntity, IXxx</c> mapped to the base table, and a read
/// class <c>XxxExt : IyuEntity, IXxx</c> mapped to the view.
/// </summary>
/// <remarks>
/// The <c>id</c> field (attributed <c>@pk</c>) is elided because
/// <see cref="global::Iyu.Core.Entities.IyuEntity"/> already provides it. All
/// other stored fields are rendered on both classes and declared in the
/// interface — read-only for the interface contract, get/set for the classes.
/// <para>
/// C16 scope: stored fields only. Lookup/Rollup/Computed fields and enum
/// generation land in C17-C19.
/// </para>
/// </remarks>
public static class EntityPairRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public sealed record RenderedPair(string Interface, string Write, string Read);

    /// <summary>
    /// Which SQL view (if any) backs the Ext read model. Priority:
    /// <c>Ext</c> (user-maintained ExtView) &gt; <c>Full</c> (FullView) &gt;
    /// <c>Ud</c> (UdView) &gt; <c>None</c> (base table).
    /// </summary>
    public enum ExtBacking { None, Ud, Full, Ext }

    public static RenderedPair Render(
        ResolvedModel model,
        string ns,
        IReadOnlySet<string>? knownEnumNames = null,
        ExtBacking extBacking = ExtBacking.None)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var entityName = PascalCase(model.Name);

        // PK 지원 게이트 — IyuEntity.Id(Guid 단일 키)와 양립 불가한 모델은 조용히
        // 삼키지 않고 명시적으로 실패한다. (silent drop 금지 — 2026-07-22 이슈)
        var pkFields = model.Fields.Where(f => HasAttribute(f, "pk")).ToList();
        if (pkFields.Count > 1)
        {
            throw new InvalidOperationException(
                $"Model '{model.Name}': 복합 PK({string.Join(", ", pkFields.Select(f => f.Name))})는 " +
                "Model 타깃이 지원하지 않습니다. 단일 identifier PK로 모델링하세요.");
        }
        if (pkFields is [{ } pkField] && pkField.Type != "identifier")
        {
            throw new InvalidOperationException(
                $"Model '{model.Name}.{pkField.Name}': PK 타입 '{pkField.Type}'은 Model 타깃이 지원하지 " +
                "않습니다. 상속되는 IyuEntity.Id(Guid)와 양립하려면 identifier 타입이어야 합니다.");
        }

        // Stored fields (pk + created_at/updated_at elided — inherited from IyuEntity).
        // 비-id PK(공유 PK 확장 테이블)도 elide 대상 — 그 필드는 IyuEntity.Id가 표현하며,
        // DbContextRenderer가 fluent HasColumnName으로 실제 PK 컬럼에 재매핑한다.
        // Kind.Stored is the default; anything else (Lookup/Rollup/Computed) lives
        // on the Ext read model only.
        var storedFields = model.Fields
            .Where(f => f.Kind == FieldKind.Stored)
            .Where(f => !HasAttribute(f, "pk"))
            .Where(f => !IsInheritedTimestamp(f.Name))
            .ToList();

        var derivedFields = model.Fields
            .Where(f => f.Kind is FieldKind.Lookup or FieldKind.Rollup or FieldKind.Computed)
            .ToList();

        return new RenderedPair(
            Interface: RenderInterface(entityName, storedFields, ns, knownEnumNames),
            Write: RenderClass(entityName, storedFields, derivedFields: null, ns, isExt: false, knownEnumNames, extBacking, model.Source),
            Read: RenderClass(entityName, storedFields, derivedFields, ns, isExt: true, knownEnumNames, extBacking, model.Source));
    }

    private static string RenderInterface(string entityName, IReadOnlyList<FieldNode> fields, string ns, IReadOnlySet<string>? knownEnumNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("public interface I").Append(entityName).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    global::System.Guid Id { get; }");
        foreach (var f in fields)
        {
            var cs = CSharpTypeMapper.MapFieldType(f.Type!, knownEnumNames);
            var nullable = f.Nullable ? "?" : string.Empty;
            sb.Append("    ").Append(cs).Append(nullable).Append(' ')
              .Append(PascalCase(f.Name)).AppendLine(" { get; }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string RenderClass(
        string entityName,
        IReadOnlyList<FieldNode> storedFields,
        IReadOnlyList<FieldNode>? derivedFields,
        string ns,
        bool isExt,
        IReadOnlySet<string>? knownEnumNames,
        ExtBacking extBacking,
        ModelNode source)
    {
        var className = isExt ? entityName + "Ext" : entityName;
        // Ext classes route to the SQL layer that actually exposes their
        // derived columns: {Name}ExtView (rollup/computed), {Name}FullView (lookups
        // only), or the base table (table-only model). Write classes always
        // target the base table.
        var tableName = !isExt
            ? entityName
            : extBacking switch
            {
                ExtBacking.Ext => entityName + "ExtView",
                ExtBacking.Full => entityName + "FullView",
                ExtBacking.Ud => entityName + "UdView",
                _ => entityName,
            };

        // @implements 어트리뷰트에서 추가 인터페이스 추출 (도메인 중립 — 인자는
        // 완전수식명(FQN)을 verbatim 사용, mdd는 global:: 만 접두).
        var extraInterfaces = (source.Attributes ?? [])
            .Where(a => string.Equals(a.Name, "implements", StringComparison.OrdinalIgnoreCase))
            .SelectMany(a => a.Args ?? [])
            .Select(AttributeArgString)
            .Where(s => !string.IsNullOrEmpty(s))
            .Select(iface => $"global::{iface}")
            .ToList();

        // @inherits(FQN) — 기본 베이스클래스 IyuEntity 오버라이드 (도메인 중립).
        // 미지정 시 IyuEntity 유지(하위호환). 단일 인자(C# 단일 상속).
        var inheritsFqn = (source.Attributes ?? [])
            .Where(a => string.Equals(a.Name, "inherits", StringComparison.OrdinalIgnoreCase))
            .SelectMany(a => a.Args ?? [])
            .Select(AttributeArgString)
            .FirstOrDefault(s => !string.IsNullOrEmpty(s));
        var baseClass = string.IsNullOrEmpty(inheritsFqn)
            ? "global::Iyu.Core.Entities.IyuEntity"
            : $"global::{inheritsFqn}";

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("[Table(\"").Append(tableName).AppendLine("\")]");
        sb.Append("public partial class ").Append(className)
          .Append(" : ").Append(baseClass).Append(", I").Append(entityName);
        foreach (var iface in extraInterfaces)
            sb.Append(", ").Append(iface);
        sb.AppendLine();
        sb.AppendLine("{");
        // Build a map of stored FK field nullability so Lookup fields can
        // inherit the correct optionality from their FK path's first hop.
        // A lookup through a nullable FK produces NULL whenever the FK is NULL
        // (LEFT JOIN) and the generated C# property must reflect that.
        var storedNullability = BuildStoredNullabilityMap(storedFields);
        foreach (var f in storedFields)
        {
            RenderProperty(sb, f, knownEnumNames, storedNullability, isExt);
        }
        if (derivedFields is { Count: > 0 })
        {
            foreach (var f in derivedFields)
            {
                RenderProperty(sb, f, knownEnumNames, storedNullability, isExt);
            }
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void RenderProperty(
        StringBuilder sb,
        FieldNode f,
        IReadOnlySet<string>? knownEnumNames,
        IReadOnlyDictionary<string, bool>? storedNullability,
        bool isExt = false)
    {
        var cs = CSharpTypeMapper.MapFieldType(f.Type!, knownEnumNames);

        // Lookup fields inherit nullability from their FK path's first hop.
        // A @lookup(fk.col) through a nullable FK yields NULL whenever the FK
        // is NULL (LEFT JOIN). Propagate that to the generated C# type.
        var effectiveNullable = f.Nullable;
        if (f.Kind == FieldKind.Lookup && !effectiveNullable && storedNullability is not null)
        {
            var path = f.Lookup?.Path;
            if (!string.IsNullOrEmpty(path))
            {
                var dot = path.IndexOf('.');
                var fkName = dot > 0 ? path[..dot] : path;
                if (storedNullability.TryGetValue(fkName, out var fkNullable) && fkNullable)
                    effectiveNullable = true;
            }
        }

        var nullable = effectiveNullable ? "?" : string.Empty;
        var prop = PascalCase(f.Name);

        var isEnumField = knownEnumNames is not null && knownEnumNames.Contains(f.Type!);

        // Nullable reference/value types default to null — no initializer needed.
        // Non-nullable types: non-null reference types get an explicit default
        // (for nullable-reference analysis); value types (including enums)
        // auto-default to 0/false.
        var initializer = effectiveNullable || isEnumField
            ? string.Empty
            : CSharpTypeMapper.DefaultInitializer(f.Type!);

        // [Column(TypeName = "decimal(p,s)")] for decimal fields with explicit precision.
        // Suppresses EF Core's "No store type specified" warning and aligns the CLR
        // mapping with the SQL DECIMAL(p,s) column the SQL generator emits.
        if (f.Type == "decimal")
        {
            var decParams = ExtractFieldParams(f);
            if (decParams is { Count: >= 1 })
            {
                var scale = decParams.Count >= 2 ? decParams[1] : "0";
                sb.Append("    [Column(TypeName = \"decimal(")
                  .Append(decParams[0]).Append(',').Append(scale)
                  .AppendLine(")\")]");
            }
        }

        // Emit [Reference("Target")] for foreign-key properties.
        var referenceTarget = GetAttributeFirstParam(f, "reference");
        if (!string.IsNullOrEmpty(referenceTarget))
        {
            sb.Append("    [global::Iyu.Core.Attributes.Reference(\"")
              .Append(referenceTarget).AppendLine("\")]");
        }

        // [Binding("Entity", "Column")] — # Entity.Column 바인딩
        if (f.Binding is not null)
        {
            sb.Append("    [global::Iyu.Core.Attributes.Binding(\"")
              .Append(f.Binding.Entity).Append("\", \"")
              .Append(f.Binding.Column).AppendLine("\")]");
        }

        // Derived-field markers: [Lookup], [Rollup], [Computed].
        // The SQL view populates these; EF never writes them back.
        switch (f.Kind)
        {
            case FieldKind.Lookup:
                var lookupArg = GetAttributeFirstParam(f, "lookup")
                    ?? f.Lookup?.Path
                    ?? string.Empty;
                sb.Append("    [global::Iyu.Core.Attributes.Lookup(\"")
                  .Append(EscapeStringLiteral(lookupArg)).AppendLine("\")]");
                break;
            case FieldKind.Rollup:
                var rollupExpr = GetRollupExpression(f);
                sb.Append("    [global::Iyu.Core.Attributes.Rollup(\"")
                  .Append(EscapeStringLiteral(rollupExpr)).Append('"');
                if (HasAttribute(f, "indexed"))
                    sb.Append(", Indexed = true");
                sb.AppendLine(")]");
                break;
            case FieldKind.Computed:
                var computedExpr = GetAttributeFirstParam(f, "computed")
                    ?? f.Computed?.Expression
                    ?? string.Empty;
                // Strip surrounding backticks that M3L uses to fence expressions
                if (computedExpr.Length >= 2 && computedExpr.StartsWith('`') && computedExpr.EndsWith('`'))
                    computedExpr = computedExpr[1..^1];
                sb.Append("    [global::Iyu.Core.Attributes.Computed(\"")
                  .Append(EscapeStringLiteral(computedExpr)).AppendLine("\")]");
                break;
        }

        // [Display(Name, GroupName)] — field label and/or group from M3L declaration
        var displayLabel = f.Description;
        var displayGroup = GetAttributeString(f, "group");
        if (displayLabel != null || displayGroup != null)
        {
            sb.Append("    [Display(");
            var displayParts = new List<string>();
            if (displayLabel != null) displayParts.Add($"Name = \"{EscapeStringLiteral(displayLabel)}\"");
            if (displayGroup != null) displayParts.Add($"GroupName = \"{EscapeStringLiteral(displayGroup)}\"");
            sb.Append(string.Join(", ", displayParts));
            sb.AppendLine(")]");
        }

        sb.Append("    public ").Append(cs).Append(nullable).Append(' ')
          .Append(prop).Append(" { get; set; }").AppendLine(initializer);

        // Write entity only: emit EF Core navigation property for [Reference] FK fields
        // that follow the standard xxx_id naming convention.
        // EF Core uses nav properties to infer INSERT order; without them, bulk
        // SaveChanges calls with parent+child in the same batch produce FK violations.
        if (!isExt && !string.IsNullOrEmpty(referenceTarget)
            && f.Name.EndsWith("_id", StringComparison.OrdinalIgnoreCase))
        {
            var navName = NavPropertyName(f.Name);
            if (effectiveNullable)
                sb.Append("    public ").Append(referenceTarget).Append("? ")
                  .Append(navName).AppendLine(" { get; set; }");
            else
                sb.Append("    public ").Append(referenceTarget).Append(" ")
                  .Append(navName).AppendLine(" { get; set; } = null!;");
        }
    }

    /// <summary>
    /// Derives the EF Core navigation property name from a FK field name ending in <c>_id</c>.
    /// Strips the <c>_id</c> suffix and converts the remainder to PascalCase.
    /// For example <c>customer_id</c> → <c>Customer</c>,
    /// <c>channel_partner_id</c> → <c>ChannelPartner</c>.
    /// </summary>
    private static string NavPropertyName(string fkFieldName)
    {
        var name = fkFieldName.EndsWith("_id", StringComparison.OrdinalIgnoreCase)
            ? fkFieldName[..^3]
            : fkFieldName;
        return PascalCase(name);
    }

    private static IReadOnlyDictionary<string, bool> BuildStoredNullabilityMap(IReadOnlyList<FieldNode> storedFields)
    {
        var map = new Dictionary<string, bool>(StringComparer.Ordinal);
        foreach (var f in storedFields)
        {
            if (!string.IsNullOrEmpty(f.Name))
                map[f.Name] = f.Nullable;
        }
        return map;
    }

    private static string GetRollupExpression(FieldNode f)
    {
        // Prefer the structured RollupDef when present; fall back to joining
        // attribute args so hand-written fixtures without the parsed block
        // still round-trip.
        if (f.Rollup is not null)
        {
            var fkPart = string.IsNullOrEmpty(f.Rollup.Fk) ? f.Rollup.Target : $"{f.Rollup.Target}.{f.Rollup.Fk}";
            return string.IsNullOrEmpty(f.Rollup.Aggregate) ? fkPart : $"{fkPart}:{f.Rollup.Aggregate}";
        }
        var attr = MddBooster.Core.Ast.FieldAttributes.Find(f, "rollup");
        if (attr?.Args is { Count: > 0 })
        {
            return string.Join(":", attr.Args.Select(a =>
                a.ValueKind == System.Text.Json.JsonValueKind.String ? a.GetString() : a.GetRawText()));
        }
        return string.Empty;
    }

    private static IReadOnlyList<string>? ExtractFieldParams(FieldNode field)
    {
        if (field.Params is null || field.Params.Count == 0) return null;
        var result = new List<string>(field.Params.Count);
        foreach (var p in field.Params)
        {
            if (p.ValueKind == JsonValueKind.Number)
            {
                if (p.TryGetDouble(out var d) && d == Math.Floor(d) && !double.IsInfinity(d))
                    result.Add(((long)d).ToString());
                else
                    result.Add(p.GetRawText());
            }
            else if (p.ValueKind == JsonValueKind.String)
                result.Add(p.GetString() ?? string.Empty);
            else
                result.Add(p.GetRawText());
        }
        return result;
    }

    private static string EscapeStringLiteral(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string? GetAttributeFirstParam(FieldNode field, string name)
    {
        var attr = MddBooster.Core.Ast.FieldAttributes.Find(field, name);
        if (attr?.Args is null || attr.Args.Count == 0) return null;
        var first = attr.Args[0];
        return first.ValueKind == System.Text.Json.JsonValueKind.String
            ? first.GetString()
            : first.GetRawText();
    }

    private static string? GetAttributeString(FieldNode field, string attrName)
    {
        var attr = MddBooster.Core.Ast.FieldAttributes.Find(field, attrName);
        if (attr?.Args is { Count: > 0 }
            && attr.Args[0].ValueKind == System.Text.Json.JsonValueKind.String)
        {
            return attr.Args[0].GetString();
        }
        return null;
    }

    /// <summary>
    /// Extracts a model-attribute argument as a plain string, unwrapping JSON
    /// string values and stripping quotes from raw tokens. Used by the
    /// domain-neutral <c>@implements</c>/<c>@inherits</c> knobs where the
    /// argument is a verbatim fully-qualified type name.
    /// </summary>
    private static string AttributeArgString(JsonElement arg) =>
        arg.ValueKind == JsonValueKind.String
            ? arg.GetString()!
            : arg.GetRawText().Trim('"');

    private static bool HasAttribute(FieldNode field, string name) =>
        MddBooster.Core.Ast.FieldAttributes.Has(field, name);

    private static bool IsInheritedTimestamp(string fieldName) =>
        string.Equals(fieldName, "created_at", StringComparison.OrdinalIgnoreCase)
        || string.Equals(fieldName, "updated_at", StringComparison.OrdinalIgnoreCase);

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
