using System.Text;
using System.Text.Json;
using M3L.Native;
using MddBooster.Core.Generation;
using MddBooster.Core.Semantic;
using MddBooster.Core.Naming;

namespace MddBooster.Generators.Model;

/// <summary>
/// Renders a single M3L entity into the C# read/write entity pair described
/// in the design spec section 3.2: a marker interface <c>IXxx</c>, a write
/// class <c>Xxx : IyuEntity, IXxx</c> mapped to the base table, and a read
/// class <c>XxxExt : IyuEntity, IXxx</c> mapped to the view.
/// </summary>
/// <remarks>
/// The <c>id</c> field (attributed <c>@pk</c>) is elided because
/// <see cref="IyuEntity"/> already provides it. All
/// other stored fields are rendered on both classes and declared in the
/// interface — read-only for the interface contract, get/set for the classes.
/// <para>
/// C16 scope: stored fields only. Lookup/Rollup/Computed fields and enum
/// generation land in C17-C19.
/// </para>
/// </remarks>
public static class EntityPairRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public sealed record RenderedPair(string Interface, string Write, string Read);

    /// <summary>
    /// Which SQL view (if any) backs the Ext read model. Priority:
    /// <c>Ext</c> (user-maintained ExtView) &gt; <c>Full</c> (FullView) &gt;
    /// <c>Ud</c> (UdView) &gt; <c>None</c> (base table).
    /// </summary>
    public enum ExtBacking { None, Ud, Full, Ext }

    public static RenderedPair Render(
        ResolvedModel model,
        string ns,
        IReadOnlySet<string>? knownEnumNames = null,
        ExtBacking extBacking = ExtBacking.None)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var entityName = NameCasing.ToPascalCase(model.Name);

        // PK 지원 게이트 — IyuEntity.Id(Guid 단일 키)와 양립 불가한 모델은 조용히
        // 삼키지 않고 명시적으로 실패한다. (silent drop 금지 — 2026-07-22 이슈)
        var pkFields = model.Fields.Where(f => HasAttribute(f, "pk")).ToList();
        if (pkFields.Count > 1)
        {
            throw new InvalidOperationException(
                $"Model '{model.Name}': 복합 PK({string.Join(", ", pkFields.Select(f => f.Name))})는 " +
                "Model 타깃이 지원하지 않습니다. 단일 identifier PK로 모델링하세요.");
        }
        if (pkFields is [{ } pkField] && pkField.Type != "identifier")
        {
            throw new InvalidOperationException(
                $"Model '{model.Name}.{pkField.Name}': PK 타입 '{pkField.Type}'은 Model 타깃이 지원하지 " +
                "않습니다. 상속되는 IyuEntity.Id(Guid)와 양립하려면 identifier 타입이어야 합니다.");
        }

        // Stored fields (pk + created_at/updated_at elided — inherited from IyuEntity).
        // 비-id PK(공유 PK 확장 테이블)도 elide 대상 — 그 필드는 IyuEntity.Id가 표현하며,
        // DbContextRenderer가 fluent HasColumnName으로 실제 PK 컬럼에 재매핑한다.
        // Kind.Stored is the default; anything else (Lookup/Rollup/Computed) lives
        // on the Ext read model only.
        var storedFields = model.Fields
            .Where(f => f.Kind == FieldKind.Stored)
            .Where(f => !HasAttribute(f, "pk"))
            .Where(f => !IsInheritedTimestamp(f.Name))
            .ToList();

        var derivedFields = model.Fields
            .Where(f => f.Kind is FieldKind.Lookup or FieldKind.Rollup or FieldKind.Computed)
            .ToList();

        // A field-level @internal field stays on the base table and the write entity
        // (storage), but drops out of the read surface — the interface both classes
        // implement, and the Ext (read) class itself. Dropping it from the interface is
        // not optional: XxxExt still has to compile against IXxx, so IXxx cannot declare
        // a member the Ext class no longer has.
        var readOnlyStoredFields = storedFields.Where(f => !EntitySurface.IsFieldInternal(f)).ToList();
        var readOnlyDerivedFields = derivedFields.Where(f => !EntitySurface.IsFieldInternal(f)).ToList();

        return new RenderedPair(
            Interface: RenderInterface(entityName, readOnlyStoredFields, ns, knownEnumNames),
            Write: RenderClass(entityName, storedFields, derivedFields: null, ns, isExt: false, knownEnumNames, extBacking, model.Source),
            Read: RenderClass(entityName, readOnlyStoredFields, readOnlyDerivedFields, ns, isExt: true, knownEnumNames, extBacking, model.Source));
    }

    private static string RenderInterface(string entityName, IReadOnlyList<FieldNode> fields, string ns, IReadOnlySet<string>? knownEnumNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("public interface I").Append(entityName).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    global::System.Guid Id { get; }");
        foreach (var f in fields)
        {
            var cs = CSharpTypeMapper.MapFieldType(f.Type!, knownEnumNames);
            var nullable = f.Nullable ? "?" : string.Empty;
            sb.Append("    ").Append(cs).Append(nullable).Append(' ')
              .Append(NameCasing.ToPascalCase(f.Name)).AppendLine(" { get; }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string RenderClass(
        string entityName,
        IReadOnlyList<FieldNode> storedFields,
        IReadOnlyList<FieldNode>? derivedFields,
        string ns,
        bool isExt,
        IReadOnlySet<string>? knownEnumNames,
        ExtBacking extBacking,
        ModelNode source)
    {
        var className = isExt ? entityName + "Ext" : entityName;
        // Ext classes route to the SQL layer that actually exposes their
        // derived columns: {Name}ExtView (rollup/computed), {Name}FullView (lookups
        // only), or the base table (table-only model). Write classes always
        // target the base table.
        var tableName = !isExt
            ? entityName
            : extBacking switch
            {
                ExtBacking.Ext => entityName + "ExtView",
                ExtBacking.Full => entityName + "FullView",
                ExtBacking.Ud => entityName + "UdView",
                _ => entityName,
            };

        // @implements 어트리뷰트에서 추가 인터페이스 추출 (도메인 중립 — 인자는
        // 완전수식명(FQN)을 verbatim 사용, mdd는 global:: 만 접두).
        var extraInterfaces = (source.Attributes ?? [])
            .Where(a => string.Equals(a.Name, "implements", StringComparison.OrdinalIgnoreCase))
            .SelectMany(a => a.Args ?? [])
            .Select(AttributeArgString)
            .Where(s => !string.IsNullOrEmpty(s))
            .Select(iface => $"global::{iface}")
            .ToList();

        // @inherits(FQN) — 기본 베이스클래스 IyuEntity 오버라이드 (도메인 중립).
        // 미지정 시 IyuEntity 유지(하위호환). 단일 인자(C# 단일 상속).
        var inheritsFqn = (source.Attributes ?? [])
            .Where(a => string.Equals(a.Name, "inherits", StringComparison.OrdinalIgnoreCase))
            .SelectMany(a => a.Args ?? [])
            .Select(AttributeArgString)
            .FirstOrDefault(s => !string.IsNullOrEmpty(s));
        var baseClass = string.IsNullOrEmpty(inheritsFqn)
            ? "IyuEntity"
            : $"global::{inheritsFqn}";

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("[Table(\"").Append(tableName).AppendLine("\")]");
        sb.Append("public partial class ").Append(className)
          .Append(" : ").Append(baseClass).Append(", I").Append(entityName);
        foreach (var iface in extraInterfaces)
            sb.Append(", ").Append(iface);
        sb.AppendLine();
        sb.AppendLine("{");
        // Build a map of stored FK field nullability so Lookup fields can
        // inherit the correct optionality from their FK path's first hop.
        // A lookup through a nullable FK produces NULL whenever the FK is NULL
        // (LEFT JOIN) and the generated C# property must reflect that.
        var storedNullability = BuildStoredNullabilityMap(storedFields);
        foreach (var f in storedFields)
        {
            RenderProperty(sb, f, knownEnumNames, storedNullability, isExt);
        }
        if (derivedFields is { Count: > 0 })
        {
            foreach (var f in derivedFields)
            {
                RenderProperty(sb, f, knownEnumNames, storedNullability, isExt);
            }
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void RenderProperty(
        StringBuilder sb,
        FieldNode f,
        IReadOnlySet<string>? knownEnumNames,
        IReadOnlyDictionary<string, bool>? storedNullability,
        bool isExt = false)
    {
        var cs = CSharpTypeMapper.MapFieldType(f.Type!, knownEnumNames);

        // Lookup fields inherit nullability from their FK path's first hop.
        // A @lookup(fk.col) through a nullable FK yields NULL whenever the FK
        // is NULL (LEFT JOIN). Propagate that to the generated C# type.
        var effectiveNullable = f.Nullable;
        if (f.Kind == FieldKind.Lookup && !effectiveNullable && storedNullability is not null)
        {
            var path = f.Lookup?.Path;
            if (!string.IsNullOrEmpty(path))
            {
                var dot = path.IndexOf('.');
                var fkName = dot > 0 ? path[..dot] : path;
                if (storedNullability.TryGetValue(fkName, out var fkNullable) && fkNullable)
                    effectiveNullable = true;
            }
        }

        var nullable = effectiveNullable ? "?" : string.Empty;
        var prop = NameCasing.ToPascalCase(f.Name);

        var isEnumField = knownEnumNames is not null && knownEnumNames.Contains(f.Type!);

        // A declared default (`= value`) is the property's initializer when the
        // field has one. Without this the CLR default is stored silently: EF
        // writes the zero value explicitly, so the column's DDL DEFAULT never
        // gets the chance to fire and `boolean = true` lands as false.
        // Nullable fields are excluded on purpose — seeding an optional property
        // changes what "unset" means, which is a separate trade-off.
        var declaredInitializer = !effectiveNullable && f.Kind == FieldKind.Stored
            ? DeclaredDefaultInitializer(f, knownEnumNames)
            : null;

        // Otherwise: nullable reference/value types default to null — no
        // initializer needed. Non-nullable types: non-null reference types get an
        // explicit default (for nullable-reference analysis); value types
        // (including enums) auto-default to 0/false.
        var initializer = declaredInitializer
            ?? (effectiveNullable || isEnumField
                ? string.Empty
                : CSharpTypeMapper.DefaultInitializer(f.Type!));

        // [Column(TypeName = "decimal(p,s)")] for decimal fields with explicit precision.
        // Suppresses EF Core's "No store type specified" warning and aligns the CLR
        // mapping with the SQL DECIMAL(p,s) column the SQL generator emits.
        if (f.Type == "decimal")
        {
            var decParams = MddBooster.Core.Ast.FieldAttributes.TypeParams(f);
            if (decParams is { Count: >= 1 })
            {
                var scale = decParams.Count >= 2 ? decParams[1] : "0";
                sb.Append("    [Column(TypeName = \"decimal(")
                  .Append(decParams[0]).Append(',').Append(scale)
                  .AppendLine(")\")]");
            }
        }

        // Emit [Reference("Target")] for foreign-key properties.
        var referenceTarget = GetAttributeFirstParam(f, "reference");
        if (!string.IsNullOrEmpty(referenceTarget))
        {
            sb.Append("    [Reference(\"")
              .Append(referenceTarget).AppendLine("\")]");
        }

        // [Binding("Entity", "Column")] — # Entity.Column 바인딩
        if (f.Binding is not null)
        {
            sb.Append("    [Binding(\"")
              .Append(f.Binding.Entity).Append("\", \"")
              .Append(f.Binding.Column).AppendLine("\")]");
        }

        // Derived-field markers: [Lookup], [Rollup], [Computed].
        // The SQL view populates these; EF never writes them back.
        switch (f.Kind)
        {
            case FieldKind.Lookup:
                var lookupArg = GetAttributeFirstParam(f, "lookup")
                    ?? f.Lookup?.Path
                    ?? string.Empty;
                sb.Append("    [Lookup(\"")
                  .Append(EscapeStringLiteral(lookupArg)).AppendLine("\")]");
                break;
            case FieldKind.Rollup:
                var rollupExpr = GetRollupExpression(f);
                sb.Append("    [Rollup(\"")
                  .Append(EscapeStringLiteral(rollupExpr)).Append('"');
                if (HasAttribute(f, "indexed"))
                    sb.Append(", Indexed = true");
                sb.AppendLine(")]");
                break;
            case FieldKind.Computed:
                var computedExpr = GetAttributeFirstParam(f, "computed")
                    ?? f.Computed?.Expression
                    ?? string.Empty;
                // Strip surrounding backticks that M3L uses to fence expressions
                if (computedExpr.Length >= 2 && computedExpr.StartsWith('`') && computedExpr.EndsWith('`'))
                    computedExpr = computedExpr[1..^1];
                sb.Append("    [Computed(\"")
                  .Append(EscapeStringLiteral(computedExpr)).AppendLine("\")]");
                break;
        }

        // Validation attributes — the constraints the model already declares,
        // carried to the C# entity so the API surface enforces them instead of
        // letting a violation reach the database and come back as a raw provider
        // error. They read the same sources the SQL column does — field
        // nullability, and the field's effective length bound — so the two
        // targets cannot drift.
        //
        // Stored fields only: Lookup/Rollup/Computed properties are populated by
        // the view and a caller never supplies them. `[Required]` on one would
        // reject every create request, because a non-nullable derived string
        // carries the `string.Empty` initializer that RequiredAttribute rejects.
        if (f.Kind == FieldKind.Stored)
        {
            // [Required] — non-nullable reference types only. Nullability comes
            // from the parsed flag, not from the `@not_null` attribute: a plain
            // `- name: string(50)` is already non-nullable, and the SQL column's
            // NOT NULL is derived the same way.
            if (!f.Nullable && CSharpTypeMapper.IsReferenceType(f.Type!))
                sb.AppendLine("    [Required]");

            // [StringLength(n)] — the bound the field actually carries, which is
            // the number the SQL column is sized with. A bound can be written
            // down (`string(50)`) or implied by the type (`email`); reading only
            // the written one is how a column came to be narrower than the
            // attribute guarding writes to it. Independent of nullability: an
            // optional `string(50)?` is still bounded at 50.
            if (MddBooster.Core.Ast.FieldAttributes.EffectiveMaxLength(f) is { } maxLength)
                sb.Append("    [StringLength(").Append(maxLength).AppendLine(")]");

            // [Editable(false)] — mirrors TS's `disabled` (TsFormRenderer, cycle-91).
            // Metadata only, like [Required]/[StringLength] above: nothing in this
            // repo's generated API layer enforces it. An actual write-blocking
            // guard is docket #42's separate, still-open request.
            if (MddBooster.Core.Ast.FieldAttributes.Has(f, "immutable"))
                sb.AppendLine("    [Editable(false)]");
        }

        // [Display(Name, GroupName, Description)] — field label/group/help from M3L declaration.
        // @label(text) overrides the description; unlike FieldAttributes.EffectiveLabel this
        // does NOT fall back to the PascalCase field name — presence of Name here signals
        // authored, meaningful text (No_Display_when_field_has_no_label_or_group pins the
        // alternative: omit [Display] entirely rather than restate the property's own name).
        // @help(text) maps to Description — the same free-text field TsFormRenderer's helpText
        // already reads, so this mirrors an existing, established mapping rather than inventing one.
        var displayLabel = GetAttributeFirstParam(f, "label") ?? f.Description;
        var displayGroup = GetAttributeString(f, "group");
        var displayHelp = GetAttributeString(f, "help");
        if (displayLabel != null || displayGroup != null || displayHelp != null)
        {
            sb.Append("    [Display(");
            var displayParts = new List<string>();
            if (displayLabel != null) displayParts.Add($"Name = \"{EscapeStringLiteral(displayLabel)}\"");
            if (displayGroup != null) displayParts.Add($"GroupName = \"{EscapeStringLiteral(displayGroup)}\"");
            if (displayHelp != null) displayParts.Add($"Description = \"{EscapeStringLiteral(displayHelp)}\"");
            sb.Append(string.Join(", ", displayParts));
            sb.AppendLine(")]");
        }

        sb.Append("    public ").Append(cs).Append(nullable).Append(' ')
          .Append(prop).Append(" { get; set; }").AppendLine(initializer);

        // Write entity only: emit EF Core navigation property for [Reference] FK fields
        // that follow the standard xxx_id naming convention.
        // EF Core uses nav properties to infer INSERT order; without them, bulk
        // SaveChanges calls with parent+child in the same batch produce FK violations.
        if (!isExt && !string.IsNullOrEmpty(referenceTarget)
            && f.Name.EndsWith("_id", StringComparison.OrdinalIgnoreCase))
        {
            var navName = NavPropertyName(f.Name);
            if (effectiveNullable)
                sb.Append("    public ").Append(referenceTarget).Append("? ")
                  .Append(navName).AppendLine(" { get; set; }");
            else
                sb.Append("    public ").Append(referenceTarget).Append(" ")
                  .Append(navName).AppendLine(" { get; set; } = null!;");
        }
    }

    /// <summary>
    /// Derives the EF Core navigation property name from a FK field name ending in <c>_id</c>.
    /// Strips the <c>_id</c> suffix and converts the remainder to PascalCase.
    /// For example <c>customer_id</c> → <c>Customer</c>,
    /// <c>channel_partner_id</c> → <c>ChannelPartner</c>.
    /// </summary>
    private static string NavPropertyName(string fkFieldName)
    {
        var name = fkFieldName.EndsWith("_id", StringComparison.OrdinalIgnoreCase)
            ? fkFieldName[..^3]
            : fkFieldName;
        return NameCasing.ToPascalCase(name);
    }

    /// <summary>
    /// Turns a declared default (<c>= value</c>, or the <c>@default(value)</c>
    /// spelling) into a C# property initializer, or <c>null</c> when the default
    /// cannot be expressed as a literal.
    /// </summary>
    /// <remarks>
    /// The gate is the <em>target type</em>, not the shape of the default text.
    /// Only types with a C# literal form are emitted; temporals,
    /// <c>identifier</c> and <c>binary</c> are skipped whatever their default
    /// says. Server-side defaults such as <c>now()</c> therefore fall out as a
    /// consequence rather than as named exceptions — a list of function names
    /// would let the next one through and emit code that does not compile.
    /// </remarks>
    private static string? DeclaredDefaultInitializer(FieldNode f, IReadOnlySet<string>? knownEnumNames)
    {
        var raw = MddBooster.Core.Ast.FieldAttributes.EffectiveDefault(f);
        if (string.IsNullOrEmpty(raw)) return null;

        var type = f.Type!;

        // Enum defaults arrive as the bare snake_case member name (the parser
        // strips the quotes). The member expression has to use the same
        // PascalCase conversion EnumRenderer applies, or it names a member that
        // was never generated.
        if (knownEnumNames is not null && knownEnumNames.Contains(type))
            return $" = {NameCasing.ToPascalCase(type)}.{NameCasing.ToPascalCase(raw)};";

        return type switch
        {
            "boolean" => raw is "true" or "false" ? $" = {raw};" : null,
            "integer" or "long" or "short" or "byte" => IsIntegerLiteral(raw) ? $" = {raw};" : null,
            // An unsuffixed literal is a double: assigning it to float or decimal
            // is CS0664, so both need their suffix.
            "float" => IsNumericLiteral(raw) ? $" = {raw}f;" : null,
            "double" => IsNumericLiteral(raw) ? $" = {raw};" : null,
            "decimal" => IsNumericLiteral(raw) ? $" = {raw}m;" : null,
            "string" or "text" or "json" or "phone" or "email" or "url"
                => $" = \"{EscapeStringLiteral(raw)}\";",
            // date/time/timestamp/datetime/identifier/binary have no literal form.
            _ => null,
        };
    }

    private static bool IsIntegerLiteral(string s) =>
        long.TryParse(s, System.Globalization.NumberStyles.Integer,
            System.Globalization.CultureInfo.InvariantCulture, out _);

    private static bool IsNumericLiteral(string s) =>
        double.TryParse(s, System.Globalization.NumberStyles.Float,
            System.Globalization.CultureInfo.InvariantCulture, out _);

    private static IReadOnlyDictionary<string, bool> BuildStoredNullabilityMap(IReadOnlyList<FieldNode> storedFields)
    {
        var map = new Dictionary<string, bool>(StringComparer.Ordinal);
        foreach (var f in storedFields)
        {
            if (!string.IsNullOrEmpty(f.Name))
                map[f.Name] = f.Nullable;
        }
        return map;
    }

    private static string GetRollupExpression(FieldNode f)
    {
        // Prefer the structured RollupDef when present; fall back to joining
        // attribute args so hand-written fixtures without the parsed block
        // still round-trip.
        if (f.Rollup is not null)
        {
            var fkPart = string.IsNullOrEmpty(f.Rollup.Fk) ? f.Rollup.Target : $"{f.Rollup.Target}.{f.Rollup.Fk}";
            return string.IsNullOrEmpty(f.Rollup.Aggregate) ? fkPart : $"{fkPart}:{f.Rollup.Aggregate}";
        }
        var attr = MddBooster.Core.Ast.FieldAttributes.Find(f, "rollup");
        if (attr?.Args is { Count: > 0 })
        {
            return string.Join(":", attr.Args.Select(a =>
                a.ValueKind == System.Text.Json.JsonValueKind.String ? a.GetString() : a.GetRawText()));
        }
        return string.Empty;
    }

    private static string EscapeStringLiteral(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string? GetAttributeFirstParam(FieldNode field, string name)
    {
        var attr = MddBooster.Core.Ast.FieldAttributes.Find(field, name);
        if (attr?.Args is null || attr.Args.Count == 0) return null;
        var first = attr.Args[0];
        return first.ValueKind == System.Text.Json.JsonValueKind.String
            ? first.GetString()
            : first.GetRawText();
    }

    private static string? GetAttributeString(FieldNode field, string attrName)
    {
        var attr = MddBooster.Core.Ast.FieldAttributes.Find(field, attrName);
        if (attr?.Args is { Count: > 0 }
            && attr.Args[0].ValueKind == System.Text.Json.JsonValueKind.String)
        {
            return attr.Args[0].GetString();
        }
        return null;
    }

    /// <summary>
    /// Extracts a model-attribute argument as a plain string, unwrapping JSON
    /// string values and stripping quotes from raw tokens. Used by the
    /// domain-neutral <c>@implements</c>/<c>@inherits</c> knobs where the
    /// argument is a verbatim fully-qualified type name.
    /// </summary>
    private static string AttributeArgString(JsonElement arg) =>
        arg.ValueKind == JsonValueKind.String
            ? arg.GetString()!
            : arg.GetRawText().Trim('"');

    private static bool HasAttribute(FieldNode field, string name) =>
        MddBooster.Core.Ast.FieldAttributes.Has(field, name);

    private static bool IsInheritedTimestamp(string fieldName) =>
        string.Equals(fieldName, "created_at", StringComparison.OrdinalIgnoreCase)
        || string.Equals(fieldName, "updated_at", StringComparison.OrdinalIgnoreCase);

}
