using System.Text;
using M3L.Native;

namespace MddBooster.Generators.Model;

/// <summary>
/// Renders an M3L top-level enum declaration (<c>## Name ::enum</c>) into a
/// C# enum type with <c>[EnumMember]</c> attributes that carry the original
/// snake_case value names. The snake_case form is what EF Core persists via
/// <c>HasConversion&lt;string&gt;()</c> and what the SQL generator's CHECK
/// constraint enforces, so the two sides stay in lock-step.
/// </summary>
/// <remarks>
/// <para>
/// M3L enum members use snake_case (<c>in_production</c>); the generated C#
/// member is PascalCase (<c>InProduction</c>) with an explicit
/// <c>[EnumMember(Value = "in_production")]</c> attribute so that JSON
/// serialization and the string value converter both round-trip through the
/// M3L name.
/// </para>
/// <para>
/// The enum's XML doc comment carries the M3L enum description (if any) and
/// each member's doc comment carries the value label for tooling surfaces
/// (IntelliSense, GraphQL schema docs).
/// </para>
/// </remarks>
public static class EnumRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string Render(EnumNode enumNode, string ns)
    {
        ArgumentNullException.ThrowIfNull(enumNode);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var typeName = PascalCase(enumNode.Name);
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.Serialization;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(enumNode.Description))
        {
            sb.AppendLine("/// <summary>");
            sb.Append("/// ").AppendLine(EscapeXmlDoc(enumNode.Description!));
            sb.AppendLine("/// </summary>");
        }

        sb.Append("public enum ").AppendLine(typeName);
        sb.AppendLine("{");

        for (var i = 0; i < enumNode.Values.Count; i++)
        {
            var v = enumNode.Values[i];
            var memberName = PascalCase(v.Name);

            if (!string.IsNullOrWhiteSpace(v.Description))
            {
                sb.AppendLine("    /// <summary>");
                sb.Append("    /// ").AppendLine(EscapeXmlDoc(v.Description!));
                sb.AppendLine("    /// </summary>");
            }
            sb.Append("    [EnumMember(Value = \"").Append(EscapeString(v.Name)).AppendLine("\")]");
            sb.Append("    ").Append(memberName);
            sb.AppendLine(i < enumNode.Values.Count - 1 ? "," : string.Empty);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Concatenates the comma-separated SQL literal list used for the
    /// <c>CHECK ([Col] IN (N'a', N'b', ...))</c> constraint emitted by the
    /// SQL generator. Exposed here so both generators share the same value
    /// serialization convention.
    /// </summary>
    public static string RenderSqlCheckValues(EnumNode enumNode)
    {
        ArgumentNullException.ThrowIfNull(enumNode);
        return string.Join(", ",
            enumNode.Values.Select(v => "N'" + (v.Name?.Replace("'", "''") ?? string.Empty) + "'"));
    }

    /// <summary>
    /// Longest enum value name in characters — used to pick an NVARCHAR length
    /// for enum columns. A small safety margin is added so late-stage value
    /// additions don't require a column resize.
    /// </summary>
    public static int MaxValueLength(EnumNode enumNode)
    {
        ArgumentNullException.ThrowIfNull(enumNode);
        return enumNode.Values.Count == 0 ? 20 : enumNode.Values.Max(v => (v.Name ?? string.Empty).Length);
    }

    private static string EscapeString(string? s) => (s ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
