using System.Text;
using M3L.Native;

namespace MddBooster.Generators.Model;

/// <summary>
/// Renders an M3L top-level enum declaration (<c>## Name ::enum</c>) into a
/// C# enum type with <c>[EnumMember]</c> attributes that carry the original
/// snake_case value names. The snake_case form is what EF Core persists via
/// <c>HasConversion&lt;string&gt;()</c> — and, when the SQL target's opt-in
/// <c>EmitEnumCheckConstraints</c> knob is on, what the generated CHECK
/// constraint enforces (see <c>EnumSqlConvention</c> in the SQL generator).
/// DB-level enforcement is otherwise absent by design (SSDT dacpac CHECK diff
/// instability); EF-level conversion is then the only guard.
/// </summary>
/// <remarks>
/// <para>
/// M3L enum members use snake_case (<c>in_production</c>); the generated C#
/// member is PascalCase (<c>InProduction</c>) with an explicit
/// <c>[EnumMember(Value = "in_production")]</c> attribute so that JSON
/// serialization and the string value converter both round-trip through the
/// M3L name.
/// </para>
/// <para>
/// The enum's XML doc comment carries the M3L enum description (if any) and
/// each member's doc comment carries the value label for tooling surfaces
/// (IntelliSense, GraphQL schema docs).
/// </para>
/// </remarks>
public static class EnumRenderer
{
    private const string Header = "// <auto-generated> mdd-booster; DO NOT EDIT.</auto-generated>";

    public static string Render(EnumNode enumNode, string ns)
    {
        ArgumentNullException.ThrowIfNull(enumNode);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);

        var typeName = PascalCase(enumNode.Name);
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.Serialization;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(enumNode.Description))
        {
            sb.AppendLine("/// <summary>");
            AppendXmlDocLines(sb, enumNode.Description!, indent: "");
            sb.AppendLine("/// </summary>");
        }

        sb.Append("public enum ").AppendLine(typeName);
        sb.AppendLine("{");

        for (var i = 0; i < enumNode.Values.Count; i++)
        {
            var v = enumNode.Values[i];
            var memberName = PascalCase(v.Name);

            if (!string.IsNullOrWhiteSpace(v.Description))
            {
                sb.AppendLine("    /// <summary>");
                AppendXmlDocLines(sb, v.Description!, indent: "    ");
                sb.AppendLine("    /// </summary>");
            }
            sb.Append("    [EnumMember(Value = \"").Append(EscapeString(v.Name)).AppendLine("\")]");
            sb.Append("    ").Append(memberName);
            sb.AppendLine(i < enumNode.Values.Count - 1 ? "," : string.Empty);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeString(string? s) => (s ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string EscapeXmlDoc(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// <summary>
    /// description 멀티라인 처리 — 줄별로 <c>/// </c> prefix를 붙여 emit.
    /// 단일 라인은 한 줄 emit, 줄바꿈(\n / \r\n)이 있으면 각 줄에 prefix가 붙는다.
    /// 멀티라인을 일괄 emit 시 둘째 줄 이후에 <c>/// </c>가 누락되어 C# 컴파일 에러가 나는 회귀 차단.
    /// </summary>
    private static void AppendXmlDocLines(StringBuilder sb, string description, string indent)
    {
        var lines = description.Replace("\r\n", "\n").Split('\n');
        foreach (var line in lines)
        {
            sb.Append(indent).Append("/// ").AppendLine(EscapeXmlDoc(line));
        }
    }

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
