using System.Text;
using System.Text.RegularExpressions;
using M3L.Native;

namespace MddBooster.Generators.Sql;

/// <summary>
/// Renders the <c>{Name}_ext</c> SQL view layered on top of the full view
/// (or directly on the base table when no lookups exist). The ext view
/// projects every column from its source and adds correlated rollup
/// subqueries and computed column expressions.
/// </summary>
/// <remarks>
/// <para>
/// <b>Rollup</b>: an <c>@rollup(OrderItem.order_id, count)</c> becomes
/// <c>(SELECT COUNT(*) FROM [dbo].[OrderItem] WHERE [OrderId] = b.[Id])</c>.
/// The aggregate string follows the M3L convention: <c>count</c>,
/// <c>sum(col)</c>, <c>avg(col)</c>, <c>min(col)</c>, <c>max(col)</c>.
/// For numeric aggregates on possibly-empty sets we wrap in ISNULL(…, 0)
/// so read models never surface NULL where they declared non-nullable.
/// </para>
/// <para>
/// <b>Computed</b>: the M3L expression (already unwrapped from its M3L
/// backticks by the Model renderer) is emitted after running through
/// <see cref="NormalizeComputedExpression"/>. Because SQL Server does NOT
/// allow a SELECT list alias to be referenced by a sibling alias in the
/// same SELECT, each computed field is placed in its OWN CTE layer on top
/// of the rollup layer. That way <c>grand_total = supply_total + vat_amount</c>
/// can reference prior aliases as ordinary columns of the enclosing CTE.
/// </para>
/// <para>
/// <b>Indexed view opt-in</b>: if any rollup field carries <c>@indexed</c>,
/// the rendered view is prefixed with <c>WITH SCHEMABINDING</c> so the
/// downstream <c>CREATE UNIQUE CLUSTERED INDEX</c> can be authored by
/// hand (the schema index itself is not emitted here — that decision
/// belongs to the DBA and belongs in the <c>Views/</c> hand-maintained
/// folder per the design spec).
/// </para>
/// </remarks>
public static class ExtViewRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(ViewPlan plan, string schema, IReadOnlySet<string>? extViewModels = null)
    {
        ArgumentNullException.ThrowIfNull(plan);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);
        if (!plan.NeedsExtView)
            throw new InvalidOperationException($"Model '{plan.Model.Name}' does not need an ext view.");

        var baseName = plan.Model.Name;
        var viewName = baseName + "_ext";
        // Source is the full view when one exists, otherwise the base table.
        var sourceTable = plan.NeedsFullView ? baseName + "_full" : baseName;
        const string baseAlias = "b";

        var hasIndexed = plan.Rollups.Any(r => r.Attributes.Any(a =>
            string.Equals(a.Name, "indexed", StringComparison.OrdinalIgnoreCase)));

        // Rollups land in one CTE layer; each computed goes into its own
        // subsequent CTE layer so it may reference any column produced by a
        // previous layer (SQL Server forbids same-SELECT alias siblings).
        var rollupProjections = new List<(string expr, string alias)>();
        foreach (var rollup in plan.Rollups)
        {
            var def = rollup.Rollup
                ?? throw new InvalidOperationException(
                    $"Rollup field '{plan.Model.Name}.{rollup.Name}' has no parsed RollupDef.");
            rollupProjections.Add((
                expr: RenderRollupSubquery(def, schema, baseAlias, extViewModels),
                alias: ToPascalCase(rollup.Name)));
        }

        var computedProjections = new List<(string expr, string alias)>();
        foreach (var computed in plan.Computeds)
        {
            var def = computed.Computed
                ?? throw new InvalidOperationException(
                    $"Computed field '{plan.Model.Name}.{computed.Name}' has no parsed ComputedDef.");
            var expr = NormalizeComputedExpression(def.Expression ?? string.Empty);
            computedProjections.Add((expr: expr, alias: ToPascalCase(computed.Name)));
        }

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE VIEW [").Append(schema).Append("].[").Append(viewName).Append(']');
        if (hasIndexed) sb.Append(" WITH SCHEMABINDING");
        sb.AppendLine();
        sb.AppendLine("AS");

        // Single-layer fast path: only rollups (no computeds) → no alias
        // self-reference hazard, keep the simpler flat SELECT.
        if (computedProjections.Count == 0)
        {
            sb.Append("SELECT ").Append(baseAlias).AppendLine(".*,");
            for (var i = 0; i < rollupProjections.Count; i++)
            {
                var (expr, alias) = rollupProjections[i];
                sb.Append("    ").Append(expr).Append(" AS [").Append(alias).Append(']');
                sb.AppendLine(i < rollupProjections.Count - 1 ? "," : string.Empty);
            }
            sb.Append("FROM [").Append(schema).Append("].[").Append(sourceTable).Append("] AS ")
              .AppendLine(baseAlias);
            sb.AppendLine("GO");
            return sb.ToString();
        }

        // Layered CTE path. Layer 0 = rollups (or pass-through when no rollups),
        // then one CTE per computed so later expressions can resolve earlier aliases.
        sb.AppendLine("WITH");
        sb.AppendLine("r AS (");
        if (rollupProjections.Count == 0)
        {
            sb.Append("    SELECT ").Append(baseAlias).AppendLine(".*");
        }
        else
        {
            sb.Append("    SELECT ").Append(baseAlias).AppendLine(".*,");
            for (var i = 0; i < rollupProjections.Count; i++)
            {
                var (expr, alias) = rollupProjections[i];
                sb.Append("        ").Append(expr).Append(" AS [").Append(alias).Append(']');
                sb.AppendLine(i < rollupProjections.Count - 1 ? "," : string.Empty);
            }
        }
        sb.Append("    FROM [").Append(schema).Append("].[").Append(sourceTable).Append("] AS ")
          .AppendLine(baseAlias);

        string prevLayer = "r";
        for (var i = 0; i < computedProjections.Count; i++)
        {
            var (expr, alias) = computedProjections[i];
            var layerName = "c" + i;
            sb.Append("),").AppendLine();
            sb.Append(layerName).AppendLine(" AS (");
            sb.Append("    SELECT ").Append(prevLayer).Append(".*, ")
              .Append(expr).Append(" AS [").Append(alias).AppendLine("]");
            sb.Append("    FROM ").AppendLine(prevLayer);
            prevLayer = layerName;
        }
        sb.AppendLine(")");
        sb.Append("SELECT * FROM ").AppendLine(prevLayer);
        sb.AppendLine("GO");
        return sb.ToString();
    }

    private static string RenderRollupSubquery(RollupDef def, string schema, string baseAlias,
        IReadOnlySet<string>? extViewModels = null)
    {
        var target = def.Target;
        var fkColumn = ToPascalCase(def.Fk);
        // M3L parses `@rollup(Target.fk, sum(col))` into Aggregate="sum" + Field="col".
        // For `count` there is no Field.
        var aggregate = (def.Aggregate ?? "count").Trim().ToLowerInvariant();
        var field = def.Field;

        // When the aggregated column is a computed/rollup field on the target
        // model, it only exists in the target's _ext view, not the base table.
        // Use the _ext view as the FROM source when the target has one.
        var fromTarget = (extViewModels != null && extViewModels.Contains(target))
            ? target + "_ext"
            : target;

        var innerExpr = aggregate switch
        {
            "count" => "COUNT(*)",
            "sum" when !string.IsNullOrEmpty(field) => $"ISNULL(SUM([{ToPascalCase(field)}]), 0)",
            "avg" when !string.IsNullOrEmpty(field) => $"AVG([{ToPascalCase(field)}])",
            "min" when !string.IsNullOrEmpty(field) => $"MIN([{ToPascalCase(field)}])",
            "max" when !string.IsNullOrEmpty(field) => $"MAX([{ToPascalCase(field)}])",
            _ => throw new NotSupportedException(
                $"Unsupported rollup: aggregate='{aggregate}' field='{field}'."),
        };

        return $"(SELECT {innerExpr} FROM [{schema}].[{fromTarget}] WHERE [{fkColumn}] = {baseAlias}.[Id])";
    }

    private static string NormalizeComputedExpression(string expr)
    {
        // Convert bare snake_case identifiers to bracketed PascalCase columns,
        // but leave the contents of single-quoted string literals untouched.
        // Bracketed identifiers [foo] are also left alone to allow manual escape.
        //
        // Split on literal boundaries so only non-literal segments are transformed.
        // SQL single-quoted string literals double '' to escape; preserve that.
        var sb = new System.Text.StringBuilder(expr.Length + 16);
        int i = 0;
        while (i < expr.Length)
        {
            var c = expr[i];
            if (c == '\'')
            {
                // Copy the literal verbatim, including the closing quote.
                sb.Append(c);
                i++;
                while (i < expr.Length)
                {
                    sb.Append(expr[i]);
                    if (expr[i] == '\'')
                    {
                        // '' escape sequence → stay inside the literal
                        if (i + 1 < expr.Length && expr[i + 1] == '\'')
                        {
                            sb.Append(expr[++i]);
                            i++;
                            continue;
                        }
                        i++;
                        break;
                    }
                    i++;
                }
                continue;
            }
            if (c == '[')
            {
                // Already-bracketed identifier — copy verbatim through ']'.
                sb.Append(c);
                i++;
                while (i < expr.Length)
                {
                    sb.Append(expr[i]);
                    if (expr[i] == ']') { i++; break; }
                    i++;
                }
                continue;
            }
            // Scan ahead to the next literal/bracket boundary and run the regex
            // on that plain-text slice in one shot.
            int start = i;
            while (i < expr.Length && expr[i] != '\'' && expr[i] != '[') i++;
            var slice = expr.AsSpan(start, i - start).ToString();
            sb.Append(Regex.Replace(slice, @"\b[a-z][a-z0-9_]*\b", m =>
            {
                var ident = m.Value;
                if (IsSqlKeyword(ident)) return ident;
                return "[" + ToPascalCase(ident) + "]";
            }));
        }
        return sb.ToString();
    }

    private static bool IsSqlKeyword(string s) => s.ToLowerInvariant() switch
    {
        "null" or "true" or "false" or "case" or "when" or "then" or "else" or "end"
            or "and" or "or" or "not" or "in" or "like" or "between" => true,
        _ => false,
    };

    private static string ToPascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
