using System.Text;
using System.Text.RegularExpressions;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Sql;

/// <summary>
/// Renders a <c>{Name}FullView</c> SQL view that combines Lookup (LEFT JOINs),
/// Rollup (correlated subqueries), and Computed (CTE expressions) derived fields.
/// This is the second layer of the view derivation chain:
/// <c>Entity → UdView → FullView → ExtView</c>.
/// <para>
/// When the model has a <c>deleted_at</c> field (NeedsUdView = true), FullView
/// sources from <c>{Name}UdView</c> so soft-delete filtering propagates upward.
/// Otherwise it sources from the base table.
/// </para>
/// <para>
/// <b>Flat SELECT</b> path (no Computed fields): Lookups and Rollups are
/// projected in a single SELECT. Each unique FK column produces one LEFT JOIN;
/// rollup aggregates become correlated subqueries.
/// </para>
/// <para>
/// <b>CTE path</b> (any Computed field): An <c>r</c> CTE holds Lookups and
/// Rollups; then one CTE layer per Computed expression is chained so that later
/// computed columns can reference aliases introduced by earlier ones (SQL Server
/// forbids SELECT-list alias references within the same SELECT level).
/// </para>
/// <para>
/// <b>Indexed view opt-in</b>: if any rollup field carries <c>@indexed</c>,
/// the rendered view includes <c>WITH SCHEMABINDING</c>. The DBA can then hand-
/// author <c>CREATE UNIQUE CLUSTERED INDEX</c> in the <c>dbo/Views/</c> folder.
/// </para>
/// </remarks>
/// </summary>
public static class FullViewRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    /// <summary>
    /// Renders the FullView SQL.
    /// </summary>
    /// <param name="plan">View plan for the model.</param>
    /// <param name="schema">SQL schema name (e.g. "dbo").</param>
    /// <param name="fullViewModels">
    /// Set of model names that have a FullView. Used so rollup subqueries target
    /// <c>{TargetName}FullView</c> when the rollup target itself has derived fields.
    /// </param>
    public static string Render(ViewPlan plan, string schema, IReadOnlySet<string>? fullViewModels = null)
    {
        ArgumentNullException.ThrowIfNull(plan);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);
        if (!plan.NeedsFullView)
            throw new InvalidOperationException($"Model '{plan.Model.Name}' does not need a FullView.");

        var baseName = plan.Model.Name;
        var viewName = baseName + "FullView";
        // Source: UdView when soft-delete is active (so the filter propagates); base table otherwise.
        // Either way the source exposes the same physical column set (UdView projects the base
        // columns 1:1), so the explicit base projection is identical in both cases.
        var sourceTable = plan.NeedsUdView ? baseName + "UdView" : baseName;
        const string baseAlias = "b";

        // Explicit base-column projection instead of `b.*` — makes the generated view text
        // track the table's columns so declarative schema tools re-define the view when a
        // column is added, rather than leaving a `SELECT *` view silently stale (see BaseColumns).
        var baseProjection = BaseColumns.Projection(plan.Model, baseAlias);

        var hasIndexed = plan.Rollups.Any(r => r.Attributes.Any(a =>
            string.Equals(a.Name, "indexed", StringComparison.OrdinalIgnoreCase)));

        // --- Build JOIN list (one per unique FK column) ---
        var joinsByFk = new Dictionary<string, JoinInfo>(StringComparer.Ordinal);
        var lookupColumns = new List<(string expr, string alias)>();
        foreach (var lookup in plan.Lookups)
        {
            var path = lookup.Lookup?.Path
                ?? throw new InvalidOperationException(
                    $"Lookup field '{plan.Model.Name}.{lookup.Name}' has no parsed LookupDef.");
            var (fkField, targetColumn) = ParsePath(path);

            if (!joinsByFk.TryGetValue(fkField, out var join))
            {
                var target = ResolveReferenceTarget(plan.Model, fkField);
                var alias = "j_" + fkField;
                join = new JoinInfo(TargetTable: target, FkColumn: ToPascalCase(fkField), Alias: alias);
                joinsByFk[fkField] = join;
            }
            lookupColumns.Add(($"{join.Alias}.[{ToPascalCase(targetColumn)}]", ToPascalCase(lookup.Name)));
        }

        // --- Build rollup subquery list ---
        var rollupColumns = new List<(string expr, string alias)>();
        foreach (var rollup in plan.Rollups)
        {
            var def = rollup.Rollup
                ?? throw new InvalidOperationException(
                    $"Rollup field '{plan.Model.Name}.{rollup.Name}' has no parsed RollupDef.");
            rollupColumns.Add((
                expr: RenderRollupSubquery(def, schema, baseAlias, fullViewModels),
                alias: ToPascalCase(rollup.Name)));
        }

        // --- Build computed expression list ---
        var computedColumns = new List<(string expr, string alias)>();
        foreach (var computed in plan.Computeds)
        {
            var def = computed.Computed
                ?? throw new InvalidOperationException(
                    $"Computed field '{plan.Model.Name}.{computed.Name}' has no parsed ComputedDef.");
            computedColumns.Add((
                expr: NormalizeComputedExpression(def.Expression ?? string.Empty),
                alias: ToPascalCase(computed.Name)));
        }

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE VIEW [").Append(schema).Append("].[").Append(viewName).Append(']');
        if (hasIndexed) sb.Append(" WITH SCHEMABINDING");
        sb.AppendLine();
        sb.AppendLine("AS");

        if (computedColumns.Count == 0)
        {
            // Flat SELECT path: all projected columns in one level.
            var allProjected = lookupColumns.Concat(rollupColumns).ToList();
            sb.Append("SELECT ").Append(baseProjection).AppendLine(",");
            for (var i = 0; i < allProjected.Count; i++)
            {
                var (expr, alias) = allProjected[i];
                sb.Append("    ").Append(expr).Append(" AS [").Append(alias).Append(']');
                sb.AppendLine(i < allProjected.Count - 1 ? "," : string.Empty);
            }
            sb.Append("FROM [").Append(schema).Append("].[").Append(sourceTable).Append("] AS ")
              .AppendLine(baseAlias);
            AppendJoins(sb, schema, joinsByFk, baseAlias);
            sb.AppendLine("GO");
            return sb.ToString();
        }

        // CTE path: r = (Lookups + Rollups), then one CTE per Computed.
        sb.AppendLine("WITH");
        sb.AppendLine("r AS (");

        var rProjected = lookupColumns.Concat(rollupColumns).ToList();
        if (rProjected.Count == 0)
        {
            sb.Append("    SELECT ").AppendLine(baseProjection);
        }
        else
        {
            sb.Append("    SELECT ").Append(baseProjection).AppendLine(",");
            for (var i = 0; i < rProjected.Count; i++)
            {
                var (expr, alias) = rProjected[i];
                sb.Append("        ").Append(expr).Append(" AS [").Append(alias).Append(']');
                sb.AppendLine(i < rProjected.Count - 1 ? "," : string.Empty);
            }
        }
        sb.Append("    FROM [").Append(schema).Append("].[").Append(sourceTable).Append("] AS ")
          .AppendLine(baseAlias);
        AppendJoins(sb, schema, joinsByFk, baseAlias, indent: "    ");

        string prevLayer = "r";
        for (var i = 0; i < computedColumns.Count; i++)
        {
            var (expr, alias) = computedColumns[i];
            var layerName = "c" + i;
            sb.Append("),").AppendLine();
            sb.Append(layerName).AppendLine(" AS (");
            sb.Append("    SELECT ").Append(prevLayer).Append(".*, ")
              .Append(expr).Append(" AS [").Append(alias).AppendLine("]");
            sb.Append("    FROM ").AppendLine(prevLayer);
            prevLayer = layerName;
        }
        sb.AppendLine(")");
        sb.Append("SELECT * FROM ").AppendLine(prevLayer);
        sb.AppendLine("GO");
        return sb.ToString();
    }

    private static void AppendJoins(
        StringBuilder sb,
        string schema,
        Dictionary<string, JoinInfo> joinsByFk,
        string baseAlias,
        string indent = "")
    {
        foreach (var join in joinsByFk.Values.OrderBy(j => j.Alias, StringComparer.Ordinal))
        {
            sb.Append(indent)
              .Append("LEFT JOIN [").Append(schema).Append("].[").Append(join.TargetTable)
              .Append("] AS ").Append(join.Alias)
              .Append(" ON ").Append(baseAlias).Append(".[").Append(join.FkColumn).Append("] = ")
              .Append(join.Alias).AppendLine(".[Id]");
        }
    }

    private static string RenderRollupSubquery(RollupDef def, string schema, string baseAlias,
        IReadOnlySet<string>? fullViewModels)
    {
        var target = def.Target;
        var fkColumn = ToPascalCase(def.Fk);
        var aggregate = (def.Aggregate ?? "count").Trim().ToLowerInvariant();
        var field = def.Field;

        // When the rollup target itself has derived fields, source from its FullView.
        var fromTarget = (fullViewModels != null && fullViewModels.Contains(target))
            ? target + "FullView"
            : target;

        var innerExpr = aggregate switch
        {
            "count" => "COUNT(*)",
            "sum" when !string.IsNullOrEmpty(field) => $"ISNULL(SUM([{ToPascalCase(field)}]), 0)",
            "avg" when !string.IsNullOrEmpty(field) => $"AVG([{ToPascalCase(field)}])",
            "min" when !string.IsNullOrEmpty(field) => $"MIN([{ToPascalCase(field)}])",
            "max" when !string.IsNullOrEmpty(field) => $"MAX([{ToPascalCase(field)}])",
            _ => throw new NotSupportedException(
                $"Unsupported rollup: aggregate='{aggregate}' field='{field}'."),
        };

        return $"(SELECT {innerExpr} FROM [{schema}].[{fromTarget}] WHERE [{fkColumn}] = {baseAlias}.[Id])";
    }

    private static string NormalizeComputedExpression(string expr)
    {
        var sb = new StringBuilder(expr.Length + 16);
        int i = 0;
        while (i < expr.Length)
        {
            var c = expr[i];
            if (c == '\'')
            {
                sb.Append(c);
                i++;
                while (i < expr.Length)
                {
                    sb.Append(expr[i]);
                    if (expr[i] == '\'')
                    {
                        if (i + 1 < expr.Length && expr[i + 1] == '\'')
                        {
                            sb.Append(expr[++i]);
                            i++;
                            continue;
                        }
                        i++;
                        break;
                    }
                    i++;
                }
                continue;
            }
            if (c == '[')
            {
                sb.Append(c);
                i++;
                while (i < expr.Length)
                {
                    sb.Append(expr[i]);
                    if (expr[i] == ']') { i++; break; }
                    i++;
                }
                continue;
            }
            int start = i;
            while (i < expr.Length && expr[i] != '\'' && expr[i] != '[') i++;
            var slice = expr.AsSpan(start, i - start).ToString();
            sb.Append(Regex.Replace(slice, @"\b[a-z][a-z0-9_]*\b", m =>
            {
                var ident = m.Value;
                if (IsSqlKeyword(ident)) return ident;
                return "[" + ToPascalCase(ident) + "]";
            }));
        }
        return sb.ToString();
    }

    private static bool IsSqlKeyword(string s) => s.ToLowerInvariant() switch
    {
        "null" or "true" or "false" or "case" or "when" or "then" or "else" or "end"
            or "and" or "or" or "not" or "in" or "like" or "between" => true,
        _ => false,
    };

    private static (string fk, string column) ParsePath(string path)
    {
        var idx = path.IndexOf('.');
        if (idx <= 0 || idx >= path.Length - 1)
            throw new InvalidOperationException($"Invalid lookup path '{path}'. Expected 'fk.column'.");
        return (path[..idx], path[(idx + 1)..]);
    }

    private static string ResolveReferenceTarget(ResolvedModel model, string fkFieldName)
    {
        var field = model.Fields.FirstOrDefault(f =>
            string.Equals(f.Name, fkFieldName, StringComparison.Ordinal));
        if (field is null)
            throw new InvalidOperationException(
                $"Model '{model.Name}' has no field '{fkFieldName}' (referenced by a lookup path).");

        var refAttr = field.Attributes.FirstOrDefault(a =>
            string.Equals(a.Name, "reference", StringComparison.OrdinalIgnoreCase));
        if (refAttr?.Args is null || refAttr.Args.Count == 0)
            throw new InvalidOperationException(
                $"Lookup FK '{model.Name}.{fkFieldName}' is missing an @reference(Target) attribute.");

        var first = refAttr.Args[0];
        return first.ValueKind == System.Text.Json.JsonValueKind.String
            ? first.GetString() ?? throw new InvalidOperationException("Empty reference target.")
            : first.GetRawText();
    }

    private static string ToPascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }

    private sealed record JoinInfo(string TargetTable, string FkColumn, string Alias);
}
