using System.Text;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Sql;

/// <summary>
/// Renders a <c>{Name}FullView</c> SQL view: the base table plus a LEFT JOIN
/// for every <c>@lookup(fk.field)</c> declaration. Each unique FK column
/// produces one JOIN (shared across all lookups that traverse it) to
/// keep the generated SQL compact and the query plan predictable.
/// </summary>
/// <remarks>
/// Resolution strategy for a lookup field such as
/// <c>customer_name: string @lookup(customer_id.name)</c>:
/// <list type="number">
/// <item><description>Split the dotted path: <c>fk = "customer_id"</c>,
/// <c>column = "name"</c>.</description></item>
/// <item><description>Locate the base-model field named <c>customer_id</c>
/// and read its <c>@reference(Customer)</c> attribute — that's the
/// JOINed table.</description></item>
/// <item><description>Alias the join per FK column (<c>j_customer_id</c>)
/// and use PascalCase for the projected column names on both sides.</description></item>
/// </list>
/// Lookups whose FK can't be resolved raise <see cref="InvalidOperationException"/>
/// — the semantic analyzer will eventually catch this earlier, but the
/// renderer still guards to fail fast during generator development.
/// </remarks>
public static class FullViewRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(ViewPlan plan, string schema)
    {
        ArgumentNullException.ThrowIfNull(plan);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);
        if (!plan.NeedsFullView)
            throw new InvalidOperationException($"Model '{plan.Model.Name}' does not need a full view.");

        var baseName = plan.Model.Name;
        var viewName = baseName + "FullView";
        var baseAlias = "b";

        // Group lookups by FK column so each join is emitted once.
        var joinsByFk = new Dictionary<string, JoinInfo>(StringComparer.Ordinal);
        var projectedColumns = new List<(string expr, string alias)>();

        foreach (var lookup in plan.Lookups)
        {
            var path = lookup.Lookup?.Path
                ?? throw new InvalidOperationException(
                    $"Lookup field '{plan.Model.Name}.{lookup.Name}' has no parsed LookupDef.");
            var (fkField, targetColumn) = ParsePath(path);

            if (!joinsByFk.TryGetValue(fkField, out var join))
            {
                var target = ResolveReferenceTarget(plan.Model, fkField);
                var alias = "j_" + fkField;
                join = new JoinInfo(TargetTable: target, FkColumn: ToPascalCase(fkField), Alias: alias);
                joinsByFk[fkField] = join;
            }

            var projected = ToPascalCase(lookup.Name);
            var sourceColumn = ToPascalCase(targetColumn);
            projectedColumns.Add(($"{join.Alias}.[{sourceColumn}]", projected));
        }

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE VIEW [").Append(schema).Append("].[").Append(viewName).AppendLine("]");
        sb.AppendLine("AS");
        sb.Append("SELECT ").Append(baseAlias).AppendLine(".*,");

        for (var i = 0; i < projectedColumns.Count; i++)
        {
            var (expr, alias) = projectedColumns[i];
            sb.Append("    ").Append(expr).Append(" AS [").Append(alias).Append(']');
            sb.AppendLine(i < projectedColumns.Count - 1 ? "," : string.Empty);
        }

        sb.Append("FROM [").Append(schema).Append("].[").Append(baseName).Append("] AS ")
          .AppendLine(baseAlias);

        foreach (var join in joinsByFk.Values.OrderBy(j => j.Alias, StringComparer.Ordinal))
        {
            sb.Append("LEFT JOIN [").Append(schema).Append("].[").Append(join.TargetTable)
              .Append("] AS ").Append(join.Alias)
              .Append(" ON ").Append(baseAlias).Append(".[").Append(join.FkColumn).Append("] = ")
              .Append(join.Alias).AppendLine(".[Id]");
        }

        sb.AppendLine("GO");
        return sb.ToString();
    }

    private static (string fk, string column) ParsePath(string path)
    {
        var idx = path.IndexOf('.');
        if (idx <= 0 || idx >= path.Length - 1)
            throw new InvalidOperationException($"Invalid lookup path '{path}'. Expected 'fk.column'.");
        return (path[..idx], path[(idx + 1)..]);
    }

    private static string ResolveReferenceTarget(ResolvedModel model, string fkFieldName)
    {
        var field = model.Fields.FirstOrDefault(f =>
            string.Equals(f.Name, fkFieldName, StringComparison.Ordinal));
        if (field is null)
            throw new InvalidOperationException(
                $"Model '{model.Name}' has no field '{fkFieldName}' (referenced by a lookup path).");

        var refAttr = field.Attributes.FirstOrDefault(a =>
            string.Equals(a.Name, "reference", StringComparison.OrdinalIgnoreCase));
        if (refAttr?.Args is null || refAttr.Args.Count == 0)
            throw new InvalidOperationException(
                $"Lookup FK '{model.Name}.{fkFieldName}' is missing an @reference(Target) attribute.");

        var first = refAttr.Args[0];
        return first.ValueKind == System.Text.Json.JsonValueKind.String
            ? first.GetString() ?? throw new InvalidOperationException("Empty reference target.")
            : first.GetRawText();
    }

    private static string ToPascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }

    private sealed record JoinInfo(string TargetTable, string FkColumn, string Alias);
}
