using System.Text;

namespace MddBooster.Generators.Sql;

/// <summary>
/// Renders the SSDT post-deployment refresh script for all generated views.
/// FullViews (no CTEs) are refreshed via sp_refreshview.
/// ExtViews (CTE-based) require ALTER VIEW because SQL Server's sp_refreshview
/// does not support views defined with a CTE (WITH ... AS).
/// </summary>
public static class PostDeploymentScriptRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(
        IEnumerable<string> fullViewModelNames,
        IEnumerable<(string modelName, string createSql)> extViews)
    {
        ArgumentNullException.ThrowIfNull(fullViewModelNames);
        ArgumentNullException.ThrowIfNull(extViews);

        var fullViews = fullViewModelNames.ToList();
        var extViewList = extViews.ToList();

        var sb = new StringBuilder();
        sb.AppendLine(Header);

        if (fullViews.Count > 0)
        {
            sb.AppendLine();
            foreach (var name in fullViews)
            {
                sb.Append("EXEC sp_refreshview N'[dbo].[").Append(name).AppendLine("FullView]';");
            }
        }

        foreach (var (_, createSql) in extViewList)
        {
            sb.AppendLine();
            sb.Append(ConvertCreateToAlter(createSql));
        }

        return sb.ToString();
    }

    private static string ConvertCreateToAlter(string createSql)
    {
        var lines = createSql.Split(["\r\n", "\n"], StringSplitOptions.None);
        var result = new List<string>(lines.Length);
        bool headerSkipped = false;
        bool createReplaced = false;

        foreach (var line in lines)
        {
            if (!headerSkipped && line.StartsWith("-- # Code generated"))
            {
                headerSkipped = true;
                continue;
            }
            if (!createReplaced && line.Contains("CREATE VIEW"))
            {
                result.Add(line.Replace("CREATE VIEW", "ALTER VIEW"));
                createReplaced = true;
                continue;
            }
            result.Add(line);
        }

        return string.Join(Environment.NewLine, result).TrimEnd() + Environment.NewLine;
    }
}
