using System.Text;

namespace MddBooster.Generators.Sql;

/// <summary>
/// Renders the SSDT post-deployment refresh script for all generated views.
/// <list type="bullet">
/// <item><description>
/// UdViews (simple WHERE clause, no CTEs) → <c>sp_refreshview</c>.
/// </description></item>
/// <item><description>
/// FullViews without Computed fields (flat SELECT) → <c>sp_refreshview</c>.
/// </description></item>
/// <item><description>
/// FullViews with Computed fields (CTE-based) → <c>ALTER VIEW</c>, because
/// SQL Server's <c>sp_refreshview</c> does not support views defined with CTEs.
/// </description></item>
/// </list>
/// </summary>
public static class PostDeploymentScriptRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(
        IEnumerable<string> udViewModelNames,
        IEnumerable<string> simpleFullViewModelNames,
        IEnumerable<(string modelName, string createSql)> cteFullViews)
    {
        ArgumentNullException.ThrowIfNull(udViewModelNames);
        ArgumentNullException.ThrowIfNull(simpleFullViewModelNames);
        ArgumentNullException.ThrowIfNull(cteFullViews);

        var udViews = udViewModelNames.ToList();
        var simpleFullViews = simpleFullViewModelNames.ToList();
        var cteFullViewList = cteFullViews.ToList();

        var sb = new StringBuilder();
        sb.AppendLine(Header);

        if (udViews.Count > 0)
        {
            sb.AppendLine();
            foreach (var name in udViews)
                sb.Append("EXEC sp_refreshview N'[dbo].[").Append(name).AppendLine("UdView]';");
        }

        if (simpleFullViews.Count > 0)
        {
            sb.AppendLine();
            foreach (var name in simpleFullViews)
                sb.Append("EXEC sp_refreshview N'[dbo].[").Append(name).AppendLine("FullView]';");
        }

        foreach (var (_, createSql) in cteFullViewList)
        {
            sb.AppendLine();
            sb.Append(ConvertCreateToAlter(createSql));
        }

        return sb.ToString();
    }

    private static string ConvertCreateToAlter(string createSql)
    {
        var lines = createSql.Split(["\r\n", "\n"], StringSplitOptions.None);
        var result = new List<string>(lines.Length);
        bool headerSkipped = false;
        bool createReplaced = false;

        foreach (var line in lines)
        {
            if (!headerSkipped && line.StartsWith("-- # Code generated"))
            {
                headerSkipped = true;
                continue;
            }
            if (!createReplaced && line.Contains("CREATE VIEW"))
            {
                result.Add(line.Replace("CREATE VIEW", "ALTER VIEW"));
                createReplaced = true;
                continue;
            }
            result.Add(line);
        }

        return string.Join(Environment.NewLine, result).TrimEnd() + Environment.NewLine;
    }
}
