using System.Text;
using System.Text.RegularExpressions;

namespace MddBooster.Generators.Sql;

/// <summary>
/// Renders the SSDT post-deployment refresh script.
/// Scans Views_gen/ and Views/ for all .sql view files, extracts inter-view
/// dependencies from the SQL body, topologically sorts them, and emits
/// <c>EXEC sp_refreshview</c> for each view in dependency order.
/// </summary>
public static class PostDeploymentScriptRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    private static readonly Regex ViewNameRe = new(
        @"CREATE\s+VIEW\s+\[dbo\]\.\[(\w+)\]",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    private static readonly Regex ViewRefRe = new(
        @"\[dbo\]\.\[(\w+)\]",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    /// <param name="viewsGenDir">Path to dbo/Views_gen/ (auto-generated views).</param>
    /// <param name="viewsDir">Path to dbo/Views/ (hand-maintained views). May be null or missing.</param>
    public static string Render(string viewsGenDir, string? viewsDir = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(viewsGenDir);

        var views = new Dictionary<string, string>(StringComparer.Ordinal);
        CollectViews(viewsGenDir, views);
        if (viewsDir != null) CollectViews(viewsDir, views);

        if (views.Count == 0)
            return Header + Environment.NewLine;

        var deps = BuildDependencies(views);
        var sorted = TopoSort(views.Keys, deps);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine();
        foreach (var name in sorted)
            sb.Append("EXEC sp_refreshview N'[dbo].[").Append(name).AppendLine("]';");

        return sb.ToString();
    }

    private static void CollectViews(string dir, Dictionary<string, string> views)
    {
        if (!Directory.Exists(dir)) return;
        foreach (var file in Directory.GetFiles(dir, "*.sql"))
        {
            var sql = File.ReadAllText(file);
            var m = ViewNameRe.Match(sql);
            if (m.Success)
                views[m.Groups[1].Value] = sql;
        }
    }

    private static Dictionary<string, HashSet<string>> BuildDependencies(
        Dictionary<string, string> views)
    {
        var deps = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        foreach (var (name, sql) in views)
        {
            deps[name] = [];
            var m = ViewNameRe.Match(sql);
            var body = m.Success ? sql[(m.Index + m.Length)..] : sql;

            foreach (Match refMatch in ViewRefRe.Matches(body))
            {
                var refName = refMatch.Groups[1].Value;
                if (views.ContainsKey(refName) && !StringComparer.Ordinal.Equals(refName, name))
                    deps[name].Add(refName);
            }
        }
        return deps;
    }

    private static List<string> TopoSort(
        IEnumerable<string> allNames,
        Dictionary<string, HashSet<string>> deps)
    {
        var inDegree = allNames.ToDictionary(n => n, _ => 0, StringComparer.Ordinal);
        var dependents = allNames.ToDictionary(n => n, _ => new List<string>(), StringComparer.Ordinal);

        foreach (var (name, dependencies) in deps)
        {
            foreach (var dep in dependencies)
            {
                if (!inDegree.ContainsKey(dep)) continue;
                inDegree[name]++;
                dependents[dep].Add(name);
            }
        }

        var queue = new Queue<string>(inDegree
            .Where(kv => kv.Value == 0)
            .Select(kv => kv.Key)
            .OrderBy(n => n, StringComparer.Ordinal));

        var result = new List<string>();
        while (queue.Count > 0)
        {
            var node = queue.Dequeue();
            result.Add(node);
            foreach (var dependent in dependents[node].OrderBy(n => n, StringComparer.Ordinal))
            {
                if (--inDegree[dependent] == 0)
                    queue.Enqueue(dependent);
            }
        }

        // Append any remaining (cyclic dependencies — should not occur in well-formed SSDT)
        result.AddRange(inDegree
            .Where(kv => kv.Value > 0)
            .Select(kv => kv.Key)
            .OrderBy(n => n, StringComparer.Ordinal));

        return result;
    }
}
