using System.Text;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Sql;

public static class TableRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(ResolvedModel model, string schema, IReadOnlyDictionary<string, EnumNode>? enumLookup = null)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE TABLE [").Append(schema).Append("].[").Append(model.Name).AppendLine("]");
        sb.AppendLine("(");

        // Base tables carry stored columns only. Lookup/Rollup/Computed fields
        // materialize in the _ext view (Phase I, ViewPlanner) — they must never
        // appear as physical columns here.
        var storedFields = model.Fields.Where(f => f.Kind == FieldKind.Stored).ToList();
        var columnLines = storedFields.Select(f => ColumnRenderer.Render(f, enumLookup)).ToList();

        // Unique 제약 분기: nullable은 filtered unique index(CREATE INDEX ... WHERE IS NOT NULL)로
        // 테이블 뒤에 별도 statement로 emit. non-nullable만 inline CONSTRAINT.
        // SQL Server의 UNIQUE NONCLUSTERED는 NULL을 "값"으로 취급하여 NULL 2개 이상을 허용하지 않으므로,
        // nullable unique 필드는 filtered index가 유일하게 정확한 모델링.
        var inlineUniques = new List<string>();
        var postTableStatements = new List<string>();
        foreach (var field in storedFields)
        {
            if (!HasAttribute(field, "unique")) continue;
            if (HasAttribute(field, "pk")) continue; // PK는 이미 유일

            var column = ToPascalCase(field.Name);
            if (field.Nullable)
            {
                postTableStatements.Add(
                    $"CREATE UNIQUE NONCLUSTERED INDEX [UK_{model.Name}_{column}] " +
                    $"ON [{schema}].[{model.Name}]([{column}]) " +
                    $"WHERE [{column}] IS NOT NULL;");
            }
            else
            {
                inlineUniques.Add($"CONSTRAINT [UK_{model.Name}_{column}] UNIQUE NONCLUSTERED ([{column}])");
            }
        }

        var bodyLines = new List<string>(columnLines.Count + inlineUniques.Count);
        bodyLines.AddRange(columnLines);
        bodyLines.AddRange(inlineUniques);

        for (var i = 0; i < bodyLines.Count; i++)
        {
            sb.Append("    ").Append(bodyLines[i]);
            if (i < bodyLines.Count - 1)
            {
                sb.Append(',');
            }
            sb.AppendLine();
        }

        sb.AppendLine(")");
        sb.AppendLine("GO");

        foreach (var stmt in postTableStatements)
        {
            sb.AppendLine(stmt);
            sb.AppendLine("GO");
        }

        return sb.ToString();
    }

    private static bool HasAttribute(FieldNode field, string name) =>
        field.Attributes.Any(a => string.Equals(a.Name, name, StringComparison.OrdinalIgnoreCase));

    private static string ToPascalCase(string snake)
    {
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
