using System.Text;
using System.Text.Json;
using M3L.Native;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Sql;

public static class TableRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(ResolvedModel model, string schema, IReadOnlyDictionary<string, EnumNode>? enumLookup = null)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE TABLE [").Append(schema).Append("].[").Append(model.Name).AppendLine("]");
        sb.AppendLine("(");

        // Base tables carry stored columns only. Lookup/Rollup/Computed fields
        // materialize in the _ext view (Phase I, ViewPlanner) — they must never
        // appear as physical columns here. BaseColumns is the shared authority so
        // the views project exactly the columns this table emits.
        var storedFields = BaseColumns.StoredFields(model).ToList();
        var columnLines = storedFields.Select(f => ColumnRenderer.Render(f, enumLookup)).ToList();

        // Unique 제약 분기: nullable은 filtered unique index(CREATE INDEX ... WHERE IS NOT NULL)로
        // 테이블 뒤에 별도 statement로 emit. non-nullable만 inline CONSTRAINT.
        // SQL Server의 UNIQUE NONCLUSTERED는 NULL을 "값"으로 취급하여 NULL 2개 이상을 허용하지 않으므로,
        // nullable unique 필드는 filtered index가 유일하게 정확한 모델링.
        var inlineUniques = new List<string>();
        var postTableStatements = new List<string>();
        foreach (var field in storedFields)
        {
            if (!HasAttribute(field, "unique")) continue;
            if (HasAttribute(field, "pk")) continue; // PK는 이미 유일

            var column = ToPascalCase(field.Name);
            if (field.Nullable)
            {
                postTableStatements.Add(
                    $"CREATE UNIQUE NONCLUSTERED INDEX [UK_{model.Name}_{column}] " +
                    $"ON [{schema}].[{model.Name}]([{column}]) " +
                    $"WHERE [{column}] IS NOT NULL;");
            }
            else
            {
                inlineUniques.Add($"CONSTRAINT [UK_{model.Name}_{column}] UNIQUE NONCLUSTERED ([{column}])");
            }
        }

        // Sections.Indexes 처리 — table-level @unique(c1, c2) directive + @index(c1) directive를
        // 각각 UNIQUE 제약 / NONCLUSTERED INDEX로 emit. M3L.Native가 directive 형식만 args를 보존하므로
        // `idx_name: @index(col)` 형식은 args 없이 들어와 정보 부족(skip).
        // enum CHECK 제약은 의도적으로 미emit — EF Core가 string converter로 검증하며,
        // SSDT가 CHECK를 매번 Drop→Create로 표현해 dacpac diff가 불안정. (정책: cycle 27)
        AppendSectionIndexes(model, schema, storedFields, inlineUniques, postTableStatements);

        var bodyLines = new List<string>(columnLines.Count + inlineUniques.Count);
        bodyLines.AddRange(columnLines);
        bodyLines.AddRange(inlineUniques);

        for (var i = 0; i < bodyLines.Count; i++)
        {
            sb.Append("    ").Append(bodyLines[i]);
            if (i < bodyLines.Count - 1)
            {
                sb.Append(',');
            }
            sb.AppendLine();
        }

        sb.AppendLine(")");
        sb.AppendLine("GO");

        foreach (var stmt in postTableStatements)
        {
            sb.AppendLine(stmt);
            sb.AppendLine("GO");
        }

        return sb.ToString();
    }

    /// <summary>
    /// `### Indexes` 섹션 처리. M3L.Native 0.5.5+ 기준 두 가지 entry 형식 모두 지원:
    /// <list type="bullet">
    /// <item><c>type=directive</c> — `- @index(c)` / `- @unique(c1, c2)` 형식</item>
    /// <item><c>type=indexed</c> — `- idx_xxx: @index(c)` / `- idx_xxx: @unique(c1, c2)` 라벨드 형식</item>
    /// </list>
    /// 양쪽 다 <c>args</c>(컬럼 배열) + <c>unique</c>(bool) 키를 보유. M3L.Native 0.5.4 호환을 위해
    /// args가 string scalar로 들어올 가능성도 fallback 처리한다.
    /// </summary>
    private static void AppendSectionIndexes(
        ResolvedModel model, string schema,
        IReadOnlyList<FieldNode> storedFields,
        List<string> inlineUniques, List<string> postTableStatements)
    {
        var indexes = model.Source.Sections?.Indexes;
        if (indexes is null || indexes.Count == 0) return;

        // PascalCase 컬럼명 → nullable 매핑. 다중 컬럼 UK에 nullable 컬럼이 끼면
        // SQL Server UNIQUE 제약은 NULL을 값으로 취급(다중 NULL 허용 안 됨)하므로
        // filtered unique index로 변환해 NULL 행을 제약 평가에서 제외해야 한다.
        var columnNullability = storedFields.ToDictionary(
            f => ToPascalCase(f.Name),
            f => f.Nullable,
            StringComparer.Ordinal);

        foreach (var idxEl in indexes)
        {
            if (idxEl.ValueKind != JsonValueKind.Object) continue;

            // type이 directive 또는 indexed일 때만 처리 (정보 부족한 entry 차단)
            if (!idxEl.TryGetProperty("type", out var typeProp)) continue;
            var typeStr = typeProp.GetString();
            if (typeStr != "directive" && typeStr != "indexed") continue;

            if (!idxEl.TryGetProperty("args", out var argsEl)) continue;

            // M3L.Native 0.5.5+: args는 항상 array.
            // 0.5.4 호환: 단일 인자가 string scalar로 들어올 수 있음.
            var cols = new List<string>();
            if (argsEl.ValueKind == JsonValueKind.String)
            {
                var s = argsEl.GetString();
                if (!string.IsNullOrWhiteSpace(s)) cols.Add(ToPascalCase(s!));
            }
            else if (argsEl.ValueKind == JsonValueKind.Array)
            {
                foreach (var a in argsEl.EnumerateArray())
                {
                    var s = a.ValueKind == JsonValueKind.String ? a.GetString() : a.GetRawText();
                    if (!string.IsNullOrWhiteSpace(s)) cols.Add(ToPascalCase(s!));
                }
            }
            if (cols.Count == 0) continue;

            var isUnique = idxEl.TryGetProperty("unique", out var uniqueProp)
                           && uniqueProp.ValueKind == JsonValueKind.True;
            var colJoined = string.Join("_", cols);
            var colList = string.Join(", ", cols.Select(c => $"[{c}]"));

            if (isUnique)
            {
                // 컬럼 중 하나라도 nullable이면 filtered unique index로 emit.
                // 모두 NOT NULL이면 inline UK constraint(테이블 본문에 함께 emit).
                var anyNullable = cols.Any(c =>
                    columnNullability.TryGetValue(c, out var n) && n);
                if (anyNullable)
                {
                    var notNullPredicate = string.Join(" AND ",
                        cols.Select(c => $"[{c}] IS NOT NULL"));
                    postTableStatements.Add(
                        $"CREATE UNIQUE NONCLUSTERED INDEX [UK_{model.Name}_{colJoined}] " +
                        $"ON [{schema}].[{model.Name}] ({colList}) " +
                        $"WHERE {notNullPredicate};");
                }
                else
                {
                    inlineUniques.Add(
                        $"CONSTRAINT [UK_{model.Name}_{colJoined}] UNIQUE NONCLUSTERED ({colList})");
                }
            }
            else
            {
                postTableStatements.Add(
                    $"CREATE NONCLUSTERED INDEX [IX_{model.Name}_{colJoined}] " +
                    $"ON [{schema}].[{model.Name}] ({colList});");
            }
        }
    }

    private static bool HasAttribute(FieldNode field, string name) =>
        field.Attributes.Any(a => string.Equals(a.Name, name, StringComparison.OrdinalIgnoreCase));

    private static string ToPascalCase(string snake)
    {
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
