using System.Text;
using M3L.Native;
using MddBooster.Core.Semantic;
using MddBooster.Core.Naming;

namespace MddBooster.Generators.Sql;

public static class TableRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(
        ResolvedModel model,
        string schema,
        IReadOnlyDictionary<string, EnumNode>? enumLookup = null,
        bool emitEnumCheckConstraints = false,
        bool emitForeignKeyIndexes = false,
        IReadOnlyList<ResolvedModel>? allModels = null)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE TABLE [").Append(schema).Append("].[").Append(model.Name).AppendLine("]");
        sb.AppendLine("(");

        // Base tables carry stored columns only. Lookup/Rollup/Computed fields
        // materialize in the _ext view (Phase I, ViewPlanner) — they must never
        // appear as physical columns here. BaseColumns is the shared authority so
        // the views project exactly the columns this table emits.
        var storedFields = BaseColumns.StoredFields(model).ToList();
        // FK 는 대상 모델의 실제 PK 와 이 렌더의 스키마를 가리킨다(TargetKey). 참조가 없는 모델은
        // 대상 목록 없이도 렌더된다.
        Func<string, ResolvedModel?> findModel = name =>
            allModels?.FirstOrDefault(m => string.Equals(m.Name, name, StringComparison.Ordinal));
        var columnLines = storedFields
            .Select(f => ColumnRenderer.Render(
                f, enumLookup,
                onDelete: OnDeleteRule.For(model, f),
                referencedKey: ReferencedKey(f, model, schema, findModel)))
            .ToList();

        // Unique 제약 분기: nullable은 filtered unique index(CREATE INDEX ... WHERE IS NOT NULL)로
        // 테이블 뒤에 별도 statement로 emit. non-nullable만 inline CONSTRAINT.
        // SQL Server의 UNIQUE NONCLUSTERED는 NULL을 "값"으로 취급하여 NULL 2개 이상을 허용하지 않으므로,
        // nullable unique 필드는 filtered index가 유일하게 정확한 모델링.
        var inlineConstraints = new List<string>();
        var postTableStatements = new List<string>();
        foreach (var field in storedFields)
        {
            if (!HasAttribute(field, "unique")) continue;
            if (HasAttribute(field, "pk")) continue; // PK는 이미 유일

            var column = NameCasing.ToPascalCase(field.Name);
            if (field.Nullable)
            {
                postTableStatements.Add(
                    $"CREATE UNIQUE NONCLUSTERED INDEX [UK_{model.Name}_{column}] " +
                    $"ON [{schema}].[{model.Name}]([{column}]) " +
                    $"WHERE [{column}] IS NOT NULL;");
            }
            else
            {
                inlineConstraints.Add($"CONSTRAINT [UK_{model.Name}_{column}] UNIQUE NONCLUSTERED ([{column}])");
            }
        }

        // field-level @index (스펙 §10.8.1 — DB 인덱스). PK/unique는 이미 인덱스를 가지므로 제외.
        // (rollup 필드의 @indexed는 별개 확장 — WITH SCHEMABINDING 트리거, FullViewRenderer 소관.)
        foreach (var field in storedFields)
        {
            if (!HasAttribute(field, "index")) continue;
            if (HasAttribute(field, "pk") || HasAttribute(field, "unique")) continue;

            var column = NameCasing.ToPascalCase(field.Name);
            postTableStatements.Add(
                $"CREATE NONCLUSTERED INDEX [IX_{model.Name}_{column}] " +
                $"ON [{schema}].[{model.Name}] ([{column}]);");
        }

        // Sections.Indexes 처리 — table-level @unique(c1, c2) directive + @index(c1) directive를
        // 각각 UNIQUE 제약 / NONCLUSTERED INDEX로 emit. M3L.Native가 directive 형식만 args를 보존하므로
        // `idx_name: @index(col)` 형식은 args 없이 들어와 정보 부족(skip).
        AppendSectionIndexes(model, schema, storedFields, inlineConstraints, postTableStatements);

        // FK 자동 인덱스 — opt-in. 모델이 이미 덮은 컬럼은 판정기가 걸러낸다.
        if (emitForeignKeyIndexes)
        {
            foreach (var field in ForeignKeyIndexPlanner.Plan(model))
            {
                var column = NameCasing.ToPascalCase(field.Name);
                postTableStatements.Add(
                    $"CREATE NONCLUSTERED INDEX [IX_{model.Name}_{column}] " +
                    $"ON [{schema}].[{model.Name}] ([{column}]);");
            }
        }

        // enum CHECK 제약은 opt-in (기본 off) — SSDT dacpac이 CHECK를 매번 Drop→Create로
        // 재현해 diff가 불안정하므로(정책: cycle 27) SSDT 소비자는 EF Core string converter
        // 검증에 의존한다. 선언형 도구(Schemorph 등) 소비자는 EmitEnumCheckConstraints로
        // DB 레벨 강제를 켠다. NULL은 IN 술어에서 UNKNOWN → CHECK 통과(nullable enum 안전).
        if (emitEnumCheckConstraints && enumLookup is not null)
        {
            foreach (var field in storedFields)
            {
                if (field.Type is null || !enumLookup.TryGetValue(field.Type, out var enumNode)) continue;
                if (enumNode.Values.Count == 0) continue;

                var column = NameCasing.ToPascalCase(field.Name);
                inlineConstraints.Add(
                    $"CONSTRAINT [CK_{model.Name}_{column}] CHECK ({EnumSqlConvention.CheckExpression(enumNode, column)})");
            }
        }

        var bodyLines = new List<string>(columnLines.Count + inlineConstraints.Count);
        bodyLines.AddRange(columnLines);
        bodyLines.AddRange(inlineConstraints);

        for (var i = 0; i < bodyLines.Count; i++)
        {
            sb.Append("    ").Append(bodyLines[i]);
            if (i < bodyLines.Count - 1)
            {
                sb.Append(',');
            }
            sb.AppendLine();
        }

        sb.AppendLine(")");
        sb.AppendLine("GO");

        foreach (var stmt in postTableStatements)
        {
            sb.AppendLine(stmt);
            sb.AppendLine("GO");
        }

        return sb.ToString();
    }

    /// <summary>
    /// `### Indexes` 섹션 처리. entry 해석은 <see cref="SectionIndexParser"/> 몫이고,
    /// 여기서는 이 방언의 표기(PascalCase 컬럼명)와 널 허용 컬럼 분기만 맡는다.
    /// </summary>
    private static void AppendSectionIndexes(
        ResolvedModel model, string schema,
        IReadOnlyList<FieldNode> storedFields,
        List<string> inlineConstraints, List<string> postTableStatements)
    {
        var entries = SectionIndexParser.Parse(model);
        if (entries.Count == 0) return;

        // PascalCase 컬럼명 → nullable 매핑. 다중 컬럼 UK에 nullable 컬럼이 끼면 기본적으로
        // filtered unique index로 변환해 NULL 행을 제약 평가에서 제외한다 — `nulls:
        // "not_distinct"` 선언 시의 예외는 분기 본체(아래) 참조.
        var columnNullability = storedFields.ToDictionary(
            f => NameCasing.ToPascalCase(f.Name),
            f => f.Nullable,
            StringComparer.Ordinal);

        foreach (var entry in entries)
        {
            var cols = entry.Columns.Select(NameCasing.ToPascalCase).ToList();
            var isUnique = entry.IsUnique;
            var colJoined = string.Join("_", cols);
            var colList = string.Join(", ", cols.Select(c => $"[{c}]"));

            if (isUnique)
            {
                // 컬럼 중 하나라도 nullable이면 filtered unique index로 emit — SQL Server의
                // plain UNIQUE는 NULL을 값으로 취급해 다중 NULL을 막으므로, "NULL은 미설정"
                // 의미(NULLS DISTINCT, 기본값)를 내려면 NULL 행을 제약 평가에서 걸러내야 한다.
                // `nulls: "not_distinct"`(m3l `@unique(..., nulls: "not_distinct")`)
                // 를 선언했다면 정반대다 — NULL도 다른 값처럼 유일성 경쟁에 참여해야 하고,
                // 그건 SQL Server의 plain UNIQUE가 **이미 기본으로 하는 일**이라 필터가 필요
                // 없다: 모두 NOT NULL인 경우와 같은 inline 제약으로 충분하다.
                var anyNullable = cols.Any(c =>
                    columnNullability.TryGetValue(c, out var n) && n);
                var needsFilteredIndex = anyNullable && entry.Nulls != "not_distinct";
                if (needsFilteredIndex)
                {
                    var notNullPredicate = string.Join(" AND ",
                        cols.Select(c => $"[{c}] IS NOT NULL"));
                    postTableStatements.Add(
                        $"CREATE UNIQUE NONCLUSTERED INDEX [UK_{model.Name}_{colJoined}] " +
                        $"ON [{schema}].[{model.Name}] ({colList}) " +
                        $"WHERE {notNullPredicate};");
                }
                else
                {
                    inlineConstraints.Add(
                        $"CONSTRAINT [UK_{model.Name}_{colJoined}] UNIQUE NONCLUSTERED ({colList})");
                }
            }
            else
            {
                postTableStatements.Add(
                    $"CREATE NONCLUSTERED INDEX [IX_{model.Name}_{colJoined}] " +
                    $"ON [{schema}].[{model.Name}] ({colList});");
            }
        }
    }

    private static bool HasAttribute(FieldNode field, string name) =>
        MddBooster.Core.Ast.FieldAttributes.Has(field, name);

    private static string? ReferencedKey(
        FieldNode field, ResolvedModel owner, string schema, Func<string, ResolvedModel?> findModel)
    {
        var target = MddBooster.Core.Ast.FieldAttributes.FirstArg(field, "reference");
        if (string.IsNullOrEmpty(target)) return null;

        var targetModel = TargetKey.Resolve(target!, findModel, $"'{owner.Name}.{field.Name}'");
        return $"[{schema}].[{targetModel.Name}]([{TargetKey.PkColumn(targetModel)}])";
    }
}
