using System.Text;
using MddBooster.Core.Semantic;

namespace MddBooster.Generators.Sql;

/// <summary>
/// Renders a <c>{Name}UdView</c> (UndeletedView) that selects all rows from
/// the base table where <c>[DeletedAt] IS NULL</c>. This is the first layer
/// of the view derivation chain for soft-delete-enabled entities:
/// <c>Entity → UdView → FullView → ExtView</c>.
/// <para>
/// The base columns are projected <b>explicitly</b> (not <c>SELECT *</c>) so
/// the generated view text tracks the table's column set — see
/// <see cref="BaseColumns"/> for why this matters to declarative schema tools.
/// </para>
/// </summary>
public static class UdViewRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(ResolvedModel model, string schema)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);

        var modelName = model.Name;
        var projection = BaseColumns.Projection(model);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE VIEW [").Append(schema).Append("].[").Append(modelName).AppendLine("UdView]");
        sb.AppendLine("AS");
        sb.Append("SELECT ").Append(projection)
          .Append(" FROM [").Append(schema).Append("].[").Append(modelName).AppendLine("]");
        sb.AppendLine("WHERE [DeletedAt] IS NULL");
        sb.AppendLine("GO");
        return sb.ToString();
    }
}
