using System.Text;

namespace MddBooster.Generators.Sql;

/// <summary>
/// Renders a <c>{Name}UdView</c> (UndeletedView) that selects all rows from
/// the base table where <c>[DeletedAt] IS NULL</c>. This is the first layer
/// of the view derivation chain for soft-delete-enabled entities:
/// <c>Entity → UdView → FullView → ExtView</c>.
/// </summary>
public static class UdViewRenderer
{
    private const string Header = "-- # Code generated by \"mdd-booster\"; DO NOT EDIT.";

    public static string Render(string modelName, string schema)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(modelName);
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);

        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.Append("CREATE VIEW [").Append(schema).Append("].[").Append(modelName).AppendLine("UdView]");
        sb.AppendLine("AS");
        sb.Append("SELECT * FROM [").Append(schema).Append("].[").Append(modelName).AppendLine("]");
        sb.AppendLine("WHERE [DeletedAt] IS NULL");
        sb.AppendLine("GO");
        return sb.ToString();
    }
}
