global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Text.Json;
global using MddBooster.Core.Ast;
global using MddBooster.Core.Generation;
global using MddBooster.Core.Semantic;
global using MddBooster.Generators.Sql;
